### ISSUE TITLE
[Table] Lightweight design

### ISSUE THREAD

**Issue by bryancboyd** [IBM/carbon-addons-iot-react#10]
Add a "lightweight" styling to the table (prop under `options`) that matches the following designs.

This table still maintains all capabilities of the full table (pagination, filter, column selection, batch actions).

![image](https://user-images.githubusercontent.com/2175647/51275050-76c63200-1996-11e9-97bd-c007db306efd.png)

![image](https://user-images.githubusercontent.com/2175647/51275060-7af24f80-1996-11e9-9e96-bf529ec0d870.png)

![image](https://user-images.githubusercontent.com/2175647/51275067-7fb70380-1996-11e9-87b6-a58ec43bcc12.png)

![image](https://user-images.githubusercontent.com/2175647/51275070-83e32100-1996-11e9-8151-07ae7fd05c49.png)

**Comment by scottdickerson** [comment]
this was closed by the integrated PR
