### ISSUE TITLE
[bar charts—all] Helvetica typeface showing up in X and Y-axis

### ISSUE THREAD

**Issue by mjabbink** [IBM/carbon-addons-iot-react#1003]
IBM Plex is being replaced with Helvetica in both X and Y-axis and labels as well.

example:
https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-barchartcard--simple-bar

**Comment by mjabbink** [comment]
some additional screen grabs

<img width="503" alt="Screen Shot 2020-03-12 at 11 59 34 AM" src="https://user-images.githubusercontent.com/32881239/76546154-ffd0e000-6458-11ea-8c46-4887111e0a06.png">


<img width="513" alt="Screen Shot 2020-03-12 at 11 59 24 AM" src="https://user-images.githubusercontent.com/32881239/76546168-04959400-6459-11ea-9fee-4b3895881f24.png">


<img width="501" alt="Screen Shot 2020-03-12 at 11 59 16 AM" src="https://user-images.githubusercontent.com/32881239/76546180-08c1b180-6459-11ea-9018-0d6d1aa12380.png">

**Comment by mjabbink** [comment]
all correct in Carbon Charts
https://carbon-design-system.github.io/carbon-charts/

**Comment by scottdickerson** [comment]
it looks like Plex on my machine, do I maybe have Plex locally installed?

![image](https://user-images.githubusercontent.com/6663002/76567438-bc886880-647c-11ea-9917-b8f9ff6de946.png)

**Comment by scottdickerson** [comment]
yeah that's the issue, our Carbon addons iot repo isn't serving the Plex font as part of the storybook. @tay1orjones @davidicus

**Comment by enricoberti** [comment]
'IBM Plex Sans Condensed' is the one missing in our case and used by Carbon Charts

**Comment by mjabbink** [comment]
yes, that is the style used for those parts of the anatomy. Check with Vince Picone on the type packages from Carbon

**Comment by scottdickerson** [comment]
I have a fix ready where we locally packaging this font in addons-iot.  Would be good if the @carbon/types package automatically provided this for us.

**Comment by tay1orjones** [comment]
I've opened #1007 to follow on from this to remove our fix once it's fixed upstream in either `@carbon/type` or `@carbon/charts`
