### ISSUE TITLE
[Bug] Column resizing breaks row action button container

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#1004]
Tables with column re-sizing seem to ignore the in-line actions container, causing overflow
https://pages.github.ibm.com/maximo-app-framework/graphite/reference-app/#/tables
![Screen Shot 2020-03-12 at 3 39 04 PM](https://media.github.ibm.com/user/17018/files/57804300-647b-11ea-8603-3af23fcfb099)

**Comment by bjornalm** [comment]
_Existing fix_
The default table-layout is fixed for a table that has column resize enabled, which means it doesn't care about the width of the content in the table cells. Normally the content is wrapped when needed, but the "row action column" is an exception. The table-layout can be made dynamic setting the prop
`option: { useAutoTableLayoutForResize: true }`

_Additional fix for this issue:_
Allowing a min-width property for the row action column so we can force it to never shrink beyond that and hence never overflow (given proper minWidth).

**Comment by davidicus** [comment]
discussing solution in internal repo https://github.ibm.com/Watson-IoT/pal-tracking/issues/321?
