### ISSUE TITLE
[table] column ordering slow

### ISSUE THREAD

**Issue by bjornalm** [IBM/carbon-addons-iot-react#1006]
### Describe the bug
The table updates “realtime” while the user is dragging a column and it can cause sluggish and buggy behaviour because of all the processing that is going on per render. See the attached gif for a table with 100 rows.

![column-reorder-issue-1](https://user-images.githubusercontent.com/5167091/76624036-d38a9180-6534-11ea-9e97-e300be27109f.gif)

It is also possible to end up in a state where the columns position keep jumping back and fourth.
![bug2](https://user-images.githubusercontent.com/5167091/76625851-6547ce00-6538-11ea-9a99-e71f4049e891.gif)

With the additional complexity/processing needed for table column resize this behaviour gets worse when `hasResize` is true. 

### To Reproduce
1. Choose a table story with `hasColumnSelection:true`
2. Click the column reorder button
3. Drag a column slowly across the as shown in the GIFs

### Expected behavior
The best in my opinion would be to update the table on drop instead of on drag when rearranging the columns.

### Environment/versions:

- OS: MacOS
- Browser: chrome

**Comment by bjornalm** [comment]
Looking into this, I believe the minimal code change for this is just one row. Changing 
` hover(props, monitor) { ....` to ` drop(props, monitor) { ....` in file `ColumnHeaderSelect.js` will solve this issue.

But we probably want to add some kind of visual feedback that indicates where the drop zones are. I assume that is well supported by react-dnd so that should also be easy.

**Comment by davidicus** [comment]
@lukefirth @JordanWSmith15 is updating after drop ok for UX. Do we need to design some visual aspect to allow users to know reorder is happening?

**Comment by JordanWSmith15** [comment]
I am fine with a "state of done" if we follow up with the enhancements soon.
