### ISSUE TITLE
[ValueCard] text truncation limited

### ISSUE THREAD

**Issue by JoelArmendariz** [IBM/carbon-addons-iot-react#1027]
### Describe the bug

In ValueCards, if you have a long string it will be truncated and difficult to read without mousing over it.

### Expected behavior

Allow the text to wrap to two lines, rather than only one.

### Additional context

Example:
![Screen Shot 2020-03-20 at 11 57 31 AM](https://user-images.githubusercontent.com/53092833/77187951-42bb3500-6aa3-11ea-817f-a0b3b90c75bd.png)

**Comment by davidicus** [comment]
This was closed by #1042
