### ISSUE TITLE
[ValueCard] Tooltip opens behind other cards

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-addons-iot-react#1059]
### Describe the bug

The tooltip opens behind other tiles using the DashboardGrid.

The likelihood in Heath to have 2 tiles near each other will be great.

### To Reproduce

Just place to value cards with tooltips on top of each other

![image](https://user-images.githubusercontent.com/1056553/78133519-8f303a00-73ec-11ea-911c-bda76abbff6c.png)

**Comment by bjornalm** [comment]
Duplicate or regression of https://github.com/IBM/carbon-addons-iot-react/issues/1040 ?

**Comment by stuckless** [comment]
Duplicate of #1040
