### ISSUE TITLE
[project] potential build regression, d3 peer dep

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#1062]
### Describe the bug

We've identified a regression from https://github.com/IBM/carbon-addons-iot-react/pull/1045/files where consuming apps are potentially unable to build without d3 as a dependency.

<sub>[Internal issue #356](https://github.ibm.com/Watson-IoT/pal-tracking/issues/356)</sub>

### To Reproduce

1. make a new CRA, install this library, configure it to render a simple button, the app doesn't load
```
Failed to compile.
./node_modules/@carbon/charts/components/graphs/bubble.js
Module not found: Can't resolve 'd3-array' in '/Users/taylorjones/Desktop/side-effects-test/node_modules/@carbon/charts/components/graphs'
```

**Comment by tay1orjones** [comment]
Once this is remedied via a PR, I will unpublish `2.61.0`

**Comment by tay1orjones** [comment]
There is no By default, CRA and similar apps will use the new es build files. With this, d3 is no longer included as it is in the UMD build.

We list d3 as a peer dep, and consumers need to have it installed. In the event they do not, they may see the error listed in the initial issue description.

To remedy we'll do the following:
- [ ] Update documentation to instruct folks to install d3
- [ ] Widen the d3 peer dep range to be [what is needed by `@carbon/charts`](https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/package.json#L56) 
- [ ] Remind consumers on internal slack that d3 is a peer dep, and it needs to be installed when updating to 2.61.0
- [ ] Add a step to travis to build a small sample app like this on PR builds. If it fails, we can know in status checks and look for a remedy before introducing things like this.
- [ ] Update create-iot-react-app @davidicus https://github.com/davidicus/create-iot-react-app/issues/15

**Comment by tay1orjones** [comment]
The smoke test was a nice to have, and wasn't able to get it working.

I attempted to create a smoke test script that would spin up a CRA for carbon-addons-iot-react and built it, failing CI builds if the build did not pass. One issue is that `yarn build` doesn't provide proper exit codes, and for `yarn start` the server runs indefinitely. So we'd need to read the console/stdout output as a stream in realtime, and cancel node server if compiled failed or succeeded, and then exit the script with 0 or 1 depending on failure. Reading the stdout/console output and branching conditionals off of it is challenging and I haven't been able to get it to work yet. It just hangs. https://gist.github.ibm.com/taylorjones/9661488c75783f3c8503a90776a8c83a

This could be a manual acceptance process at some point in the future

**Comment by sstone2423** [comment]
Possibly related to #1073 ?
