### ISSUE TITLE
Propose small version of input fields

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#1068]
[From PAL repo](https://github.ibm.com/Watson-IoT/pal-tracking/issues/4) Chris Reckling

> **Description**
> A clear and concise description of what you are requesting and why.
> In IoT, there are very large forms and other input fields (like a filter input on a table). The default carbon field height is 40px. Add in recommended padding and it can take up a lot of space.
> 
> Carbon already has small versions of a search box, button, and probably others at 32px height.
> Search: https://www.carbondesignsystem.com/components/search/style/
> 
> **Name of Pattern or Asset**
> Add the name and a link to the pattern you are referencing in IoT or Carbon
> These all have 40px heights and no small version:
> Text input: https://www.carbondesignsystem.com/components/text-input/style/
> Date and time pickers: https://www.carbondesignsystem.com/components/date-picker/style/
> Dropdowns: https://www.carbondesignsystem.com/components/dropdown/style
> Number Input: https://www.carbondesignsystem.com/components/number-input/style
> Select: https://www.carbondesignsystem.com/components/select/style
> Slider: https://www.carbondesignsystem.com/components/slider/style
> 
> **User outcome**
> Carbon completeness
> 
> **Proposal**
> Do you have a proposed solution? or something you have tried already?
> 32px height options for all of the above.
> 
> **Additional context**
> Add any other context or screenshots about the request here.
> Need to add some screen shot examples..

**Comment by lukefirth** [comment]
Related Carbon issue where they have now enabled this for most inputs at our request 😄 hopefully we can leverage this : https://github.com/carbon-design-system/carbon/issues/5448
