### ISSUE TITLE
[Table]: Need a nice "deleting" state as records are being deleted..

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#107]
Usecase is that the table should give some sort of indication as records are being deleted from a remote server.  And also handle the fact that the record deletion might fail.

**Comment by matsgothe** [comment]
I would like to assign this to Amy.
@scottdickerson can you invite Amy to this repo please.

**Comment by amymillett** [comment]
@scottdickerson I think there's two different situations here... If there's a large amount of records being deleted and it will take awhile for the table to update, I would use the overlay and loading animation provided by Carbon: https://www.carbondesignsystem.com/components/loading/code

<img width="1244" alt="Screen Shot 2019-04-09 at 5 28 47 PM" src="https://user-images.githubusercontent.com/48336859/55839289-f58dbf80-5aec-11e9-9102-6abc89c049c6.png">

Alternatively we could use the same skeleton loading code we already have in place when first fetching the data for the table, but I'm not sure if that makes as much sense.



The other situation is if the deleting happens quickly, without any lag or loading. I know it was mentioned that the transition is a bit jarring and it's definitely hard to tell what happened at first. Maybe an animation to make the transition a little more obvious. I'm thinking something where the rows slide up to fill in the missing space, like this Codepen example: https://codepen.io/Colir/pen/wBWxwL/

**Comment by lukefirth** [comment]
I can think of 3 scenarios here, @scottdickerson could you help specify which we are aiming for here:

1. The entire table is being affected by a long running action (updated underlying query perhaps)
     - Is this covered by what is shown in this story: https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--with-row-expansion-and-actions

2. A single row is in a 'busy' state (such as 'being deleted').
     - Is this covered by what is shown in this story: https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--with-loading-state

3. Multiple/many rows are in a 'busy' state due to a batch action being applied to them (such as bulk delete):
     - The default behaviour I would expect is the same as item 1 in this list, but against all affected rows. Would this meet the need described?

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.
