### ISSUE TITLE
[Data Table] Row action gradient height should be dynamic

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#1085]
Pal [issue](https://github.ibm.com/Watson-IoT/pal-tracking/issues/371)

> It seems that the gradient fade behind the row-action buttons is a fixed height. In data table rows that are taller, the gradient should grow to match it.
> https://pages.github.ibm.com/maximo-app-framework/graphite-testing/pr-GRAPHITE-7359-Llamas-13042020/reference-app/#/tables
> ![Untitled](https://media.github.ibm.com/user/17018/files/1632ca00-7d7e-11ea-8831-82468b60e31f)

Related to #1065

**Comment by davidicus** [comment]
closed by https://github.com/IBM/carbon-addons-iot-react/issues/1065

**Comment by bjornalm** [comment]
@davidicus Is it really correct that this was closed by [#1065](https://github.com/IBM/carbon-addons-iot-react/issues/1065)? They way I understood this issue I think the problem still exists:

![image](https://user-images.githubusercontent.com/5167091/81584823-8f403400-93b3-11ea-80b5-ae11b66b84ba.png)
