### ISSUE TITLE
[PageTitleBar] oneOf PropType error thrown to logs

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#1092]
### Describe the bug

This is a regression recently, now when rendering PageTitleBar, it throws an error to the log:
"Warning: Invalid arguments supplied to oneOf, expected an array, got 2 arguments. A common mistake is to write oneOf(x, y, z) instead of oneOf([x, y, z])."

### To Reproduce

View PageTitleBar and look in the Javascript console in a development build.

Came in in this track:
https://github.com/IBM/carbon-addons-iot-react/commit/cec9c0b5336d5aa39f8a89a239974ad0e4f321ef

**Comment by tay1orjones** [comment]
Resolved in #1124
