### ISSUE TITLE
[PageWizard] ProgressIndicator should allow for optional label

### ISSUE THREAD

**Issue by rawa-resul** [IBM/carbon-addons-iot-react#1094]
### Summary

The ProgressIndicator component allows for an optional label to be displayed by using a secondaryLabel prop which is missing in the PageWizard.

**Additional context**
We need to add the secondaryLabel prop to ProgressIndicator step in PageWizard and also add it in the PageWizard story as an example.

`<ProgressStep ... secondaryLabel={secondaryLabel}/>`

```
<PageWizardStep
    id="step1"
    label="Step 1"
    key="step1"
    secondaryLabel="optional"
```

### Available extra resources

https://react.carbondesignsystem.com/?path=/story/progressindicator--default

<img width="921" alt="Screenshot 2020-04-15 at 18 24 39" src="https://user-images.githubusercontent.com/61942902/79367987-a02d8f00-7f46-11ea-8503-7792bcf59993.png">

**Comment by tay1orjones** [comment]
[Internal Watson-IoT/pal-tracking#389](https://github.ibm.com/Watson-IoT/pal-tracking/issues/389)
