### ISSUE TITLE
[Dashboard] How can I enable the isResizable from RGL?

### ISSUE THREAD

**Issue by jshuadvd** [IBM/carbon-addons-iot-react#1107]
### Summary

If I add the `isResizable={isEditable}` flag to the DashBoardGrid component, I am then able to drag and or resize cards in edit mode, but for whatever reason, this will not work the same on the Dashboard component. 

I can successfully set the flag on the Dashboard and see that it is true, yet the 

```<span class="react-resizable-handle react-resizable-handle-se" style="touch-action: none;"></span>``` 

doesn't even render as it does in the DashboardGridComponent. Any help is appreciated. 

Thank you!

**Comment by jshuadvd** [comment]
Just wanted to update here to make sure it doesn't go stale. Any help is appreciated.

**Comment by jshuadvd** [comment]
Preventing Stale. Can any one please provide insight for this?

**Comment by jshuadvd** [comment]
Preventing Stale.

**Comment by jshuadvd** [comment]
Preventing Stale.

**Comment by tay1orjones** [comment]
Hey @jshuadvd sorry for the delay in responding. We're deprecating `Dashboard` in #1333 in favor of promoting composing the various `*Card` components with `DashboardGrid`. 

This is not only to encourage data/state management at the application layer, but also to standardize functionality provided by the library. This specific issue you outline looks like one of these inconsistent pieces that between using `Dashboard` vs `DashboardGrid` that we're avoiding by standardizing on `DashboardGrid`

I'm going to close this one as it's technically a `wontfix` but please reach out or respond here if you have any additional concerns or questions.

**Comment by jshuadvd** [comment]
Hey @tay1orjones No worries. Thank you for the update! 

Ah, that's bad news :( I understand the idea behind it, but in using for monitoring situations it's invaluable. 

What would be the best way to render the exact version of the dashboard as it is currently via the `DashboardGrid` ? Will there be supporting documentation to reflect? Can you shine some light on how this will all work moving forward?

Thank you!

**Comment by tay1orjones** [comment]
Which parts have you found valuable? We might be able to extract certain pieces into reusable hooks or something to bridge that gap a bit.

We'll update the storybook before the components are removed. DashboardGrid story will be updated with examples of how to compose them together. Right now the DashboardGrid stories just use blank cards:

https://github.com/IBM/carbon-addons-iot-react/blob/8591279a5e5c653c2428770f34087b5ea3c5699e/src/components/Dashboard/DashboardGrid.story.jsx#L12-L46

We'll probably migrate the cards configured in the Dashboard story over to the DashboardGrid story:
https://github.com/IBM/carbon-addons-iot-react/blob/11ffafdcecbbf00cb4b9bca960c1b13b1328e561/src/components/Dashboard/Dashboard.story.jsx#L24-L46

For this specific example above, I think we can simply retool this to be a `ValueCard` component with the associated props and pass that (and the others) into DashboardGrid as children.

I've opened https://github.com/IBM/carbon-addons-iot-react/issues/1403 to track this documentation/migration path work. Please add thoughts here or there, your input is valued as it sounds like you're already using this component.

**Comment by jshuadvd** [comment]
@tay1orjones I will go through this weekend and respond to this in depth. Thank you for the reply!!

**Comment by jshuadvd** [comment]
@tay1orjones my apologies for the delay here. Just getting around to this. 

> Which parts have you found valuable? We might be able to extract certain pieces into reusable hooks or something to bridge that gap a bit.

 _**I love the `cardRenderer` I can configure it to take the existing `cardTypes` as well as create my own. The data reusable `async` data load function is great. I also like the caching mechanism, hooks, and the listener to update or refresh with new data. This is paramount in a real time monitoring situation. Sure, I could write my own and customize a little more, but I don't see this as needing to go away.**_ 

**_As for the `Dashboard` component, most of the aforementioned is applicable . The data fetch handler. The layout, the hooks etc. The Dashboard header is nice as well. I have set it to have an edit mode for the entire dashboard where I can move, add and remove cards at will, which is very nice. I really do find this component as a whole extremely valuable and it is a bit frustrating that both the `Header` & `Dashboard` are being depreciated. If the `DashboardGrid` were to be a newly refreshed/ updated version of this, that would be ideal._**

> We'll update the storybook before the components are removed. DashboardGrid story will be updated with examples of how to compose them together. Right now the DashboardGrid stories just use blank cards:

**_Great. Would love to see this beforehand._**

> We'll probably migrate the cards configured in the Dashboard story over to the DashboardGrid story:
> https://github.com/IBM/carbon-addons-iot-react/blob/11ffafdcecbbf00cb4b9bca960c1b13b1328e561/src/components/Dashboard/Dashboard.story.jsx#L24-L46

**_This would be very helpful and valuable._**

> For this specific example above, I think we can simply retool this to be a `ValueCard` component with the associated props and pass that (and the others) into DashboardGrid as children.

**_Hmm. That makes since. Being able to select or input the "ValueCad" Type would be nice. IE `TimeSeries`, `BarChart`, `LineChart`, `Table`, etc..._** 
 
> I've opened #1403 to track this documentation/migration path work. Please add thoughts here or there, your input is valued as it sounds like you're already using this component.

**_Awesome! Thank you very much for this. Please let me know if you need any further clarification or input. How long do you estimate it will be before this is all completed?_**
