### ISSUE TITLE
[Table] z-index issue with dropdowns in table filters

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#1108]
z-index issue with dropdowns in table filters and the table below. Dropdown goes behind the table and you are unable to see the dropdown options

### Steps to reproduce:
- go to [Table story](https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--stateful-example-with-expansion-and-column-resize)
- click on filters
- click on select menu
- see table over dropdown

![image](https://user-images.githubusercontent.com/1590966/79908568-77dfdd80-83e9-11ea-82f6-48948cffd1ff.png)

**Comment by scottdickerson** [comment]
this doesn't seem to be working for me in the latest builds, you can see it on the carbon-addons-iot-react page: 
https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--stateful-example-with-expansion-maxpages-and-column-resize

**Comment by scottdickerson** [comment]
still having problems with this one

**Comment by mike247** [comment]
Still having this problem
