### ISSUE TITLE
[Donut/gauge card] Values too small, inside donut and trend number

### ISSUE THREAD

**Issue by KarenGski** [IBM/carbon-addons-iot-react#1113]
### Describe the bug

In the Xsmall card, the user can't read the value inside the donut or the trend value.  (We demo'ed to multiple clients and they complained.)

![image](https://user-images.githubusercontent.com/51330315/80016562-462a4d80-84a1-11ea-933d-185a6fb1fc91.png)

![image](https://user-images.githubusercontent.com/51330315/80016523-39a5f500-84a1-11ea-8a06-272b82d0a83e.png)

### To Reproduce

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Expected behavior

**Value inside donut**

- If there are 2 values shown, the primary value should be larger than the secondary value.  
- If there is 1 value shown, it should fill the available space.  
Ex: if 2 characters, it should be 28. If 3, 20.  If 4, 16.  (see image below)

**Trend value**

- Should be size 14

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

Note: disregard the trend arrow being in the wrong place.

![image](https://user-images.githubusercontent.com/51330315/80021235-36623780-84a8-11ea-8ad5-3678891f0a1c.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by davidicus** [comment]
I am removing the bug tag. The original design details did not give any specifics for text sizes. This change is an enhancement.

**Comment by davidicus** [comment]
@KarenGski There is no guidance on the optional text that goes underneath the value ("Good"). And the design above only shows the text changes without this additional text

**Comment by KarenGski** [comment]
@davidicus Stakeholders indicated that they were less concerned with seeing that optional label and more concerned about the primary value being significantly larger, so in Health, we're going to only use the primary value inside the donut.

**Comment by KarenGski** [comment]
Issue in PAL tracking: https://github.ibm.com/Watson-IoT/pal-tracking/issues/381
