### ISSUE TITLE
[table] table header column padding missing

### ISSUE THREAD

**Issue by bjornalm** [IBM/carbon-addons-iot-react#1122]
[Internal Watson-IoT/pal-tracking#387](https://github.ibm.com/Watson-IoT/pal-tracking/issues/387)

### Describe the bug
The padding for the table column header that does not have sort, while the other column headers do have sort, will become misaligned due to the removed padding.
![image](https://user-images.githubusercontent.com/5167091/80348938-ce786c00-886e-11ea-91e0-9655e1016750.png)

### To Reproduce

1. Go to story https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--stateful-example-with-expansion-and-column-resize
2. Look at the date column which is the only one without sorting

### Expected behavior
Columns should be aligned

### Environment/versions:
.

**Comment by bjornalm** [comment]
@davidicus Is this the same as https://github.com/IBM/carbon-addons-iot-react/pull/1153 that was recently fixed?

**Comment by davidicus** [comment]
@bjornalm yes looks like it. The updated story is here https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--stateful-example-with-expansion-maxpages-and-column-resize

and padding is being applied.

**Comment by davidicus** [comment]
closed by the above mentioned PR
