### ISSUE TITLE
What is the QA and regression testing process around components

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-addons-iot-react#114]
Is there a formal QA process for the IoT components?  I know there are Jest tests and code reviews, but, are the dedicated resources to verifying a component does what it should do, and that a component isn't broken?  Are there UI automation tests (selenium?) that are run to verify a component's behaviour hasn't changed?

**Comment by scottdickerson** [comment]
we cover the click behavior in enzyme unit tests that simulate clicks and verifies expected states and automatically run every build.  We also take visual snapshots of components in their different states and snapshot compare them.
