### ISSUE TITLE
DateTime Picker(Experimental): Throwing error with Custom range option in storybook.

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#1145]
[Internal Watson-IoT/pal-tracking#402](https://github.ibm.com/Watson-IoT/pal-tracking/issues/402)

### Describe the bug

DateTime Picker component which is under experimental section in the story book https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-datetime-picker--default throws error.

### To Reproduce

Steps to reproduce the behaviour:

Please refer to the attached screen recording for steps.

![abp](https://user-images.githubusercontent.com/22093326/81043594-24cd5680-8ed0-11ea-9de6-9d17e03f6c75.gif)

### Environment/versions:

- OS: MacOS, Windows
- Browser: firefox, chrome
- `carbon-addons-iot-react` version: v2.75.2

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

We need this component for our June 2020 release.

**Comment by tay1orjones** [comment]
Thanks for opening an issue. I briefly took a look - seems that we need to add some null checks to the `parseValue` function. There might be a broader swath of logic we need to improve though as well.

https://github.com/IBM/carbon-addons-iot-react/blob/3e50b7ab7555ce042a53f6bdbd9948c3ed683827/src/components/DateTimePicker/DateTimePicker.jsx#L323-L386

**Comment by kalyanixraut** [comment]
@tay1orjones , Thanks you for looking into it. As we are chasing a release scheduled for June, so can you please provide an ETA for the fix.

**Comment by davidicus** [comment]
closed by https://github.com/IBM/carbon-addons-iot-react/pull/1162
