### ISSUE TITLE
[Deps] Migrate off carbon-icons

### ISSUE THREAD

**Issue by sstone2423** [IBM/carbon-addons-iot-react#1148]
[Internal Watson-IoT/pal-tracking#401](https://github.ibm.com/Watson-IoT/pal-tracking/issues/401)

### Describe the bug

We're using the legacy `carbon-icons` library in some places of our component library. The library hasn't been updated in 2 years and has open security vulnerabilities.

See https://github.com/carbon-design-system/carbon-icons/issues/95 for more info

### To Reproduce

1. Search for usage of `carbon-icons` in our repo
2. See multiple locations we're using the legacy library

### Expected behavior

We should only be using `@carbon/icons` or `@carbon/icons-react`

**Comment by tay1orjones** [comment]
I'm surprised we don't have an issue for this yet - I know it's been discussed for quite a while.

It would be great to remove it as a dep. It's probably worth noting that Carbon [intends to support `carbon-icons` through v11](https://github.com/carbon-design-system/carbon/blob/v10.10.3/packages/react/src/components/Icon/migrate-to-7.x.md).
