### ISSUE TITLE
[StatefulTable] wrapCellText prop not working

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#1156]
[Internal Watson-IoT/pal-tracking#410](https://github.ibm.com/Watson-IoT/pal-tracking/issues/410)

### Describe the bug

In Stateful table the column titles are getting truncated. Tried setting the wrapCellText prop with 'always'/'never'/'auto' but still column titles are truncated. 
Scenario 1: 
 When prop is set to 'always ' as in below code or prop is not referred under options and stickyHeader=true.

options={{
              hasFilter: false,
              hasSearch: false,
              hasPagination: true,
              hasRowActions: false,
              hasColumnSelection: false,
              wrapCellText: 'never'
            }}

We expect the longer cell data to wrap whereas it gets truncated. I find that stickyHeader overwrites the css.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/22093326/81152124-477a7080-8f9f-11ea-8480-d6d31d970cf1.png">

 Scenario 2: 
 When prop is set to 'auto' or 'never' column cell data will still get truncated with ellipsis. It works only when hasResize prop also set to true to make the column cell data display with ellipsis(as in storybook). 

But again if I have stickyHeader set to true table is distorted with above settings.

I am using v2.75.2.

### Specific timeline issues / requests

We have a release in June 2020 and need this to be fixed before to that.

**Comment by bjornalm** [comment]
There are a lot of things that currently do not work or render properly when stickyHeader is active:

- Filters
- Row selection
- Row expansion
- Row selection
- Column resize
- Column reordering

**Comment by bjornalm** [comment]
### wrappCellText + stickyHeader
Our wrappCellText truncation only works if the columns have a fixed width or are resizable (in which case they will also have a width). Wrapping should normally always work, but in this case the forced truncation comes from the stickyHeader implementation that adds its own truncate CSS. The reason for that is probably that stickyHeader requires a fixed height on the table head row, which is set to 3rem by default. 

**An application workaround**
The application can override the sticky stickyHeader css 
```
.bx--data-table--sticky-header .bx--table-header-label span {
  white-space: normal;
}

// Adjust to allow enough height for your wrapped titles
.bx--data-table_inner-container {
  padding-top: 4rem;
}
.bx--data-table--sticky-header th {
  height: 4rem;
}
```

**An addons-iot-library solution**
Handle the `white-space` css conditionally depending on the wrapCellText Value and make sure that truncation also works properly which is not the case with stickyHeader. The application would have to handle the height of the table header row or we could possibly update that height dynamically via javascript.

**Comment by davidicus** [comment]
@bjornalm Due to the experimental nature of the sticky header feature we are waiting to see the design strategy of @kalyanixraut team before we decide on a course of action.

**Comment by davidicus** [comment]
Closing this as sticky header is not supported and the product team has decided against using this feature.
