### ISSUE TITLE
[ImageCard] provide default hotspot content

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#1172]
Adds a default hotspot content to addons, previously all consumers had to build their own custom tooltip content

- Allows the ImageCard to show hotspots based on a standard Content panel
- This new Content panel supports localized numeric metric values
- Continue to support passing in custom hotspot content elements

**Comment by scottdickerson** [comment]
this is supported now

**Comment by scottdickerson** [comment]
https://github.com/IBM/carbon-addons-iot-react/pull/1144
