### ISSUE TITLE
[ui-shell] Updating carbon-addons-iot-react version to 2.76.0 causes ui-shel sidenav to change background color

### ISSUE THREAD

**Issue by aj995** [IBM/carbon-addons-iot-react#1195]
### Describe the bug

Hi all,

we needed to upgrade the version of `carbon-addons-iot-react` to 2.76.0 for `DateTimePicker` support. With that change our `SideNav` component changed the background-color of active links to `#e5e5e5`

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: v2.76.0

### Additional context

I noticed that the change seems to come from this file:
`carbon-components/scss/components/ui-shell/_side-nav.scss`.

On v2.76.0 the file looks like this:
<img width="376" alt="Screenshot 2020-05-18 at 10 40 33" src="https://user-images.githubusercontent.com/38671044/82194454-239c2080-98f7-11ea-9750-405d935e5d3f.png">

A working previous version does not have the `background-color` attribute:
<img width="381" alt="Screenshot 2020-05-18 at 10 45 53" src="https://user-images.githubusercontent.com/38671044/82194526-3d3d6800-98f7-11ea-9bad-1e01b6f382a0.png">

Does someone know if this is an intended behaviour?

**Comment by scottdickerson** [comment]
I'm getting the same behavior I think it's carbon-components themselves setting this and overriding the color we were intending to set.  @lukefirth which color do we want?

**Comment by scottdickerson** [comment]
Strangely it's not broken in the storybook, only if we import it into our own project are the carbon-component overriding the carbon-addons-iot-react version

**Comment by scottdickerson** [comment]
![image](https://user-images.githubusercontent.com/6663002/82483327-d3ab8e00-9a9d-11ea-84f6-e36eb877eb3e.png)

**Comment by lukefirth** [comment]
@creckling recently looked into this for other reasons, I'm pretty sure I know the answer but I'd like him to report his findings just to be on the safe side 😄

**Comment by scottdickerson** [comment]
looks like we decided to go with a black themed side nav in addons, but the carbon-components one is white themed, which is causing these kind of conflicts @lukefirth .  I'll just temporarily set back to our original color.  Ideally we'd resolve this discrepancy between the SideNav inside carbon-components and the one inside carbon-addons-iot-react

**Comment by lukefirth** [comment]
Its a purposeful choice - the Carbon side nav is indeed white, but for many reasons we need to keep black (partially as part of EAM support down the road, who have need for a dark one, and partially down to a declaration by the visual bodies of our org).

For note, Carbon know its a problem that their nav (in sketch and in code) doesn't allow theming and flexibility like this, but its all wrapped in a longer term fix they have coming to allow the theming for it. Hopefully we'll be able to leverage that when it comes, rather than get broken by it ha.
