### ISSUE TITLE
[ValueCard] data state - error description runs off the page

### ISSUE THREAD

**Issue by RogerRosado** [IBM/carbon-addons-iot-react#1198]
### Describe the bug
On ValueCard for the data and error state, when you click on the description symbol, the information runs off the page

![image](https://user-images.githubusercontent.com/56408920/82232494-b5f2f300-98fc-11ea-9dda-0dbed8475ccf.png)

Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-valuecard--data-state-error-small.

Snapshot below shows issue:

![image](https://user-images.githubusercontent.com/56408920/82232678-ee92cc80-98fc-11ea-92f5-b58d00e2476b.png)

**Comment by tay1orjones** [comment]
Thanks for reporting this. A think decent stopgap could be to left align these tooltips by default and potentially provide the ability to override the tooltip alignment.
