### ISSUE TITLE
[Table] Expand/Collapse icon can we allow the checkbox to the far left of the twisty.  

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#122]

**Comment by matsgothe** [comment]
Carbon, the Carbon team and Amy to define this visual style.
Assigning to Amy for clarification. 
I think the design is already set in the visual UX library.

@amymillett please clarify and close.

**Comment by amymillett** [comment]
@scottdickerson Just to clarify, we're talking about moving from something like this:<img width="237" alt="Screen Shot 2019-04-08 at 8 26 36 AM" src="https://user-images.githubusercontent.com/48336859/55727685-1fa18d80-59d8-11e9-81a0-64187df0727f.png">

To this?
<img width="169" alt="Screen Shot 2019-04-08 at 8 27 00 AM" src="https://user-images.githubusercontent.com/48336859/55727688-229c7e00-59d8-11e9-805b-8da2b3bd3f30.png">

I don't think I would recommend switching the position of the checkbox and the twisty. I've never seen that pattern before and the current positioning is outlined by Carbon. It might also be a little confusing to a user.

**Comment by scottdickerson** [comment]
when we have nested rows the checkboxes get stair steppy @stuckless mentioned that perhaps the checkboxes should be vertically aligned.   The checkboxes will behave differently based on the level of the hierarchy that they're within.  The child checkboxes will actually impact the parent checkbox according to the spec.
