### ISSUE TITLE
[DateTime Picker] Default value passed in props not being set

### ISSUE THREAD

**Issue by navjeets** [IBM/carbon-addons-iot-react#1220]
https://github.ibm.com/Watson-IoT/pal-tracking/issues/429
### Describe the bug
The default value passed in props doesn't get set. As a result the DateTime Picker box stays blank. The object set to defaultValue props is the following:
```
{
    kind: 'PRESET',
    preset: {
        label: '12 months',
        offset: 525600
    }
}
```

The issue is in parseDefaultValue() function. In the following code parsableValue is set to the object passed in defaultValue prop. However, its looking for offset attribute directly under the passed object.
```
if (parsableValue.hasOwnProperty('offset')) {
    // preset
    resetAbsoluteValue();
    resetRelativeValue();
    setCustomRangeKind(currentCustomRangeKind);
    onPresetClick(parsableValue);
}

```
Changing the above code to the following fixed the issue
```
if (parsableValue.kind === PICKER_KINDS.PRESET) {
    // preset
    resetAbsoluteValue();
    resetRelativeValue();
    setCustomRangeKind(PICKER_KINDS.RELATIVE);
    onPresetClick(parsableValue.preset);
}
```

Making the above change would also require a change in `onApplyClick()` where instead of `setLastAppliedValue(value.preset)` we will need to call `setLastAppliedValue(value)`

### To Reproduce
Create a new DateTime Picker component and pass a defaultValue prop.

**Comment by davidicus** [comment]
Hi @navjeets. Thank you for submitting this bug. We have decided to refactor the proptype declaration to match the way the code was using the `defaultValue` prop. This way users will just have to pass a value in the correct format for each value type.

for preset
```
{
    label: '12 months',
    offset: 525600
}
```

for relative
```
{
    llastNumber: 20,
    lastInterval: 'MINUTES',
    relativeToWhen: 'YESTERDAY',
    relativeToTime: '13:30',
}
```

for absolute
```
{
    startDate: '04/01/2020',
    startTime: '12:34',
    endDate: '04/06/2020',
    endTime: '10:49',
}
```
