### ISSUE TITLE
[DateTimePicker] add prop to hide tooltips

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#1232]
### Summary

From @navjeets [Internal Watson-IoT/pal-tracking#430](https://github.ibm.com/Watson-IoT/pal-tracking/issues/430)

> **Description**
> DateTime Picker component being used in Maximo Predict widget has a custom behavior defined on preset values. Instead of 12 months being defined as last 12 months it is set to 8 months in past and 4 months in future.
> This works fine but the tooltip shows the date range from 8 months in past to today. This is misleading for the user as it doesn't reflect the actual range.
> Having an option to disable the tooltip would help avoid any confusion.
> 
> **Name of Pattern or Asset**
> DateTime Picker
> 
> **User outcome**
> Allows to hide tooltip while customizing the preset values behavior.
> 
> **Proposal**
> Provide a property on the DateTime Picker that allows the user to hide the tooltip.

**Comment by navjeets** [comment]
Created new issue https://github.com/IBM/carbon-addons-iot-react/issues/1251 to replace this issue.

Closing this issue.
