### ISSUE TITLE
[StatefulTable] Using stickyHeader property in statefultable brings issue with style

### ISSUE THREAD

**Issue by xwgao** [IBM/carbon-addons-iot-react#1241]
### Describe the bug

After setting the `stickyHeader` property to be true in StatefulTable, it brings some issue with style:
1. The cell width becomes very strange in each row.
2. The filter header can not be shown fully

### To Reproduce
As you can see on the screenshot below, the row width becomes `100%` for each row cell, and the filter on header can not be shown fully.
![图片](https://user-images.githubusercontent.com/54341035/83213738-7dbda100-a195-11ea-8d02-508366c768b7.png)

### Expected behavior
The StatefulTable style is normal as without setting `stickyHeader` property to be true as below:

![图片](https://user-images.githubusercontent.com/54341035/83214109-5f0bda00-a196-11ea-81f3-ad8df659c618.png)

**Comment by davidicus** [comment]
Thank you for opening this bug. Unfortunately, the sticky header feature is not currently supported. This feature is still experimental in the base Carbon table and as such we have not tried to make it compatible with our extended features. Once their implementation is finalized we can begin the work to support.
