### ISSUE TITLE
[Table]: alignment is off on the first column header for certain table styles

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#1246]
![image](https://user-images.githubusercontent.com/6663002/83334151-23dadb00-a26a-11ea-82a8-57fbc3f081f4.png)

https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--filtered-sorted-paginated-table-with-asynchronous-data-source

I think it has something to do with no selection/expansion and a sortable column header

**Comment by tay1orjones** [comment]
I believe this has been fixed - please reopen if it still is an issue
