### ISSUE TITLE
[ComboBox] with multi-select

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#1264]
### Summary

This provides an input mechanism for multiple values both new, and/or from an existing suggested list. This also allows users to see all of the selections on the face of the component, rather than hidden with only a count like the stock carbon multi-select dropdowns.

**Additional context**
From the internal issue [pal-tracking#155](https://github.ibm.com/Watson-IoT/pal-tracking/issues/155):

> This looks like a standard text input at first glance. However when a user begins to interact with the input, a series of autocomplete suggestions will be provided. The user can select one of these items or write in a new value. Once an item is selected (or new value supplied and... assume a comma or loss of focus is given) the value will appear as a closable tag [#147](https://github.ibm.com/Watson-IoT/pal-tracking/issues/147) in the input, and the user can dismiss it, or write more.
> 
> As more values are added, the input may grow in height to allow wrapping, and at responsive levels, add a mega tag of "+X more" which will represent the hidden other values.
> 
> ![image](https://media.github.ibm.com/user/684/files/1c147500-1bfd-11ea-950b-51e9524d25ae)

There is an associated Carbon PR https://github.com/carbon-design-system/carbon/pull/6015 to enable us to implement this feature.

**Comment by davidicus** [comment]
Opened up a [PR](https://github.com/carbon-design-system/carbon/issues/6001) to allow bubbling for this feature.
