### ISSUE TITLE
[Table] Missing the active state of icon button

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#1279]
From [Internal Watson-IoT/pal-tracking#399](https://github.ibm.com/Watson-IoT/pal-tracking/issues/399)

**Description**
The icon buttons for filter and column edit do not have active state indicated.  It's unclear how to dismiss the column filters when enabled. 

![image](https://media.github.ibm.com/user/627/files/3e089700-8ba0-11ea-80b4-b9085a8f05a0)

**Name of Pattern or Asset**
Data Table 

**User outcome**
Is this related to a user outcome you are working on?

**Proposal**
Use carbon's active state for icon-only button. 

<img width="929" alt="image" src="https://media.github.ibm.com/user/627/files/e0ef4700-8ef9-11ea-88d5-dec48662e5a5">

**Additional context**
Add any other context or screenshots about the request here.

**Comment by tay1orjones** [comment]
@scottdickerson are you still intending to deliver this alongside #1227 ?

**Comment by scottdickerson** [comment]
this is fixed now
