### ISSUE TITLE
[Table]: Row Actions  Need some indication that the row action is long running ( possibly undo/cancel)

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#128]

**Comment by matsgothe** [comment]
This design described the general behavior of the table component when a user selects and runs a row action. This behavior should be alike the Carbon standard behavior.

**Flow**

1.  Mouse of a row. Action buttons show.
2. The user selects an action
3. [Default] The action should perform instantly and runs synchronously. 
3.1 The action reports running activity using a spinner on the row
3.2 The action reports progress using a progress slider on the row
3.3. The action runs asynchronously in the background. The separate process is responsible for reporting progress using the common progress indicator on a separate dialog, independent of the table. The dialog may be dragged aside and user to track completion while the user continues with other table operations. This behavior is also, and even more, applicable to bulk actions where there may be an indeterminable progress across multiple rows.
4. The table refreshes with any updates

**Design considerations**

- Show the any progress indicator (spinner / progress bar) at the far left side on the row.
- Alternatively, overlay / replace the action controls on the row with the progress indicator control
- This design is also related to the vertical scrolling and the design decision on how to show actions (and progress controls) when the rows are wider than the screen width. And any row controls fall off the visible right side.

**Comment by matsgothe** [comment]
Assigning to Amy for visual design recommendation.

**Comment by amymillett** [comment]
@scottdickerson I guess one of my main questions with this is: If a row action is long-running, can the user still go about their business clicking on things and inspecting other rows, or would there need to be a loading state/indicator over the whole table?

**Comment by scottdickerson** [comment]
Imagine the usecase where you're activating a row or changing the status of a row.  Wouldn't be covered.  Do you lock the row in that status?    (Delete is a special case)

**Comment by scottdickerson** [comment]
@amymillett any idea here?  I'll need some kind of decision about the row locking and visual design.  I think in my cases we will need to prevent further actions on the row, but can allow selection and other interactions with the table to proceed.  I'd be interested to hear from @bryancboyd whether he also thinks that only the row actions should be locked, not the whole table

**Comment by scottdickerson** [comment]
@lukefirth here are the UX issues I mentioned in the demo

**Comment by amymillett** [comment]
@scottdickerson @lukefirth What do you guys think about this? The row action icon (in this example it's the drill-in icon) would change into a loading icon, and would return an error if the action couldn't be completed.

<img width="1247" alt="Screen Shot 2019-04-26 at 11 59 01 AM" src="https://user-images.githubusercontent.com/48336859/56823927-cc726c00-681a-11e9-86a9-f15966e15b47.png">
<img width="1248" alt="Screen Shot 2019-04-26 at 11 59 10 AM" src="https://user-images.githubusercontent.com/48336859/56823929-cf6d5c80-681a-11e9-8652-2091b9e963a0.png">
<img width="1248" alt="Screen Shot 2019-04-26 at 12 03 12 PM" src="https://user-images.githubusercontent.com/48336859/56824160-4dc9fe80-681b-11e9-84d2-13dd9565313a.png">

**Comment by scottdickerson** [comment]
@amymillett do you mind if I turn off the other actions when an action is in progress or errored?  In our case we wouldn't want to allow triggering multiple actions on rows.  So basically hide the other actions when an action is in progress

**Comment by amymillett** [comment]
@scottdickerson Yep, that makes sense to me.
