### ISSUE TITLE
[Table] Column width is not applied when the columns are changed

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#1284]
Migrated from [internal](https://github.ibm.com/Watson-IoT/pal-tracking/issues/445)

> I trying change the table columns dynamically but i'm facing some issues with columns width.
> 
> The component set the column width automatically what is good but, when i changed the columns the table is not rendered correctly.
> 
> When i change the columns the new width is ignored.
> 
> **### initial:**
> 
> columns={[
> {
> filter: {
> placeholderText: 'enter a string'
> },
> id: 'string',
> name: 'String'
> },
> {
> filter: {
> placeholderText: 'enter a date'
> },
> id: 'date',
> name: 'Date'
> },
> {
> id: 'secretField',
> name: 'Secret Information'
> }
> ]}
> 
> **### change 1:**
> 
> columns={[
> {
> filter: {
> placeholderText: 'enter a string'
> },
> id: 'string',
> name: 'String',
> width: '300px'
> },
> {
> filter: {
> placeholderText: 'enter a date'
> },
> id: 'date',
> name: 'Date',
> width: '50px'
> },
> {
> id: 'secretField',
> name: 'Secret Information',
> width: '150px'
> }
> ]}

**Comment by tay1orjones** [comment]
This was directly fixed in https://github.com/IBM/carbon-addons-iot-react/pull/1229

Additionally, #1253 was also needed for this team to update to the new version that was published from #1229
