### ISSUE TITLE
[TimeSeriesCard] When passed no time information use GMT time

### ISSUE THREAD

**Issue by troyibm** [IBM/carbon-addons-iot-react#1287]
We are using the TimeSeriesCard to show count-of-activity per day, so there is no time info in our data.  Maybe we should be using a different component (DateSeriesCard??), but we would like an option to tell the graph that the data has no time info so use GMT time for all timespan data.

**Comment by scottdickerson** [comment]
unfortunately all dates in javascript have time, but I can give you a prop called 'showTimeInGMT' that if you set true will not localize the time part of the date.
