### ISSUE TITLE
[Table]: Row Actions If the row action fails, how do we communicate that?

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#129]

**Comment by matsgothe** [comment]
This design should describe the behavior of the table component and recommendation on common behavior for client usage of the table.

Generally, the table is agnostic to the actions that a client application may put on rows. Likewise to the behavior of the IoT resource that is represented by the row, and any children of the row. Hence only a general recommendation  and default behavior can be provided.

Action code running as a row or bulk action should report errors using the standard UX warning or error dialogs. Such a dialog may report the outcome of an action success, log, warning, error.

An action code may also choose to set a state indicator on a row. Hovering over the row may provide a quick information summary of the state.

One can note that the visual allocation f space for a row state indicator may be generalized to cover other similar row state indicators, e.g. Error (this case), Action progress, Lazy loading progress.
https://github.com/IBM/carbon-addons-iot-react/issues/126
https://github.com/IBM/carbon-addons-iot-react/issues/128

**Comment by matsgothe** [comment]
Assigning to Amy for a visual design.

**Comment by scottdickerson** [comment]
@amymillett any update?

**Comment by scottdickerson** [comment]
If we're able to implement this in a way that would also address the left panel fixed this would be great!  Perhaps a column prop that fixed to left or right
