### ISSUE TITLE
[Table]: Run user testing on the table 

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#131]

**Comment by matsgothe** [comment]
This user test validates the usability of the new common table component.

Thee following tests are prioritized test cases
- Show hidden columns
- Change the order of columns
- Sort rows by column data
- Filter rows by column data
- Create a new row
- View row details
- Edit row details

Test script: https://ibm.ent.box.com/notes/431560646973

**Comment by scottdickerson** [comment]
@bryancboyd need some guidance here on when the IoT Platform would pickup the actual shared table into production with an experimental switch.

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.
