### ISSUE TITLE
[Card / Dashboard] add error boundary around cards in dashboard

### ISSUE THREAD

**Issue by sstone2423** [IBM/carbon-addons-iot-react#1318]
### Summary

Currently, there is no error boundary around cards in dashboards, meaning if one card errors out, the entire dashboard goes down. I'd propose that we wrap each card in an error boundary so that the rest of the dashboard will still be functional, while that one card will have an error state.

This case mainly comes up when users are setting up their dashboards and trying to get the JSON configuration correct.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

No specific timeline

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

Monitor team can add this

**Comment by tay1orjones** [comment]
Great idea! What do you think the fallback UI should be?

**Comment by sstone2423** [comment]
The regular card's error state should work I think. But this may be fixed by moving Dashboard and CardRenderer to Monitor. See #1332

**Comment by sstone2423** [comment]
Closing this and moving to Monitor's issue board
