### ISSUE TITLE
[repo] separate build script from install script

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#1328]
### Summary

Currently our full production build is being ran on `yarn install`. This is unnecessary for developing locally on the codebase. We should refactor our build scripts to not run on `yarn install`

**Additional context**
`yarn install` automatically calls `yarn prepare` which we have configured to run our `yarn build`.

`semantic-release` relies on this as part of the publishing process. We'll need to remove the `yarn prepare` script, and reconfigure Travis to specifically invoke `yarn build`. We'll want a test build ran on pull request builds to report build fail/success in pull request status checks. Additionally, we'll need to ensure that `yarn build` is ran in Travis on `master` builds before we run `semantic-release` to publish the package.

This came from [a slack conversation](https://ibm-ai-apps.slack.com/archives/CMYHKU8HZ/p1592500364450500) with @sstone2423 

### Specific timeline issues / requests

This is just a nice-to-have improvement

### Available extra resources

Anyone can pick this up, but we'll want a thorough code review as it effects the production build/deploy process.

**Comment by sstone2423** [comment]
For some reason the command randomly re-entered my package.json when I pulled from master just now. I know you had the same issue in a recent PR as well @tay1orjones . Very weird
