### ISSUE TITLE
[Table]: Update the column selection icon

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#134]

**Comment by matsgothe** [comment]
The column selection icon in the table component is not the one designated by Carbon
Use this icon
![Column](https://user-images.githubusercontent.com/23455181/55387492-d1047700-5531-11e9-89a8-071fc67d22ed.png)

**Comment by matsgothe** [comment]
@amymillett please confirm.

**Comment by scottdickerson** [comment]
@matsgothe I need this in svg format so I can change the colors on focus and selection, can you reattach it or ping it to me directly?

**Comment by matsgothe** [comment]
@amymillett can you please help Scott

**Comment by matsgothe** [comment]
[Column.svg.zip](https://github.com/IBM/carbon-addons-iot-react/files/3111815/Column.svg.zip)
