### ISSUE TITLE
[Table]: Column width resizing

### ISSUE THREAD

**Issue by matsgothe** [IBM/carbon-addons-iot-react#135]
The table competent shall support the user gesture to resize the column width.
By default, a column has a default width set by the tool based on the column title length, and secondarily by cell content. 

Users may optionally set a fixed column width. The set width is not persisted across loading the page / table. In future revisions of the component, users may save a table column configuration as a query filter including the column selections, colum order, column filters, and sort order.

To change the column width, when hovering the space between columns in the column header the cursor changes to a resize pointer. Pressing the mouse button the user drags a splitter and the column responds by reactivity change the column width. Releasing the mouse button will change the width of the column.

Design pattern details in this file. https://ibm.box.com/s/j3lwxgqkiagnjtzt86hn82pao46rab5d

<sub>[Internal tracking issue #45](https://github.ibm.com/Watson-IoT/pal-tracking/issues/45)</sub>

Context from jira item:
As a user, I can click on the table column header and drag/release to determine the width of any column

![image](https://user-images.githubusercontent.com/1590966/73098719-f515b800-3eb7-11ea-8bfc-7fa14c1583d0.png)

**Comment by matsgothe** [comment]
@scottdickerson please move to backlog for Q2

**Comment by lukefirth** [comment]
@JordanWSmith15 can you post updates RE your column resizing plans here? (or if the jira integration exists/permits, link comment a link here to where it is tracked?)

**Comment by JordanWSmith15** [comment]
Certainly. The story in Jira is https://jsw.ibm.com/browse/GRAPHITE-3715
![Screen Shot 2019-10-31 at 8 25 40 AM](https://user-images.githubusercontent.com/21066152/67946596-0badbb00-fbb8-11e9-8f05-f6cdc7ee44bf.png)

**Comment by davidicus** [comment]
@JordanWSmith15 I am unable to see the jira link above. Do I still need to be added?

**Comment by tay1orjones** [comment]
Some thoughts on the implementation:

Column size can be set via css targeting the appropriate `<th>`.

This will require a mouseup/down/move touch start/move/end handler on each `<th>`. [We can support mouse and touch events at the same time](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent). The initial width should be gathered, and then modified based on the values during move/end event.

I don't think there's a clear way to set the width on the element via Sass. It would require a custom property being set from javascript and classes stubbed out for each column, so the width could be set for individual `<th>`s. [We're also moving off of StyledComponents](https://github.com/IBM/carbon-addons-iot-react/blob/master/.github/CONTRIBUTING.MD#styling-new-components), so the width should be set via an inline style tag `style={{width: x;}}`.

One case that may require some additional logic is if the size is dragged too small to fit content, or too large for the page.

**Comment by sunilkotiyaibm** [comment]
@tay1orjones @davidicus https://gist.github.com/sunilkotiyaibm/64f5b5a71f516e81fa86b393a8ed53a8
 gist  is created for your initial review at high level, So there are two files modified TableHead.jsx and _data-table.scss. It is working (left/right dragging) our local environment. 
As of we are not able to commit the code because of unit cases/coverage, we will work on this once our initial approach is ok. 
Please provide your feed back.  
Including @psdixit @JordanWSmith15

**Comment by tay1orjones** [comment]
There is an issue open on Carbon for this - may be an opportunity to contribute this enhancement directly to them. https://github.com/carbon-design-system/carbon/issues/4751

**Comment by tay1orjones** [comment]
I've issued[ a PR to Carbon to forward refs from TableHeader.](https://github.com/carbon-design-system/carbon/pull/4877)

In the meantime, we can reimplement/copy TableHeader from my carbon PR and use that for the time being. This way we're not blocked and can work through the rest of the implementation.

Depending on the timeline and our ability to update to the new version that carbon will release with my change, we may wait to merge the implementation of column resizing until we've updated. 

Another (likely better) option would be to merge the implementation of column resizing with the reimplemented/copied TableHeader and create a new issue to refactor (delete the reimplemented one) once we've updated the Carbon version.

**Comment by matsgothe** [comment]
@tay1orjones question on the resizing. is there a way for the client of this component to get the new sizing so that can be persisted and restored when the page is refreshed or the table is opened a second time after the column size has been changed.

**Comment by tay1orjones** [comment]
We can provide a callback that is called when a column is resized. This should enable the ability to save the column widths. We'll also need to extend the columns prop to accept a width for the initial state of the table. This will prevent the table columns "jumping" from default width to saved width after initial render.

We should provide an example in the storybook of how to store column widths in localstorage using [the `useLocalStorage` hook](https://github.com/rehooks/local-storage)

**Comment by tay1orjones** [comment]
Resolved via #867 - auto-close didn't pull through due to minor syntax error on the PR body.
