### ISSUE TITLE
[Table]: Reordering of columns using drag and drop

### ISSUE THREAD

**Issue by matsgothe** [IBM/carbon-addons-iot-react#136]
The common UX table component shall support reordering of columns using drag and drop.

This capability is a secondary use-case to the selection and order use-cases implemented for the table component (as is and to be)

For columns visible on the screen, a user may mouse-over, mouse-down and grab a column. Then drag the column to a space between other columns and drop by releasing the mouse button. The table shall be responsive and visually display the new column inserts during drag, in a similar    way as is implemented in the primary column reorder UX.

Design pattern details in this file. https://ibm.box.com/s/j3lwxgqkiagnjtzt86hn82pao46rab5d

**Comment by matsgothe** [comment]
@scottdickerson please assign to Q2 backlog.

**Comment by davidicus** [comment]
@matsgothe what is missing from the current implementation? Is this in addition?

**Comment by matsgothe** [comment]
There are multiple use-cases defined in the IoT EDS for table columns
- Drag and drop ordering
- Change column width
- Lock column width

On this issue there is a primary and secondary use-case.
The current implementation covers the primary case of selecting the column editor and then reordering the columns
The secondary use-case is no just drag and drop the column, without the pre-condition of opening the column editor. This is the use-case defined in the EDS. 
https://ibm.invisionapp.com/share/8FNYY6HH4AN#/screens/319100283

**Comment by tay1orjones** [comment]
I think this has been fully resolved via the initial drag and drop functionality, #867 table column resizing, and the column min width ("lockable" via overriding) provided in #1034, and other column classnames available to override in application code.

@lukefirth @creckling maybe you have some additional info?

**Comment by lukefirth** [comment]
Looks good to me. The 'locking' _could_ be referring to the ability to 'freeze' columns when used in horizontally scrolling tables. However, that should probably be kept as a separate issue to this one "reordering columns using drag and drop' which from my understanding is complete using the current IoT method, but may at some lower priority date, be changed over to use a method similar to the original EDS.

**Comment by tay1orjones** [comment]
@lukefirth I've opened #1061 to contain the static column width item.

This is considered delivered - if the original EDS method or similar becomes a formal requirement we can open a new issue with the proper design spec and architecture discussion.
