### ISSUE TITLE
[ChartCards] truncate legend in cases there are many labels

### ISSUE THREAD

**Issue by alronz** [IBM/carbon-addons-iot-react#1364]
### Summary

This is a feature enhancement idea.  With many labels in the legend, the charts gets so small depending on the card size as shown in the screenshot below.  It would be nice if the legend can show the first few labels and hide the rest. The hidden labels can be shown in a drop down list or any other design that makes sense.  

![Annotation 2020-07-06 140030](https://user-images.githubusercontent.com/7453308/86591799-8ecab080-bf92-11ea-8eb4-013f9edc8bb4.png)

**Comment by tay1orjones** [comment]
Yes, this would be a great enhancement. The charts and legends come directly from [`@carbon/charts`](https://github.com/carbon-design-system/carbon-charts). We don't own that code, so the change would need to be made there. They have an open issue to address this https://github.com/carbon-design-system/carbon-charts/issues/287. 

This is the specific design guidance from the issue that would meet this need:

![image](https://user-images.githubusercontent.com/3360588/86821236-c21f4500-c04f-11ea-912f-38b7c846e3f6.png)

I'm going to close this as a `wontfix` for now and update their issue noting this request.

**Comment by theiliad** [comment]
again truncations have been implemented, the rest of the functionalities such as scrolling legends haven't been implemented. Feel free to contribute those pieces if you have the bandwidth

Legend truncation demo: https://carbon-design-system.github.io/carbon-charts/?path=/story/line--line-discrete-with-truncated-labels
