### ISSUE TITLE
[PageHero]: title is misaligned vertically

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#157]
Area title for Explore is misaligned. #1483 from our internal repo

![image](https://user-images.githubusercontent.com/6663002/55736439-e887a800-59e8-11e9-84e6-50b224f188fa.png)

**Comment by scottdickerson** [comment]
@lukefirth

**Comment by scottdickerson** [comment]
also this bug: 

![image](https://user-images.githubusercontent.com/6663002/55740083-fbea4180-59ef-11e9-884e-140d3fa74a9c.png)

**Comment by lukefirth** [comment]
@scottdickerson Any chance we can have this addressed before the 30th Apr? It is affecting the AS main explore page people see when logging in quite noticeably - hard for demos!
