### ISSUE TITLE
[Wizard]: should warn the user if they try and navigate away while in the flow

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#170]
If a wizard is showing, we should warn the user if they try to navigate away (for example if they've accidentally hit the back button)

**Comment by scottdickerson** [comment]
@lukefirth has some ideas on how to manage this.

**Comment by matsgothe** [comment]
This is the dialog in the in-line wizard. 
![image](https://user-images.githubusercontent.com/23455181/56141756-baccd100-5f9d-11e9-80f6-5b2fb713fa36.png)

**Comment by matsgothe** [comment]
@amymillett, @lukefirth something similar for the floating wizard.

**Comment by lukefirth** [comment]
@matsgothe Correct, although should be updated to the newer styles @amymillett has worked on.

Logic definition incoming after the call.

**Comment by lukefirth** [comment]
When to, and when not to supply confirmation dialogs of this kind:

You should whenever any of the below are true:
- 1 The user has initiated a wizard, and has changed or supplied information anywhere within it. Aka- they have work that could be lost by the early exit. 
- 2 By opening the dialog, an action has been initiated that would be interrupted/exited by their leaving of the dialog. Eg: They have initiated an action from a button on a main page, and are now looking at its status while it completes. 

Generally, 2 should not happen where we can avoid it (long-lasting actions should be async when possible - so the user can navigate away without risking cancelling out of it.

**Comment by scottdickerson** [comment]
can we also add the native warnings if they click links to navigate outside...

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.
