### ISSUE TITLE
[Table]: Pagination Alignment Bug

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#172]
Not sure when this was introduced, but we have an alignment issue with pagination selection arrows

<img width="729" alt="Screen Shot 2019-04-12 at 3 53 49 PM" src="https://user-images.githubusercontent.com/3360588/56065683-324ef600-5d3b-11e9-91db-9af098ddd9ec.png">

**Comment by scottdickerson** [comment]
that's actually what they ship in Carbon, when we upgrade we'll get the later one..

![image](https://user-images.githubusercontent.com/6663002/56868172-1449ec80-69ef-11e9-8e09-148959e3afb8.png)
