### ISSUE TITLE
[Table]: Column grouping

### ISSUE THREAD

**Issue by matsgothe** [IBM/carbon-addons-iot-react#173]
There is a change request on the Table component to support groupings of columns
![image](https://user-images.githubusercontent.com/23455181/56120417-58101100-5f6e-11e9-8cc1-095f85ff5f16.png)

MVP requirements
- Column may be given a group
- A Group has a name
- All grouped columns shall be managed as part the group 
  - The group may be reordered in relation to other columns / groups
  - The same user gestures shall be used to reorder a group as reordering a column
  - Individual columns in a group may be reordered
  - A column in a group may not be reordered / moved out of the group
  - A column in a group may be shown / hidden
  - Hiding the last column in a group will hide the group
- That shall be a visual design styling that differentiate top level columns and groups vs columns in a group. (see example above)
- All use-cases for sorting and filtering that apply to a column also apply to a column in a group.

**Comment by bryancboyd** [comment]
Additional design showing that columns in groups are filterable:

![image](https://user-images.githubusercontent.com/2175647/58024682-635bdc80-7ad8-11e9-8730-a401ada71884.png)

**Comment by bryancboyd** [comment]
I've sized this at around 2 person-days for development and test.

**Comment by daphoenix** [comment]
Hey Bryan, here's the latest versions of the visuals for the double header update with filters.
## Table
![Table](https://user-images.githubusercontent.com/5711817/58052425-14a05800-7b55-11e9-97e9-f360037a75af.png)

##Table with filters
![Table with Filter](https://user-images.githubusercontent.com/5711817/58052439-1d912980-7b55-11e9-9d59-be9e5a90dde9.png)

@amymillett please could you review visual design and let Laura + me know if you have any comments, updates or queries?
Thanks.

**Comment by davidicus** [comment]
@amymillett is this design completed? Is there an updated spec we can link here?

**Comment by matsgothe** [comment]
@amymillett @davidicus I'm validating if this has been included in the EDS.

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.

**Comment by matsgothe** [comment]
This requirement was added by the Tririga / Building Insights team. I'll FW the link in case its still relevant in the designs and should be reopened.

**Comment by matsgothe** [comment]
@davidicus I confirmed that Tritiga / BI withdraw this requirement.
---
Thanks for letting us know, Mats.
We went with a different pattern for the current designs for TBI, so it is no longer required.
Mit freundlichen Grüßen/Kind regards,
Laura Dohle
