### ISSUE TITLE
[Table]: Needs to work correctly with asynchronous data and paging

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-addons-iot-react#186]
# Issue Details

## Detailed description

The AsyncTable does a good job of showing how to work with remote data, but, the design of the Table is flawed, in that is requires that the Table be fully aware of the contiguous data stream.  ie, forcing the table to keep in memory all the loaded items defeats the purpose of using paging and async data.

In <AsyncTable> the code the loads the data and updates the table

```javacript
          // update the table data
          dispatch(
            baseTableActions.tableRegister([...state.data, ...tableData], data.meta.totalRows)
          );
```

Works because it keeps appending to the in memory set.  This doesn't scale.  If I point this to a real datasource of 1,000,000 records, this will not work.

If I change the table, to use...

```javacript
          // update the table data
          dispatch(
            baseTableActions.tableRegister([...tableData], data.meta.totalRows)
          );
```

Ie, removing the initial data state, the table does not move to page 2 (or any page)

Is this issue related to a specific component?

AsyncTable

What did you expect to happen? What happened instead? What would you like to see changed?

Table should only load the page into memory for data that is visible

**Comment by bryancboyd** [comment]
@stuckless This is my first time looking at the AsyncTable example, but my initial thought is there is nothing stopping the user who implements the async-data-fetching from only populating the array indices of `data` that will be in the new current view, for example:

`data={[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, { ...some data }, {}, {}, {}, {}, {}]}`

The only requirement is that the data prop array has a size corresponding to the row index of the page in view -- so if the user has a table with 100k records, a page size of 100, and is on page 900... `data` would have a length of 90k.  Any data not currently in view could just be defined with an empty object though.

If we do want to allow the user to only **explicitly pass** the data that will be rendered in the current page, we could allow `data` to be **either** an array or an object with keys mapping to the index of the row, for example:

```
data={{
  90001: { id: 'row-90001', values: { ... } },
  90002: { id: 'row-90002', values: { ... } },
  90003: { id: 'row-90003', values: { ... } },
  ...
}}
```

IMO this adds too much complexity to the model to make it the default interface, but we could certainly support this if it helps the 1million+ table row use case.  @stuckless what do you think?

**Comment by stuckless** [comment]
I get how complex this can be.  In our application we use a "datasource" that manages this complexity for us, and it's intelligent enough to know how much data to load and do it page by page, etc.  I've also been able to wire it up to react-window to do infinite lists.

It would be nice if we could get the Table to work page by page, and not care about how many real records exists.  While I don't personally forsee a million records, in maximo, the scenario is plausible.  Some customer has have 50+ million work orders.

The interesting thing is that I had the table working 1 page at a time, but I found a "bug" in that I could never get the pagination bar to reset back to page 1.  It turns out that because I was never setting state.view.pagination.page when I changed pages, it thought I was on page 1.  All my sorting, filtering and paging all worked, but, when I sorted I wanted it to go back to page 1, and I never would.  I thought it was bug in the table, but, turned out, that the table always thought I was on page 1, so telling it go to page 1 didn't cuase it update.  ie, this was already really close to working as it is today.  I just wonder if the may the pagination needs work and the table itself might be ok.

And yeah, I'd rather not change the data model.  I'm not happy with the current one, but I'm less happy with the proposal :)

**Comment by bryancboyd** [comment]
@stuckless yeah, our Device Management tables in IoTP need to support 100k+ records as well, so we have some of the same concerns.  Perhaps we could add an option that bypasses the `data + pagination` interaction (where the subset of `data` being displayed is determined by the pagination passed in) and allows you to just pass in the `data` for the particular page being displayed?

**Comment by stuckless** [comment]
@bryancboyd I think that would be good, and to be honest, I think you already close to getting it working that way.

**Comment by scottdickerson** [comment]
How would we handle Select All in this case?  Need to make sure this is working correctly without forcing it to be in memory

**Comment by scottdickerson** [comment]
Think about filtration and column sort as well

**Comment by stuckless** [comment]
I agree... all these things needs to be taken into account.   Does a select all even make sense when you have 100K records?

For things like sort/filter, when the table triggers a change in those new data is loaded and table basically get reset.  We have that working now, with the table, as is, since all of our sorting and filtering happens on the server.

**Comment by stuckless** [comment]
@bryancboyd @scottdickerson - I wouldn't hide the select all, but allow it to be user controlled.  We might need to go back to the Design folks and get clarification on what "select all" means.  Does it mean select all on this page, or select all in this dataset?  If we look at gmail (and I'm not saying that we should mimic this) select all is basically select all on this page.  In fact, if I select all on page 1, then go to page 2, select all is now turned off, if I select all, then all rows on the page is selected.  If I hit delete, the delete action is ONLY applied to the selected rows on this page.  When I navigate back to page 1, all my rows exists, and they statefully remain selected.

I think that in an async table, we still need the concept of "select all" even it only means "all on this page".  If I'm shows 50 items per page, I don't want to manually select each of the 50 items to do a select all.

But again, this should go back to the design group to better understand what the behaviour of a "select all" means in a 1 million row table.

@JordanWSmith15 - do you have any thoughts on this?

**Comment by bryancboyd** [comment]
@stuckless sounds good -- in either case, it would be up to the consuming application to determine how to handle the `onSelectAll` event anyway.

I'll work on the table update today to support passing just the current page dataset.

**Comment by JordanWSmith15** [comment]
@stuckless @bryancboyd We use select all in many tables to allow the user to take a batch action, and they usually assume it will take the action against all records in the list, even the ones that have not yet loaded. This is not what actually happens, because of the issues stated above... you can't take an action on a row that hasn't loaded. So, for 900 records, if the page size is 100, they must take the action 9 times.  Most of the time, this isn't a problem, but sometimes, it is (reconcile all inventory records, or mark all notifications as "read").  We absolutely need to support select all for at least the currently loaded page. I strongly recommend that the UI shows how many are selected vs how many are in the full table. We have actually extended our components in the tab and the batch action bar of the table to support exactly this:
![1](https://user-images.githubusercontent.com/21066152/57475317-19663180-7262-11e9-8687-dfbd26a5f056.gif)

**Comment by bryancboyd** [comment]
Thanks for bring that up @JordanWSmith15 -- both options (select-all on just the page, or on the whole data set) can be supported in the implementing application's handling of the `table.onSelectAll` callback, simply by updating the view to include all rows in `view.table.selectedIds[]` or just the rows visible on the page.

**Comment by bryancboyd** [comment]
![image](https://user-images.githubusercontent.com/2175647/57485403-40782f80-7271-11e9-80f0-eca65f3ee9bb.png)

https://github.com/IBM/carbon-addons-iot-react/pull/235
