### ISSUE TITLE
[Header]: App Switcher support to switch main app when within header

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#193]
Add app switcher to the top left of the Header

**Comment by davidicus** [comment]
Spec is outlined here:

https://ibm.invisionapp.com/share/SNNZ29ZAY6V#/screens/319167299
and
https://ibm.invisionapp.com/share/D6NZ4C0PUN9#/screens/319188836_Navigation_Panel_-_Usage

**Comment by davidicus** [comment]
Dupe of #58
