### ISSUE TITLE
[Table]: Allow Row Details to be a render function instead of a <Component>

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-addons-iot-react#198]
# Issue Details

## Detailed description

Table now allows a cell renderer for a column, which allows a single function to set that is called to do the rendering of the column.  In the same way, I'd like to see a `rowDetailsRenderer` so that we can set a single function on the table that is called when a detail render is required.  This allows us to NOT need to to build up the render component per row, but rather defer that component creation until the row details is actually expanded.  The row renderer function would normally be passed a props structure that includes the item being renderered, id of the item, and maybe the index.

Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

Is this issue related to a specific component?

Table

**Comment by scottdickerson** [comment]
do you want something similar for the children prop for the nested rows?

**Comment by scottdickerson** [comment]
@stuckless Same support for rowActions so that we're not forced to render RowActions ahead of time for non-visible rows

**Comment by scottdickerson** [comment]
we could introduce a breaking change where we deprecate rowActions and children inside the data row and only keep data.

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.
