### ISSUE TITLE
[Table]: Need UX for long running table Batch Actions

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#225]
# Issue Details
Need some guidance from UX on how long running table Batch Actions should communicate their in progress state and any errors.

## Detailed description

Just like this one: https://github.com/IBM/carbon-addons-iot-react/pull/224, but for Batch Actions,  It's a little more complicated though because I don't think we want to allow selection changes as the long running operation is running.

Since it also applies to the whole table state, should something wider range be shown?

**Comment by amymillett** [comment]
@davidicus For batch actions, I think we should use the same UX idea as in this issue: https://github.com/IBM/carbon-addons-iot-react/issues/107

" If there's a large amount of records being deleted via batch actions and it will take awhile for the table to update, I would use the overlay and loading animation provided by Carbon"

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.
