### ISSUE TITLE
[Storybooks]: chore add RtoL build step to storybook

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#229]
https://github.com/carbon-design-system/carbon-components/blob/v10.2.0/docs/g11n.md

To actually setup carbon to work in RtoL mode, we need to update this prop

**Comment by tay1orjones** [comment]
@scottdickerson is this still valid? I think we've got RTL working - the RTL toggle in storybook works as you'd expect.

**Comment by davidicus** [comment]
we have RTL support with knobs. This issue is stale. Closing. Please re-open if needed.
