### ISSUE TITLE
[TABLE] Sort order icon

### ISSUE THREAD

**Issue by matsgothe** [IBM/carbon-addons-iot-react#231]
The icon used on the column header to indicate the sort order is not the icon in the Carbon design.

**Comment by matsgothe** [comment]
These icons are the Up / Down icons in the Carbon designs
![Arrow Down](https://user-images.githubusercontent.com/23455181/57280466-65ba4180-70a9-11e9-8368-2e1ae50ed72c.png)
![Arrow UP](https://user-images.githubusercontent.com/23455181/57280628-7074d680-70a9-11e9-8ef6-01231106693c.png)

**Comment by matsgothe** [comment]
@amymillett please validate

**Comment by amymillett** [comment]
@matsgothe The sort icon has changed between Carbon 9 and Carbon X. Carbon 9 does sorting with the triangle/ chevron, which is currently being used in the IoT table.

<img width="217" alt="Screen Shot 2019-05-08 at 10 19 21 AM" src="https://user-images.githubusercontent.com/48336859/57386826-ccf3f680-717a-11e9-9954-20942f01fb29.png">

Carbon X uses the arrows you have indicated 

<img width="700" alt="Screen Shot 2019-05-08 at 10 21 10 AM" src="https://user-images.githubusercontent.com/48336859/57386935-09bfed80-717b-11e9-82c7-58ac82d27be0.png">

They have also added a hover state with an additional icon 

<img width="698" alt="Screen Shot 2019-05-08 at 10 21 44 AM" src="https://user-images.githubusercontent.com/48336859/57386972-1b08fa00-717b-11e9-8cc1-09d8073ee4ae.png">

You can see an example in the [Carbon storybook](http://react.carbondesignsystem.com/?selectedKind=DataTable&selectedStory=with%20sorting&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) This is definitely something that will be changing when we move to Carbon X.

**Comment by matsgothe** [comment]
OK, I'll close this for now and we will update the icon when we convert to Carbon 10.
