### ISSUE TITLE
[TABLE] Expand / Collapse row icon

### ISSUE THREAD

**Issue by matsgothe** [IBM/carbon-addons-iot-react#232]
The chevron icon used in the Table component is the icon used by Carbon. This icon should be the expanded icon. 
![Chevron UP](https://user-images.githubusercontent.com/23455181/57280882-0f99ce00-70aa-11e9-98d7-1d5bf015ba66.png)

**Comment by matsgothe** [comment]
@amymillett to verify

**Comment by davidicus** [comment]
Issue is complete as we have chevron in table component as seen on our storybook

![image](https://user-images.githubusercontent.com/1590966/62471560-ec46f380-b76a-11e9-9b06-fc9711492b6d.png)
