### ISSUE TITLE
[NavigationBar]: Update the tabs to match this pattern

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#239]
https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/components/secondary-navigator/specifications

See the tab layout there.  Need some guidance on where to put the hero in that layout

**Comment by scottdickerson** [comment]
@filipecorrea needs this for the Blockchain piece as well

**Comment by davidicus** [comment]
Header deprecated. Closing issue. This work should be settled in PageTitleBar component.
