### ISSUE TITLE
Simple stateful example has squashed batch action header

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#240]
# Issue Details

## Detailed description

In simple stateful example  of the table the top bar is squashed

Viewed in Chrome

## Additional information

![image](https://user-images.githubusercontent.com/1590966/57549804-8c3edd80-7332-11e9-8814-015fbcf7926c.png)

**Comment by billpereira** [comment]
Hey David... i've increased that in 1 rem... check if that is enough
![image](https://user-images.githubusercontent.com/38498198/58371855-c0e29580-7eeb-11e9-83dc-707a47902a51.png)
