### ISSUE TITLE
[TABLE] Filter help text updates

### ISSUE THREAD

**Issue by matsgothe** [IBM/carbon-addons-iot-react#244]
The prompt text in the filter, uses the word "Pick" based on the example in the storybook.
However, discussing this with the team, "Enter" may be more appropriate instruction for the user, where we are expecting the user to type in some text. We will most likely keep the word "Pick" for selecting from a dropdown box, e.g. the "Pick a Status".

**Comment by HNorlen** [comment]
Use "Enter" if the user is entering text. Use "Select" or "Pick" if the user picks from a preset list of options. 

If the field allows for both, use "Enter or select" or "Enter or pick" or similar.
