### ISSUE TITLE
[Table]: multirow select not working when Table is used with base reducer

### ISSUE THREAD

**Issue by tomklapiscak** [IBM/carbon-addons-iot-react#245]
baseTableReducer expects the value of `options.hasRowSelection` to be passed as a parameter to the `tableRowSelect` action:

```
    case TABLE_ROW_SELECT: {
      const { rowId, isSelected, hasRowSelection } = action.payload;  <------------------
      const isClearing =
        hasRowSelection === 'multi' && !isSelected && state.view.table.selectedIds.length <= 1;
```

However, none of the invokations of the `onRowSelected` function in the `Table` component include this parameter, e.g.:
```
    <StyledSingleSelectedTableRow
      key={id}
      onClick={() => {
        onRowClicked(id);
        onRowSelected(id, true);   <------------------
      }}>
      {tableCells}
    </StyledSingleSelectedTableRow>
```

The `StatefulTable` example has worked around this by injecting the parameter in its own implementation of `onRowSelected`:

```
onRowSelected: (rowId, isSelected) => {
        dispatch(tableRowSelect(rowId, isSelected, options.hasRowSelection));
```

One of two solutions:
1. Ensure all calls to `onRowSelected` from `Table` include this parameter, e.g.
```
    <StyledSingleSelectedTableRow
      key={id}
      onClick={() => {
        onRowClicked(id);
        onRowSelected(id, true, hasRowSelection);  <------------------
      }}>
      {tableCells}
    </StyledSingleSelectedTableRow>
```

2. Update baseReducer to pull this value from options, rather than expecting it to be present in the action payload, e.g.:

```
    // Row operations
    case TABLE_ROW_SELECT: {
      const { rowId, isSelected } = action.payload;
      const hasRowSelection = state.options.hasRowSelection;  <------------------
      const isClearing =
        hasRowSelection === 'multi' && !isSelected && state.view.table.selectedIds.length <= 1;
```

I prefer solution 2, but there might be a good reason for including this value in the action payload that I am not aware of.

**Comment by davidicus** [comment]
Need to check if still valid.

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.
