### ISSUE TITLE
[Table] Add custom sort function to StatefulTable

### ISSUE THREAD

**Issue by bryancboyd** [IBM/carbon-addons-iot-react#251]
## Overview

The `<StatefulTable>` component uses a default sort function that handles strings (`localeCompare`) or numerical values (`a.values[columnId] < b.values[columnId]`).  To handle sorting columns that use a complex value w/ cell renderer, we need the ability to pass a custom sort function in to StatefulTable.

https://github.com/IBM/carbon-addons-iot-react/blob/70dfe6a4feae0b2a52b5b9a5f6ada3b7b800e0ec/src/components/Table/tableReducer.js#L193

**Comment by daphoenix** [comment]
@tay1orjones please add Kalyani to this task to pair with you. Thanks.

**Comment by davidicus** [comment]
closed by this [PR](https://github.com/IBM/carbon-addons-iot-react/pull/843)
