### ISSUE TITLE
[TileCatalog]: Don't show pagination controls if we don't have enough records

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#252]
If we have less records than our max page size, hide pagination controls

**Comment by billpereira** [comment]
Is it what you expect?
Pages=1
![image](https://user-images.githubusercontent.com/38498198/58443992-255c4b00-80cc-11e9-83c8-af28742c4ddb.png)
Pages>1
![image](https://user-images.githubusercontent.com/38498198/58443998-30af7680-80cc-11e9-8961-bfc17a60464d.png)

**Comment by billpereira** [comment]
Or is it better keeping the page property just hiding the buttons?
![image](https://user-images.githubusercontent.com/38498198/58444322-18d8f200-80ce-11e9-9ca3-75a17bd180d7.png)
![image](https://user-images.githubusercontent.com/38498198/58444326-22625a00-80ce-11e9-9198-0498e1b8530b.png)
