### ISSUE TITLE
[TABLE] Need a way to disable filtering for some columns

### ISSUE THREAD

**Issue by tomklapiscak** [IBM/carbon-addons-iot-react#253]
At present, (as far as I can tell) iit is only possible to enable filtering on ALL columns (`options.hasFilter=true`) or NO columns (`options.hasFilter=false`).

I have a use case where only a subset of columns should be filterable (since filtering of some of them is not supported by the API I am calling).

To this end (and to retain backwards compatiblity), I suggest something like the following:

Add `isFillterable` property to column prop types:
```
export const TableColumnsPropTypes = PropTypes.arrayOf(
  PropTypes.shape({
    id: PropTypes.string.isRequired,
    name: PropTypes.string.isRequired,
    isSortable: PropTypes.bool,
    isFilterable: PropTypes.bool, <--------------
```

This will default to `true`. A filter box will be rendered underneath a particular column if and only if both `options.hasFilter` AND `<column>.isFilterable` are true.

@bryancboyd: any objections?

**Comment by bryancboyd** [comment]
@tomklapiscak great approach, go for it 👍

**Comment by tomklapiscak** [comment]
Turns out half of this was already done: FilterHeaderRow already accepted an <column>.isFilterable boolean, the value of which was being determined dynamically based on whether or not <column>.filter property was present. It just wasn't doing anything with this property. I've fixed this and raised PR https://github.com/IBM/carbon-addons-iot-react/pull/254.

@bryancboyd: would you mind taking a look and approving the PR if you think it all makes sense?
