### ISSUE TITLE
[Header] Desktop Support for left navigation, top dropdown menus

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#27]
## Detailed description

Enhancement request to have a shared UI Shell/Navigation drop.  Starting from Carbon component UI Shell

Target is Q2 for IoT Platform teams and IoT CS, Main pressure would be @jordanwsmith15 team

**Comment by JordanWSmith15** [comment]
Maximo's requirements will be stated in these InVision prototypes. Prototypes may update/change as Luke and I iterate:
Desktop/Tablet:  https://ibm.invisionapp.com/share/W3NYOFMQRNY#/319012843_Base
Mobile:  https://ibm.invisionapp.com/share/VCNYOFW3DAB#/319012908_Base

**Comment by scottdickerson** [comment]
@davidicus we will start delivering a standard Left Nav that expands collapses with subpages, then open a separate issue to track the "Nav selector" on top of the Left Nav and implement this separately.  We will attempt to deliver both in Sprint 4.

**Comment by scottdickerson** [comment]
First drop desktop, open separate issue on mobile responsive design under main Header epic

**Comment by davidicus** [comment]
After trying to implement into AS I found that we need more flexibility in both Header component and SideNav. Working on those and will open up separate issue for those changes. This work will be on hold until those changes are made.

**Comment by scottdickerson** [comment]
congratulations!
