### ISSUE TITLE
Console error thrown when consuming stateful table and leaving it's page

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#280]
![image](https://user-images.githubusercontent.com/6663002/58862603-4e26a680-86b1-11e9-8826-113555e81d79.png)

**Comment by davidicus** [comment]
I think this has been resolved with Carbon update. Will verify before closing

**Comment by tay1orjones** [comment]
I haven't heard of any further repros of this and it's quite stale. Closing
