### ISSUE TITLE
[Table] Add "onBlur" trigger mode to quicksearch

### ISSUE THREAD

**Issue by tomklapiscak** [IBM/carbon-addons-iot-react#290]
At present, Table fires a TABLE_SEARCH_EVENT on every change to the quicksearch input. This is not appropriate for all use cases (e.g. when filtering is performed server-side). For this reason, it would be useful to be able to configure the table to fire TABLE_SEARCH_EVENT onBlur.

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.
