### ISSUE TITLE
[Dashboard] Update all dashboard components to support Carbon v10

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#306]
Dashboard/monitoring components are baked with v9 and experimental as of now.

We need to update these components to support Carbon v10 either during the v2.0.0 beta phase, or can be done after the initial cut of v2 as well.

**Comment by davidicus** [comment]
We are bringing these components into master with issue #566.

**Comment by tay1orjones** [comment]
As a part of a v10 design evaluation/refactor for the dashboard components, we need to refactor off of `Toolbar`, `ToolbarTitle`, `ToolbarItem`, `ToolbarOption`. I believe we only use these in the header of `Card`.

[Carbon made a mistake including them in v10](https://github.com/carbon-design-system/carbon/pull/4097), and it will be removed in v11. It would be preferred to find an alternate solution now and fix.

cc @amymillett @CynZhang @lukefirth

**Comment by davidicus** [comment]
This work has been completed and any discrepancies will be dealt in individual bug issues.
