### ISSUE TITLE
[table] Audit differences between Carbon X table and our add-on

### ISSUE THREAD

**Issue by amymillett** [IBM/carbon-addons-iot-react#339]
1. Document any overlap design between Carbon X and the Carbon 9 add-on
2. Document specific differences in design between Carbon X and the Carbon 9 add-on

**Comment by amymillett** [comment]
_I am using this to evaluate the Carbon X data table: http://react.carbondesignsystem.com/?path=/story/datatable--default_

**Key feature differences between the IoT Table add-on and the Carbon X data table (solely from a design perspective)**

**Unique to Carbon X**
- Option for a data table title and description
- Option with batch expansion
- Option with dynamic content (ability to add rows and columns)

**Unique to the IoT Add-On Table**
- Option for nested rows
- Option for advanced filtering on columns using text input or dropdown
- Option for reordering columns
- Option for additional in-line actions or buttons (other than an overflow icon)
- Option for custom cell content, such as icons
- Option for "lightweight" design
- Option with horizontal scrolling
- Custom loading and empty states (I assume Carbon X has these too, but I'm not sure what they look like)

**Comment by amymillett** [comment]
_I am looking at this: https://beta.carbon-addons-iot-react.com_

**Some notes on the IoT add-ons table now that it has been moved to Carbon X**
@davidicus @lukefirth 

**1. Theming** 
- I'm not entirely sure if this is a relevant note, so feel free to disregard if needed.
- These data tables (plus some other components) appear to be using the Carbon X White theme, where the page background is #FFFFF and the component background is typically #F3F3F3.
![Screen Shot 2019-06-24 at 1 56 09 PM](https://user-images.githubusercontent.com/48336859/60044381-d92f0700-9687-11e9-92f6-3c4c1266286e.png)
- IoT is moving towards using the Carbon X Grey10 theme, where the page background is #F3F3F3 and the component background is #FFFFFF, like this:
![Screen Shot 2019-06-24 at 1 57 48 PM](https://user-images.githubusercontent.com/48336859/60044483-14c9d100-9688-11e9-88e1-8f9ea1311bed.png)


**2. Sorting**

- Sorting works as it should but there's some extra padding around the cell
![Screen Shot 2019-06-24 at 1 19 19 PM](https://user-images.githubusercontent.com/48336859/60042187-bfd78c00-9682-11e9-9466-f57bac0a658a.png)
- Should look like this:
![Screen Shot 2019-06-24 at 1 21 35 PM](https://user-images.githubusercontent.com/48336859/60042293-04632780-9683-11e9-8fc9-392339f5b832.png)

**3. Filters**

- The remove filter icon (X) in the combo-box dropdown looks different from the regular text input. Technically the X in the black square is correct based on Carbon documentation, but I think it looks odd and distracting. 
![Screen Shot 2019-06-24 at 1 27 23 PM](https://user-images.githubusercontent.com/48336859/60042667-e0541600-9683-11e9-895f-aef51e4af947.png)

- My suggestion is the keep using the same icon and to keep it on a white background:
![Screen Shot 2019-06-24 at 1 33 17 PM](https://user-images.githubusercontent.com/48336859/60042994-a7687100-9684-11e9-987f-13171fd83531.png)

- Also, just a question: Where'd this filter icon come from? Did a new one get released? We used to have a different icon.
![Screen Shot 2019-06-24 at 1 47 00 PM](https://user-images.githubusercontent.com/48336859/60043838-a3d5e980-9686-11e9-9f8b-115af9ffc61d.png)

**4. Column reordering**

- This definitely needs some Carbon X-ing, since it's a custom feature
![Screen Shot 2019-06-24 at 1 50 42 PM](https://user-images.githubusercontent.com/48336859/60044045-29f23000-9687-11e9-85aa-c4c99efc1f8a.png)

- My suggestion involves changing the buttons to black, styled after the secondary button:
![Screen Shot 2019-06-24 at 2 05 47 PM](https://user-images.githubusercontent.com/48336859/60044982-3ecfc300-9689-11e9-921f-ef4fa3344d47.png)

- It's also worth noting that Guidea has recommended an entirely different design for column picking and reordering, but we do not have that implemented in any way (as far as I know)
![Screen Shot 2019-06-24 at 2 07 07 PM](https://user-images.githubusercontent.com/48336859/60045037-5eff8200-9689-11e9-9d69-ec13c5aa7f86.png)

**5. Nesting**
- Looks like there might be an issue with the border getting cut off? Also needs a color update
![Screen Shot 2019-06-24 at 2 09 48 PM](https://user-images.githubusercontent.com/48336859/60045151-bf8ebf00-9689-11e9-85c7-8f27aa4bf65a.png)

- I think we can change the background of that :before element to #DCDCDC (the same as the column title area)
![Screen Shot 2019-06-24 at 2 25 27 PM](https://user-images.githubusercontent.com/48336859/60046022-f2d24d80-968b-11e9-9d25-2a21c8969c1e.png)

**6. Single-select**
- Not sure where this is being used, but the blue needs to be updated to #0062ff
![Screen Shot 2019-06-24 at 2 28 13 PM](https://user-images.githubusercontent.com/48336859/60046179-52c8f400-968c-11e9-9699-b08e6c599639.png)

**7. Loading state**

![Screen Shot 2019-06-24 at 2 29 03 PM](https://user-images.githubusercontent.com/48336859/60046230-712eef80-968c-11e9-88b8-72b43edcb388.png)
- Has Carbon released a new version of this? Seems like it should be some shade of grey rather than blue

**8. Lightweight Design**
- I think this design got overridden, since it just looks like the regular version of the table.

- This is what it should look like:
![Screen Shot 2019-06-24 at 2 31 06 PM](https://user-images.githubusercontent.com/48336859/60046334-bbb06c00-968c-11e9-8416-60e31dfd9b6e.png)
- The lightweight design is a regular table, just with custom styling that includes removing any background coloring and adding a heavier line beneath the column title

**Comment by davidicus** [comment]
This was closed with the PR referenced above
