### ISSUE TITLE
[v2] Align Components to Patterns

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#354]
Inventory needs to be taken of the existing components, and audit them against the patterns being established in the Watson IoT Design System. Document defects so we can fix.

Components
- [ ] Table #339, #331
- [ ] Navigation/UI Shell - #357
- [ ] ...
- [ ] ... please add more here w/ linked issue

**Comment by davidicus** [comment]
closing. out of date
