### ISSUE TITLE
[Navigation] Audit UI Shell components against Navigation pattern

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#357]
With recent changes to the UI shell, we need to review the components presently in `beta` and document what needs to be changed to fall in line with the pattern defined in the [Watson IoT Design System](https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/patterns/navigation)

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.
