### ISSUE TITLE
[Table]: Handle automatic truncation at max-width and native browser flyovers

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#36]
## Detailed description

Tables should automatically truncate at some max-width and set titles on spans for automatic browser flyovers.

![screen shot 2019-02-27 at 10 07 25 am](https://user-images.githubusercontent.com/6663002/53504427-8d70a600-3a77-11e9-9b4a-bfdfc02a4dc1.png)

**Comment by scottdickerson** [comment]
also going to allow width to be overridden by consumers

**Comment by CynZhang** [comment]
One case to consider wrt truncation: when scaling a column's width down, we should also ensure sufficient text remains visible at its smallest size so that the information that is visible is still informative. For example, try truncating full words at time to avoid presenting partial words.

**Comment by scottdickerson** [comment]
I think this is tough to do @CynZhang maybe impossible in a internationalization aware way.  We will allow users of the table to set their own max width based on what makes sense to them to try and truncation.  https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
