### ISSUE TITLE
Component Request - [ResourceSelectionList]

### ISSUE THREAD

**Issue by bryancboyd** [IBM/carbon-addons-iot-react#375]
# Component Details

## Detailed description

As part of our new IoT application setup pattern, we have need of a component that allows selection of a resource from a list

## You will consider this component complete when...

- [ ] it renders a list and allows single selection with a callback
- [ ] adds overflow button on list item
- [ ] adds rich content on list item (to support icons) or a prop to pass an icon
- [ ] adds control buttons on list header
- [ ] pagination?  TBD
- [ ] a11y, tests, documentation

## Additional information

![image](https://user-images.githubusercontent.com/2175647/60599987-0315b700-9d75-11e9-87e9-6208c84eaf52.png)

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.
