### ISSUE TITLE
Component Request - [ImageCard]

### ISSUE THREAD

**Issue by filipecorrea** [IBM/carbon-addons-iot-react#383]
# Component Details

## Detailed description

As part of the new IoT Platform monitoring dashboard, we need a card that renders an image, rescale it and has zoom controls.

## You will consider this component complete when...

The initial version of this component should support

- [ ] Load and rescale image to initially fit in card
- [ ] Automatically scale image when card size changes
- [ ] Zoom in and zoom out controls
- [ ] Zoom to fit control
- [ ] Image minimap and guide

New features will be developed as separate issues.

## Additional information

![8aa4ec80-9cc7-11e9-9baa-4eb003b17be7](https://user-images.githubusercontent.com/1496656/60991031-19e17e00-a320-11e9-8916-33be3bfc6d27.png)

https://github.ibm.com/wiotp/monitoring-dashboard/issues/83

**Comment by davidicus** [comment]
Reopening issue to go through advanced acceptance criteria which will remove the labels as they go through
