### ISSUE TITLE
[RTL support] Elements in the screen get misplaced on RTL mode

### ISSUE THREAD

**Issue by camilasb** [IBM/carbon-addons-iot-react#410]
Steps:
1. Open the IoT storybook 
https://beta.carbon-addons-iot-react.com/?path=/story/table--stateful-example-with-expansion
2. Click on Table component "Stateful Example with expansion"
3. Click on RTL tab
4. Click on Right-to-left toggle
5. Click on the Reorder Columns button
6. Click on the column buttons to hide them

Actual Result: Column titles and data get misplaced from each other
<img width="1345" alt="Pasted Graphic 1 copy" src="https://user-images.githubusercontent.com/20360162/61707060-00790280-ad20-11e9-82af-bc983e33eda0.png">

7. Scroll down the screen and verify the pagination footer

Actual Result: Elements are misplaced

![image](https://user-images.githubusercontent.com/20360162/61707821-b55fef00-ad21-11e9-8c36-93d6bbf1e4ff.png)

8. Open the details of one of the records

Actual Result: Details are shown on the left still
Expected Result: Details should be shown on the right(?)

![image](https://user-images.githubusercontent.com/20360162/61707841-bd1f9380-ad21-11e9-8997-89fd703c59e8.png)

**Comment by davidicus** [comment]
completed.
