### ISSUE TITLE
[Table]: Allow row actions to use custom components instead of Icon

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-addons-iot-react#414]
Currently we set row actions using the following props...

```javascript
export const RowActionPropTypes = PropTypes.arrayOf(
  PropTypes.shape({
    /** Unique id of the action */
    id: PropTypes.string.isRequired,
    /** icon ultimately gets passed through all the way to <Button>, which has this same copied proptype definition for icon */
    icon: PropTypes.oneOfType([
      PropTypes.shape({
        width: PropTypes.string,
        height: PropTypes.string,
        viewBox: PropTypes.string.isRequired,
        svgData: PropTypes.object.isRequired,
      }),
      PropTypes.string,
      PropTypes.node,
    ]),
    disabled: PropTypes.bool,
    labelText: PropTypes.string,
    /** Action should go into the overflow menu, not be rendered inline in the row */
    isOverflow: PropTypes.bool,
  })
);
```

While `node` is a valid option here, under icon, if you use a node that is NOT a carbon icon, then it does not work.   Ultimately it would be good to allow any kind of "node" there, OR mutally exclusive to `icon` we can set a node instead of an icon.  So something like...

```javascript
export const RowActionPropTypes = PropTypes.arrayOf(
  PropTypes.shape({
    /** Unique id of the action */
    id: PropTypes.string.isRequired,
   
   /** node to render as an action */
  node: PropTypes.node,

    /** icon ultimately gets passed through all the way to <Button>, which has this same copied proptype definition for icon */
    icon: PropTypes.oneOfType([
      PropTypes.shape({
        width: PropTypes.string,
        height: PropTypes.string,
        viewBox: PropTypes.string.isRequired,
        svgData: PropTypes.object.isRequired,
      }),
      PropTypes.string,
      PropTypes.node,
    ]),
    disabled: PropTypes.bool,
    labelText: PropTypes.string,
    /** Action should go into the overflow menu, not be rendered inline in the row */
    isOverflow: PropTypes.bool,
  })
);
```
With this change, you could render custom components into the `actions` slot of the table.

```javascript
rowActions: [
   {id: 'action1', node: <MyIcon tooltip="some text" onClick={this.onIconClicked}/>},
   {id: 'action2', node: <MyButton icon="more" tooltip="more text" onClick={this.onMoreIconClicked}/>, isOverflow: true},
   {id: 'action3', icon: 'add' ,isOverflow: true}
]
```
The general processing would be that 
* IF `node` and `icon` are both present we issue a warning but only render node.
* IF `node` is present we render the node, as is, and do not wire up onclicks etc.  We have to assume that if you are rendering your own custom actions, then you are manageing your own events.
* if `icon` is present we render as it does today.

**Comment by tay1orjones** [comment]
I'm not opposed to this approach, but I'm curious what the UX use case is behind this change.

[Carbon's documentation](https://www.carbondesignsystem.com/components/data-table/usage#inline-actions), as well as [the spec from the IoT design team](https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319100284) doesn't include anything beyond Buttons (or the OverflowMenu encapsulating Buttons) as the type of node for row actions. We've already deviated slightly with the [running/error actions](https://beta.carbon-addons-iot-react.com/?path=/story/tablebodyrow--rowactions-running). @amymillett @JordanWSmith15 have you looked further into this? The documentation doesn't appear to have this piece or the running/error actions.

If there's a case out there for nodes other than Buttons for row actions, we should document those specific cases along with this implementation change. That documentation could influence the implementation here.

One thing that comes to mind is this vs. just exporting the component directly. We could consider that when a top level `node` proptype is added to a component, it could be a signal to us to re-evaluate if we should export the component for direct composition at the product level. If `TableBodyRow` was exported, you could roll your own `RowActionsCell` for the specific cases where a `Button` doesn't suffice.

**Comment by davidicus** [comment]
@stuckless 

>While node is a valid option here, under icon, if you use a node that is NOT a carbon icon, then it does not work. Ultimately it would be good to allow any kind of "node" there, OR mutally exclusive to icon we can set a node instead of an icon. So something like...

When you tried to use something other than the carbon icon what was failing? I am able to add a custom element to this story
![image](https://user-images.githubusercontent.com/1590966/62395342-f041fe00-b53d-11e9-9f0e-bfa24e880527.png)

**Comment by stuckless** [comment]
Sadly, I sort of left the table stuff due to the latest noise around potentially moving to an another version of the Table.   When it tried it, i used a custom button / button group (not a carbon button).  And it died terribly with a React type error.  When I troubleshooted it, it appeared to be expecting an Icon.  I can try to update to the latest and test again.

If I can add anything I want, and not have an overflow menu, then likely there is nothing I need to do, which is good.

@tay1orjones  the use case come from having a button bar in the table actions area that automatically collapses is there is not enough space to render.   This comes from a Maximo design.  That's all I know.  The current table design allows you to set a button on the row, or an overflow menu, but I need something that basically does that intelligently.

**Comment by stuckless** [comment]
@davidicus Are you able to render a button and NOT the overflow menu?  And instead of a button, can you render "anything".  If so, then there is nothing I need to do, but you might want to share your story code, since I wasn't able to do that.

**Comment by davidicus** [comment]
@stuckless Yes you can, I will add a sample to our table. I was thinking about doing this anyways but similarly thought of postponing until we discuss our table future. Our stories will need to be built out to better explain some of these features if they are not self explanatory.

**Comment by davidicus** [comment]
@stuckless Instead of `PropTypes.node` we need to be more specific and use one of 

```
// A React element (ie. <MyComponent />).
  optionalElement: PropTypes.element,
 
  // A React element type (ie. MyComponent).
  optionalElementType: PropTypes.elementType,
```

In the case of the table we should be using elementType. I am going to update the table to use this proptype.

**Comment by davidicus** [comment]
Closing this issue as it is supported functionality.

**Comment by stuckless** [comment]
In case someone goes looking it appears you need to set the 'custom content' in the labelText field of the rowActions configuration.  (that is not intuitive and took me having to look deep into the source code for where this was implemented to figure that out :()
