### ISSUE TITLE
[Table]: Search default value and clear filters not working as expected

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-addons-iot-react#429]
If I set the `toolbar.search.value` state with a value, the Table's Search does not reflect that value.  It does appear to apply that search but it does not reflect it in the search text box.

Likewise clear all filters action appears to only clear the filters and not the search text (that might be by design, which is fine).  This is where i noticed the issue, since I don't allow both a filter and a search to co-exist, so once a filter is applied, I clear the search box, but the table never actually updates that search text box field.

The other use case is that our search state comes from a datasource which holds the current search that is applied.  When restoring state to the table from the datasource, and setting the `toolbar.search.value` to a value, the textbox does not reflect that value.

## Expected Behaviour
When we set or clear toolbar.search.value the table's Sarch textbox should visually update with that value.

You can easily test this in storybook, by, quickly, setting the default props value for `view.toolbar.search.value` to some text, and see if the storybook table shows that value (it doesn't).

**Comment by stuckless** [comment]
@tay1orjones @davidicus @bryancboyd @scottdickerson This bug has been on the books for awhile, any sense as to when this might get queded up.  It basically prevents us from setting the search bar value programatically (which we need to restore/set the state of the table.

**Comment by stuckless** [comment]
@davidicus You were asking if there was something you can do.  This bug has now caused 4 separate defects in our codebase, since, we cannot programatically set/clear the search filter.   Our filter state comes from the Datasource.  So the datasource might be filtered from another view, and then we attach it to the table.  A couple of things happen.  1. We can't set a new filter state to show in the header, 2. if the set that value to an empty string, it still shows the old value.   In our case we have the same table instance and we just set a new datasource on the table and everything updates, including columns, etc, but this search box will retain the old state and will not update despite the fact that I've set the value.  @JordanWSmith15

**Comment by enricoberti** [comment]
@stuckless @davidicus after a deep dive into how to fix the pre-filled search box issue, it turns out that we need to wait for [this Carbon commit](https://github.com/carbon-design-system/carbon/commit/e97a7ed9be2911707066c406544310f6cb76f273) to land. 

To test out things, you can for now use this two tags:
"carbon-components": "10.10.0-rc.0",
"carbon-components-react": "7.10.0-rc.0"

and then set the 'defaultValue' prop on `<TableToolbarSearch>` to both set a value and expand the search box.

**Comment by stuckless** [comment]
@davidicus @enricoberti Could you follow up with carbon to get an update on when when 10.10 is getting released, and then how long it will take for us to get it into IoT repo?   Do we think this is in the April timeframe?

**Comment by stuckless** [comment]
Just an update on behaviour... As of right now, since I've pulled the latest IoT code (about a week ago), we have noticed that because we are attempting to set the `search.value` it's basically making the search field readonly.  Before we could type into it and it would search... but now it's like it's read-only if you set a value there.  I've removed any code on our side that syncs the datasource search with the table search until this is resolved.

**Comment by davidicus** [comment]
@stuckless I have asked for a release date in the slack channel and I am waiting to hear back.

**Comment by stuckless** [comment]
@davidicus I think I missed that... but basically this is for the april release of the solution suite.

**Comment by stuckless** [comment]
I came here and wanted to check on the status because I got another opened bug today because table search is not showing the search value when I leave and come back :(
