### ISSUE TITLE
[Repo] Check components for RTL support

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#431]
Go through all components and check for RTL support. Open up new individual RTL bug issues and link them to this epic for tracking.

**Comment by KarenGski** [comment]
Question about the text in general - It doesn't actually flip the order of the characters or the words to read from right to left, but it does flip the order of sentence and punctuation.  Is that as expected?

**Comment by KarenGski** [comment]
Just met with Amy to divvy up the work.  Adding a checklist so we can track what we've completed.
We assume that we don't need to do the Carbon components.  @davidicus correct?

- [ ] Add card
- [ ] Base modal
- [ ] ButtonEnhanced
- [ ] FileDrop
- [ ] Header
- [ ] WizardInline
- [ ] NavigationBar
- [ ] PageHero
- [ ] ProgressIndicator
- [ ] ResourceList
- [ ] SideNav
- [ ] SimplePagination
- [ ] StructuredList
- [ ] TAble
- [ ] TableBodyRow
- [ ] TableDetailWizard
- [ ] TilesCatalog
- [ ] WizardModal

**Comment by KarenGski** [comment]
Completed BaseModal
Opened Issue #444

**Comment by KarenGski** [comment]
ButtonEnhanced complete - Opened Issue #445

**Comment by KarenGski** [comment]
Tables in progress - Opened issue #446

**Comment by KarenGski** [comment]
Table complete - issue #446.  Discovered an issue with the "horizontal scroll - full width" that occurs in LTR as well.  Opened issue #448

**Comment by KarenGski** [comment]
TableBodyRow complete - Issue #449
TableDetailWizard complete - Issue #450
TileCatalog complete - Issue #451
WizardModal complete - issue #452

**Comment by amymillett** [comment]
Completed File drop - I think this is working as expected
Completed Header - I think this is working as expected
Completed wizard - Issue https://github.com/IBM/carbon-addons-iot-react/issues/468

**Comment by amymillett** [comment]
Completed ResourceList - I think this is working as expected
Completed SideNav - Issue https://github.com/IBM/carbon-addons-iot-react/issues/472

**Comment by davidicus** [comment]
> Just met with Amy to divvy up the work. Adding a checklist so we can track what we've completed.
> We assume that we don't need to do the Carbon components. @davidicus correct?
> 
> * [x]  Add card
> * [x]  Base modal
> * [x]  ButtonEnhanced
> * [x]  FileDrop
> * [x]  Header
> * [x]  WizardInline
> * [x]  NavigationBar
> * [x]  PageHero
> * [x]  ProgressIndicator
> * [x]  ResourceList
> * [x]  SideNav
> * [x]  SimplePagination
> * [x]  StructuredList
> * [x]  TAble
> * [x]  TableBodyRow
> * [x]  TableDetailWizard
> * [x]  TilesCatalog
> * [x]  WizardModal

We do need to check off on the carbon components to be sure that they are compliant.

**Comment by davidicus** [comment]
> Question about the text in general - It doesn't actually flip the order of the characters or the words to read from right to left, but it does flip the order of sentence and punctuation. Is that as expected?

That is as expected.

**Comment by KarenGski** [comment]
> > Just met with Amy to divvy up the work. Adding a checklist so we can track what we've completed.
> > We assume that we don't need to do the Carbon components. @davidicus correct?
> 
> We do need to check off on the carbon components to be sure that they are compliant.

Oops.  So they haven't tested them?

**Comment by davidicus** [comment]
@KarenGski They say that they should all be compliant but I think we have seen enough defects to expect that there may be some gaps.

**Comment by davidicus** [comment]
keeping open to track bugs referenced above. Need to add them to this epic

**Comment by tay1orjones** [comment]
Closing this epic in favor of tracking items individually. RTL support/issues as a whole for the repo can be viewed by sorting the issues with the RTL label
