### ISSUE TITLE
Update to Carbon v10.4

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#436]
Update our Carbon dep to latest

**Comment by tay1orjones** [comment]
In progress

**Comment by tay1orjones** [comment]
Documentation for this upgrade could include a link to the direct diff.
https://github.com/carbon-design-system/carbon/compare/v10.3.1...v10.4.1

Also a link to the release notes of all versions we've jumped
https://github.com/carbon-design-system/carbon/releases/tag/v10.4.0
and
https://github.com/carbon-design-system/carbon/releases/tag/v10.4.1
also 
https://github.com/carbon-design-system/carbon/releases/tag/v10.3.2

**Comment by tay1orjones** [comment]
Closed via #465
