### ISSUE TITLE
[Table] - Selected state should change row color

### ISSUE THREAD

**Issue by amymillett** [IBM/carbon-addons-iot-react#443]
Looks like the Carbon X version of the IoT table is missing some row styling when a checkbox is selected. Here's what's in our beta repo:

![Screen Shot 2019-08-05 at 2 45 52 PM](https://user-images.githubusercontent.com/48336859/62490803-da2b7c00-b78f-11e9-973f-20334cccb25b.png)

And here's the Carbon version:

![Screen Shot 2019-08-05 at 2 47 18 PM](https://user-images.githubusercontent.com/48336859/62490840-faf3d180-b78f-11e9-9fb9-7cfbd50f3e12.png)

**Comment by davidicus** [comment]
defect no longer present. Closing issue.
