### ISSUE TITLE
RTL: BaseModal: Text overlaps "x" button, right aligns with no margin

### ISSUE THREAD

**Issue by KarenGski** [IBM/carbon-addons-iot-react#444]
- The text right-aligns with the edge of the dialog with no margin

- The top line of text overlaps the "x" close button 
   - Is the close button supposed to switch sides as well? Because that would potentially solve the overlap problem.
- Too much padding between right edge of button and text (isn't that much in LTR)
<img width="531" alt="image" src="https://user-images.githubusercontent.com/51330315/62492754-7445f100-b79d-11e9-9dce-b529e46f2d33.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/51330315/62553529-824b4e80-b83d-11e9-996d-b36335ec89ac.png">

<img width="810" alt="image" src="https://user-images.githubusercontent.com/51330315/62492776-7f008600-b79d-11e9-860c-23098f1b9286.png">

 you get the idea..

**Comment by davidicus** [comment]
this bug has been fixed upstream from carbon
