### ISSUE TITLE
RTL: Table: Lack of right alignment and other issues

### ISSUE THREAD

**Issue by KarenGski** [IBM/carbon-addons-iot-react#446]
**Columns**
- Column content doesn't right-align
- Date header doesn't right-align, but others do
<img width="972" alt="image" src="https://user-images.githubusercontent.com/51330315/62493762-ea4b5780-b79f-11e9-882d-f72f5e0be88c.png">

**Search**
- Icon doesn't switch to right of text entry
![image](https://user-images.githubusercontent.com/51330315/62494593-e6203980-b7a1-11e9-8536-11b692026ca9.png)

**Column controls**
Text in column elements doesn't right-align
![image](https://user-images.githubusercontent.com/51330315/62544188-545e0e00-b82d-11e9-816f-3be1b93e039d.png)

**Filters**
Dropdown option menu doesn't right-align
![image](https://user-images.githubusercontent.com/51330315/62543160-49a27980-b82b-11e9-8c99-26142d9766d6.png)

**Expanding rows**
- Content in expanded row doesn't right-align
- Labels don't shift to the right of values
![image](https://user-images.githubusercontent.com/51330315/62494222-f388f400-b7a0-11e9-9336-0f2e3349bce6.png)

**Overflow menu**
- No padding btw text and icon
![image](https://user-images.githubusercontent.com/51330315/62494301-28954680-b7a1-11e9-83f6-2893072793f1.png)

**Multi-select**
- Actions don't move to left, items selected doesn't move to right (in the table toolbar, those things do switch)
- Divider line btw Cancel and other actions disappears

![image](https://user-images.githubusercontent.com/51330315/62494962-aa39a400-b7a2-11e9-8e93-56e3b7dd4ad7.png)

**Page control**
- Items per page element doesn't right-align and overlaps with other elements
- Divider lines aren't in the right place
- Next / Back arrows point wrong way
![image](https://user-images.githubusercontent.com/51330315/62493951-53cb6600-b7a0-11e9-98b8-4ab465a7153e.png)

**Dumb table & minitable**
Content and headers don't right align
![image](https://user-images.githubusercontent.com/51330315/62494647-fcc69080-b7a1-11e9-923f-4b89880e2406.png)

**Nested table rows**
- Indent in nested rows offsets to the right, should indent to the left
![image](https://user-images.githubusercontent.com/51330315/62543266-95edb980-b82b-11e9-9580-70145be9f106.png)

**No data & custom empty state**
- "no data" texts aligns left, not right
![image](https://user-images.githubusercontent.com/51330315/62543361-ccc3cf80-b82b-11e9-808d-44b7f6f0a7fd.png)

**Horizontal scroll - full width**
- the end of the right-most column can't be horizontally scrolled to, which means you'll lose pieces of primary information when they are right-aligned.  The reader will lost the beginning of everything. (this is actually a problem in LTR as well. submitted as issue #448)
![image](https://user-images.githubusercontent.com/51330315/62543696-68edd680-b82c-11e9-9c71-63e89e18abef.png)

**Comment by davidicus** [comment]
- [x] Column content doesn't right-align
- [x] Date header doesn't right-align, but others do

**Comment by davidicus** [comment]
> **Columns**
> 
> - [x] Column content doesn't right-align
> - [x] Date header doesn't right-align, but others do
> 
> <img alt="image" width="972" src="https://user-images.githubusercontent.com/51330315/62493762-ea4b5780-b79f-11e9-882d-f72f5e0be88c.png">
> 
> **Search**
> 
>  - [x] Icon doesn't switch to right of text entry
>   ![image](https://user-images.githubusercontent.com/51330315/62494593-e6203980-b7a1-11e9-8536-11b692026ca9.png)
> 
> **Column controls**
> - [x]Text in column elements doesn't right-align
> ![image](https://user-images.githubusercontent.com/51330315/62544188-545e0e00-b82d-11e9-816f-3be1b93e039d.png)
> 
> **Filters**
> - [x] Dropdown option menu doesn't right-align
> ![image](https://user-images.githubusercontent.com/51330315/62543160-49a27980-b82b-11e9-8c99-26142d9766d6.png)
> 
> **Expanding rows**
> 
>  - [x] Content in expanded row doesn't right-align
> * ~Labels don't shift to the right of values~ - this is user provided content
>   ![image](https://user-images.githubusercontent.com/51330315/62494222-f388f400-b7a0-11e9-9336-0f2e3349bce6.png)
> 
> **Overflow menu**
> 
> - [x] No padding btw text and icon
>   ![image](https://user-images.githubusercontent.com/51330315/62494301-28954680-b7a1-11e9-83f6-2893072793f1.png)
> 
> **Multi-select**
> 
> - [x] Actions don't move to left, items selected doesn't move to right (in the table toolbar, those things do switch)
> - [x] Divider line btw Cancel and other actions disappears
> 
> ![image](https://user-images.githubusercontent.com/51330315/62494962-aa39a400-b7a2-11e9-8e93-56e3b7dd4ad7.png)
> 
> **Page control**
> 
> - [x] Items per page element doesn't right-align and overlaps with other elements
> - [x] Divider lines aren't in the right place
> - [x] Next / Back arrows point wrong way
>   ![image](https://user-images.githubusercontent.com/51330315/62493951-53cb6600-b7a0-11e9-98b8-4ab465a7153e.png)
> 
> **Dumb table & minitable**
> ~Content and headers don't right align~ - resolved in other PR
> ![image](https://user-images.githubusercontent.com/51330315/62494647-fcc69080-b7a1-11e9-923f-4b89880e2406.png)
> 
> **Nested table rows**
> 
> - [x] Indent in nested rows offsets to the right, should indent to the left
>   ![image](https://user-images.githubusercontent.com/51330315/62543266-95edb980-b82b-11e9-9580-70145be9f106.png)
> 
> **No data & custom empty state**
> 
> * ~"no data" texts aligns left, not right~ - this design has changed and defect is no longer present
>   ![image](https://user-images.githubusercontent.com/51330315/62543361-ccc3cf80-b82b-11e9-808d-44b7f6f0a7fd.png)
> 
> **Horizontal scroll - full width**
> 
> *~ the end of the right-most column can't be horizontally scrolled to, which means you'll lose pieces of primary information when they are right-aligned.  The reader will lost the beginning of everything. (this is actually a problem in LTR as well. submitted as issue #448)~ - resolved in other PR
>   ![image](https://user-images.githubusercontent.com/51330315/62543696-68edd680-b82c-11e9-9c71-63e89e18abef.png)
