### ISSUE TITLE
Sorting and Filtering issue with Stateful table

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#447]
In the Stateful table when the data is not available for a cell I am displaying some custom elements like in the screen shot ("Not available"/ "Not configured"/ N/A”) instead of just leaving it blank using renderDataFunction. 
The issue what I notice is that the filtering  and sorting aren’t working properly.

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/22093326/62512306-1d8bf600-b835-11e9-9bae-0429fe9845b5.png">

For instance, if I enter a value in the filter which is not matching with any of the column data then also it shows the "Not available".

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/22093326/62512690-a9eae880-b836-11e9-8b0d-78986e11a400.png">

Sorting also doesn't work properly.
Below is the default view

![image](https://user-images.githubusercontent.com/22093326/62513120-61ccc580-b838-11e9-93ed-224eba8a2db1.png)

On click to sort ascending it comes like below

![image](https://user-images.githubusercontent.com/22093326/62513160-96408180-b838-11e9-91d9-d7ff89799201.png)

On descending sort:

![image](https://user-images.githubusercontent.com/22093326/62513219-d6076900-b838-11e9-82cb-e49c317cb13a.png)

I am using  "carbon-addons-iot-react": "1.53.1"

Thanks,
Kalyani Raut

**Comment by scottdickerson** [comment]
you can now pass custom sort and filter functions for each table column and implement yourself

**Comment by scottdickerson** [comment]
this is fixed now, let me know if you have any issues
