### ISSUE TITLE
Table component: horizontal scroll - full width does not display left-most content

### ISSUE THREAD

**Issue by KarenGski** [IBM/carbon-addons-iot-react#448]
In horizontal scroll - full width, if you reduce the width of your browser, you cannot see the left-most content (or right-most with RTL) even when you scroll.

https://beta.carbon-addons-iot-react.com/?path=/story/watson-iot-table--horizontal-scroll-full-width

![image](https://user-images.githubusercontent.com/51330315/62543951-dd287a00-b82c-11e9-9bef-4f1c27758531.png)

I would assume, as user, that:
1) I could always scroll to see the full set of table content
2) It would default to being scrolled all the way left (or all the way right in RTL).

**Comment by davidicus** [comment]
@KarenGski Does this defect still exist. Looking at the updated link https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--horizontal-scroll-full-width I do not see any content cutting off. Can you verify and let me know if we can close this issue?

**Comment by davidicus** [comment]
This issue is no longer present. Closing
