### ISSUE TITLE
RTL: TileCatalog: Various

### ISSUE THREAD

**Issue by KarenGski** [IBM/carbon-addons-iot-react#451]
- Page arrows point wrong way
- Not sure if this is a problem or not, but the multi-select channel stays on the right side of the card instead of shifting to the left side

![image](https://user-images.githubusercontent.com/51330315/62552946-7a3edf00-b83c-11e9-98ce-33b11be594ad.png)

- Search icon moves to left align in the element.  doesn't move in LTR
![image](https://user-images.githubusercontent.com/51330315/62553051-ace8d780-b83c-11e9-8773-2e25cb61de2c.png)
![image](https://user-images.githubusercontent.com/51330315/62552989-8fb40900-b83c-11e9-8888-daefb0779202.png)

**Comment by davidicus** [comment]
still valid
