### ISSUE TITLE
RTL: Wizard

### ISSUE THREAD

**Issue by amymillett** [IBM/carbon-addons-iot-react#468]
![Screen Shot 2019-08-08 at 10 27 51 AM](https://user-images.githubusercontent.com/48336859/62716037-33312500-b9c7-11e9-855c-65e0c9e1c104.png)

![Screen Shot 2019-08-08 at 10 32 50 AM](https://user-images.githubusercontent.com/48336859/62716535-eb5ecd80-b9c7-11e9-9171-4be7a1d709ba.png)

Somewhat similar to this issue: https://github.com/IBM/carbon-addons-iot-react/issues/444

- Can we move the close button to the other side, like with the error message in the second screenshot? The main title does not line up with the rest of the copy.
- Missing the padding between the step circles and the accompanying text (see https://github.com/IBM/carbon-addons-iot-react/issues/471 for progress indicator issue)

**Comment by davidicus** [comment]
This component is deprecated. closing
