### ISSUE TITLE
RTL: Navigation bar buttons don't move

### ISSUE THREAD

**Issue by amymillett** [IBM/carbon-addons-iot-react#469]
![Screen Shot 2019-08-08 at 10 38 55 AM](https://user-images.githubusercontent.com/48336859/62717057-ce76ca00-b9c8-11e9-9872-e596907d779e.png)

- The normal version of this is fine in RTL, but "with actions" and "example with work area" look weird in RTL because the buttons don't move to the other side of the screen. It ends up covering the tabs.
- It also seems like the "right content" needs to be aligned to the left in RTL

**Comment by davidicus** [comment]
this issue is stale and I think this component is deprecated. Closing but please reopen if necessary
