### ISSUE TITLE
[Table]: validate the server-side paging works with filter/sort

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#47]
We think this is a test only statement to make sure this works..

**Comment by scottdickerson** [comment]
Outcome of this will be a sample story showing how to handle the server side paging with sort and filtration

**Comment by scottdickerson** [comment]
would be good to perhaps provide an escape hatch in the reducers to manage server-side data management.

**Comment by scottdickerson** [comment]
we need a story example of this in our common repo to preclude questions

**Comment by tomklapiscak** [comment]
FYI: Progress so far in https://github.com/IBM/carbon-addons-iot-react/tree/AsyncTableStory (See new `AsyncTable` component)

So far:
 - pagination
 - filtering

Todo:
  - quicksearch (should this be an in-memory search against filtered results, or implemented as an additional parameter to the (Mock) HTTP endpoint?)
  - sorting
