### ISSUE TITLE
RTL: PageHero alignment issues

### ISSUE THREAD

**Issue by amymillett** [IBM/carbon-addons-iot-react#470]
![Screen Shot 2019-08-08 at 11 01 11 AM](https://user-images.githubusercontent.com/48336859/62718659-df750a80-b9cb-11e9-9e38-065df5af9d0e.png)

- Generally working as expected, but the "right content" should be aligned to the left in RTL
- Also, I'm not sure if the "has breadcrumb" version is working or not. Nothing happens when I do the RTL toggle, but maybe that's a limitation of the container?

**Comment by davidicus** [comment]
component has been deprecated in favor of `PageTitleBar`
