### ISSUE TITLE
[ProgressIndicator] Horizontal line is not continuous at large stepWidths

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#476]
At a stepWidth of 8, this looks correct:
![image](https://user-images.githubusercontent.com/3360588/62728131-98454480-b9e0-11e9-9570-6fedfba80eae.png)

Anything >8 causes the horizontal line to have breaks inbetween:
![image](https://user-images.githubusercontent.com/3360588/62728146-a5623380-b9e0-11e9-9100-cd1affef7dc7.png)

I believe this should always be continuous/non-breaking.

**Comment by tay1orjones** [comment]
[Internal Watson-IoT/pal-tracking#389](https://github.ibm.com/Watson-IoT/pal-tracking/issues/389)

**Comment by davidicus** [comment]
closed via https://github.com/IBM/carbon-addons-iot-react/pull/1119
