### ISSUE TITLE
[SimplePagination] Incorrect background color

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#477]
![image](https://user-images.githubusercontent.com/3360588/62728269-fb36db80-b9e0-11e9-93dd-035bee4d1eb2.png)

This background should be white, as it is on the primary pagination component. I suspect we're not using a theme variable for this, which is why it didn't change from the v9-v10 upgrade.

**Comment by sstone2423** [comment]
FYI: Carbon v10 actually has a gray background
<img width="856" alt="Screen Shot 2020-01-28 at 11 05 00 PM" src="https://user-images.githubusercontent.com/25177649/73329716-45787700-4224-11ea-864d-c7e4e4d53777.png">

**Comment by tay1orjones** [comment]
For the standard Carbon theme `$ui-01` is gray. For the Carbon Gray10 theme that we use, `$ui-01` is white.
