### ISSUE TITLE
[TableDetailWizard] Progress Indicator bottom padding/spacing

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#478]
Progress indicator used in this component runs down into the buttons. Needs some spacing.

![image](https://user-images.githubusercontent.com/3360588/62728460-7ef0c800-b9e1-11e9-9b7f-fdc658c74b7f.png)

v9 version for quasai-reference
![image](https://user-images.githubusercontent.com/3360588/62728533-ae073980-b9e1-11e9-9e93-49f67272a091.png)

**Comment by davidicus** [comment]
This defect is no longer visible in storybook. https://carbon-addons-iot-react.com/?path=/story/watson-iot-tabledetailwizard--static
