### ISSUE TITLE
Carbon partials not resolving

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#505]
In v2 we are exporting the carbon-component partials as a means to limit the amount of dependencies. Due to how they are importing other partials inside the ones we export there are some resolution issues which break the build. 

We need to either add the `carbon-components` package as a peer dependency or we need to figure a way to resolve this web of imports. 

![image](https://user-images.githubusercontent.com/1590966/63365592-ec87e700-c345-11e9-8496-5b76113c935e.png)

![image](https://user-images.githubusercontent.com/1590966/63365616-fad60300-c345-11e9-9e17-576488313a69.png)

![image](https://user-images.githubusercontent.com/1590966/63365641-032e3e00-c346-11e9-9589-9243bf81fbf8.png)

**Comment by davidicus** [comment]
Reopening due to further resolution errors down the line

**Comment by tay1orjones** [comment]
Further work on this in #533 
Closing.
