### ISSUE TITLE
[Hero] [PageHero] Deprecate/remove PageHero in favor of Hero

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#507]
It appears that `PageHero` should have been deprecated and removed when `Hero` was created.

`Hero` was added during the v2 beta phase, we resolved to keep `PageHero` instead of `Hero`, which was incorrect. In following semantic versioning, removing `PageHero` would be a non-backwards-compatible change, resulting in a new major version. In light of this, I think we should keep the `PageHero` export for now, but place deprecation notice on it/remove it from the storybook.

- [x] Add `Hero` component from `1.x` branch
- [x] Add `Hero` to storybook
- [x] Add deprecation notice to `PageHero` (but still export)
- [x] Remove `PageHero` from storybook
- [ ] Align `Hero` to newly established pattern from design

**Comment by scottdickerson** [comment]
In the 1.x branch, we also deprecated the PageHeader in favor of the Hero for consistency
