### ISSUE TITLE
Improve sass linting for Carbon vars, mixins, etc

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#527]
Our sass linting through `stylelint` can be improved.

I'd like to see us linting for values that should be Carbon variables.
- font-family/size/etc should use Carbon [productive typography @includes and variables](https://www.carbondesignsystem.com/guidelines/typography/productive)
- margin/padding/left/right/bottom/top should use [Carbon spacing values](https://www.carbondesignsystem.com/guidelines/spacing#spacing-scale). Spacing values should typically be used since we're building individual components, but Layout scale might apply as well. Either way it shouldn't ever be a px or rem value
- Colors should all use Carbon variables, no hex, rgba, etc
- Motion `ms`/`s` etc should use the motion package
- All of the above should be an error-level severity as to prevent these from entering the build

There's likely more we could do here. General goal should be to enforce using Carbon tokens in our system. Ideally no custom values at all in our codebase.

Stylelint supports [custom messages for rules](https://stylelint.io/user-guide/configuration#custom-messages), which we should use here to suggest the proper remedy, perhaps with a link to Carbon documentation.

We can use [declaration-property-unit-blacklist](https://github.com/stylelint/stylelint/blob/master/lib/rules/declaration-property-unit-blacklist/README.md) for many of these, though it [doesn't support multiple custom messages](https://github.com/stylelint/stylelint/issues/4117) at this time. We'd have to write our own custom formatter, which is a decent hunk of work.

**Comment by davidicus** [comment]
this is still a valid issue. Not stale.
