### ISSUE TITLE
Link component is not working in Tooltip when used inside Modal.

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#568]
Hi Team,
I have used Tooltip component inside Modal. Inside the tooltip component I have used Link component, so that when you click on it another website opens.
Issue is on-click event in the link is not working when it is in a Modal.
I am able to replicate this issue in the codesandbox. Below is the link for your reference.
https://codesandbox.io/s/carbon-iot-react-header-ewydu
I am using carbon-addons-iot-react version 2.3.2

<img width="588" alt="image" src="https://user-images.githubusercontent.com/22093326/65751795-17294480-e129-11e9-913e-26a7cfc19aa3.png">

**Comment by kalyanixraut** [comment]
Hi Team,

Please provide an update and ETA for the fix.

**Comment by tay1orjones** [comment]
Hi @kalyanixraut, this is actually intended behavior. Modals by default trap focus, [see Carbon source code](https://github.com/carbon-design-system/carbon/blob/32c76bbd1947825812690d703ae6954f4f01f873/packages/react/src/components/Modal/Modal.js#L127-L131)

Links will work if you set `focusTrap={false}` on the Modal.

See [this Carbon issue](https://github.com/carbon-design-system/carbon/issues/3021) for additional context.
