### ISSUE TITLE
Component Request - Expose standard Carbon Data Table

### ISSUE THREAD

**Issue by daphoenix** [IBM/carbon-addons-iot-react#571]
# Component Details
Expose the Carbon Design System DataTable in the iot add-ons.

## Detailed description
The **TRIRIGA Building Insights** team has built a custom component on top of the Carbon Design system table and need it exposed for **Dec 2019** release. Otherwise we'd have to import just for that one commented out component.

## You will consider this component complete when...

- [ ] It's exposed in the add-ons package. 
> update carbon-addons-iot-react/src/index.js to expose Carbon Design System DataTable.

**Comment by tay1orjones** [comment]
What are the gaps that prevent your team from using your custom component with the current Table/StatefulTable? Is it something we could help align on so we could prevent exporting two sets of tables?

**Comment by creckling** [comment]
what is happening with this one?

**Comment by daphoenix** [comment]
The gap is that the current custom component is implemented on the default V9 table and we only need the Carbon 10 table exposed, otherwise we'd have to side load carbon 10 just for the table. Adopting the add-ons datatable would require unplanned work of extending the add-ons table and add inline editing which would impact our release Nov 2019 release date.

**Comment by davidicus** [comment]
all components are now V10 so this issue is stale and no longer applicable
