### ISSUE TITLE
[Table] Support column alignment (start, center, end)

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-addons-iot-react#574]
In the IoT table today, all column data is left aligned and there is no way to right align content in a data row.

We should add an alignment configuration to the table cols so that we can set the alignment of the column data to be `start`, `center`, or `end` (which is left, center, right in LTR environment and right, center, left in a RTL environment)

This is a requirement when displaying certain kinds of content, such as currency which should always be end aligned (right aligned in LTR).

**Comment by davidicus** [comment]
@lukefirth @JordanWSmith15  can you confirm if this is part of our Pattern spec for tables?

**Comment by JordanWSmith15** [comment]
@davidicus Not sure if it was or wasn't. @KarenGski has it in her designs though, so we are going to have Sunil and the new team joining the IoT repo do this work.

**Comment by davidicus** [comment]
Thanks @JordanWSmith15. @KarenGski can you link to the design spec that outlines this behavior?

**Comment by lukefirth** [comment]
This in general makes sense to me. Only note here is that it feels like if Carbon don't already support it, we should be super sure to plug this back into them as it seems like a highly generic capability that I'm surprised they don't already have.

**Comment by JordanWSmith15** [comment]
@davidicus @stuckless @KarenGski  I don't have a spec. Off the top of my head, I'd say we'd want to programmatically detect whether the data being displayed makes sense to display right-aligned. I'm not knowledgeable in what those rules would be, or how they would be effected by localization and RTL.

**Comment by stuckless** [comment]
@lukefirth Carbon's table does not support column alignment, and likely whatever is done here is not something that would make it's way back to carbon.  At this point I would not even conside the the IoT table to be an extension of Carbon's table, but rather it's a new independent version.   The data model is different, the column model is different, the only similarities is that they both share some atomic level components.

@JordanWSmith15 For this enhancement we only need the ability to control the alignment of content by manually setting the alignment on a column configuration.  This table doesn't know anything about data types and as such things like programatically detecting the data and controlling the alignment is not part of this feature in the IoT table.   Graphite that does extend this table and also knows about data types will autotically set the column alignment.  I just want to be clear that in this repo, we are only doing the work of providing a way to control alignment, manually vis some configuration property.
