### ISSUE TITLE
[Header]: Support switching left-hand navigation between modes with different navigation areas.

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#58]
The maximo team has a usecase where the navigation area switches between modes (carbon's SideNavDetails & SideNavSwitcher)

![image](https://user-images.githubusercontent.com/1590966/58483378-30e05e00-812e-11e9-9161-33174a4ce64f.png)

**Comment by davidicus** [comment]
Spec is outlined here:

https://ibm.invisionapp.com/share/SNNZ29ZAY6V#/screens/319167299
and
https://ibm.invisionapp.com/share/D6NZ4C0PUN9#/screens/319188836_Navigation_Panel_-_Usage

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open once discussion with design team is complete.
