### ISSUE TITLE
Table i18n Issues

### ISSUE THREAD

**Issue by leetosc** [IBM/carbon-addons-iot-react#590]
Allow translated strings to be passed into Table, in particular the text for "1 item selected" and "Cancel".

![image](https://user-images.githubusercontent.com/13279967/66220693-147f9f80-e693-11e9-918f-2066b9bfbd37.png)

----
The following are all in the 1.xx version which is used in ui-dashboard

"item selected" and "Cancel" in Table batch actions
https://github.ibm.com/wiotp-webui/ui-dashboard/issues/1236

"Filter table" tooltip
https://github.ibm.com/wiotp-webui/ui-dashboard/issues/1246

~"Dragable column" tooltip~
~https://github.ibm.com/wiotp-webui/ui-dashboard/issues/1247~

Table column tooltips
https://github.ibm.com/wiotp-webui/ui-dashboard/issues/1260

**Comment by tay1orjones** [comment]
- For `Filter table` we need to implement [these strings](https://github.com/carbon-design-system/carbon/blob/a39084f26a5a1ed3093858cf6654898a84a1dff9/packages/react/src/components/DataTable/TableToolbarSearch.js#L18-L21) in the same way as the above PR #603
- For Table column tooltips, [these are the strings](https://github.com/carbon-design-system/carbon/blob/53385e764ab34818951751909d37e67801c5f944/packages/react/src/components/DataTable/TableHeader.js#L24-L42) we need to link up to the i18n prop object

**Comment by leetosc** [comment]
It looks like the i18n strings did not make it into the TableToolbar.  Hovering over the arrows to sort a column by ascending/descending still shows default English

**Comment by davidicus** [comment]
@leetosc I am actually not able to get any hovering title with the sort arrows. Looking at Carbon's `TableHeader` [component](https://github.com/carbon-design-system/carbon/blob/f3727137f984fa09052e0ff0de69af62121845b8/packages/react/src/components/DataTable/TableHeader.js#L82) it doesn't seem like they provide a hover title. The only hover I am able to get is from the header title which is a user provided string that should be translated.

**Comment by davidicus** [comment]
Figured out the issue and will submit a PR to close
