### ISSUE TITLE
Write up requirement docs for issues

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#593]
Documentation is needed to outline the necessary requirements an issue must meet before it is considered "ready to implement"

Additionally issue templates need to be created and existing ones updated to include questions about upcoming deadlines, priority, and resource availability to accomplish (following Carbon's example).

Considered done when:
- [x] There are issue templates for bugs and feature request and all templates follow the Carbon example outlined above.
- [x] We have documentation in our wiki/README about the items required for each issue in order to be ready to implement by a developer.

**Comment by tay1orjones** [comment]
[`CONTRIBUTING.md` contains info on required items to consider an item 'ready to implement'](https://github.com/IBM/carbon-addons-iot-react/blob/master/.github/CONTRIBUTING.MD#for-all-new-components-and-features)

The above PR, #614, updates issue templates as well as the PR template.
