### ISSUE TITLE
Increase test coverage for Dashboard components

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#621]
Dashboard components in master branch need to have adequate test coverage and we need to fix any outstanding console warnings/ errors. 

Related to #306

**Comment by tay1orjones** [comment]
It seems to close this can just verify the test coverage percents and thresholds, ensure that they're at the same spot they were before the dashboard components were brought in.

**Comment by tay1orjones** [comment]
Coverage threshold [was 80% for all 4 categories](https://github.com/IBM/carbon-addons-iot-react/blame/144170dae5dd7a27453cfbe6afd65bd289114393/jest.config.js#L7-L14) before the dashboard migration into 2.x.

Currently, it's set lower than that:
https://github.com/IBM/carbon-addons-iot-react/blob/43844aabfdec277f18fc5e1716673327e9490f80/jest.config.js#L6-L13

_*Although*_, current coverage in `master` is
```
84.72% Statements 
73.28% Branches 
80.48% Functions 
84.71% Lines
```

The only deficit is ~7% coverage on branches. The components with the lowest covered branches (biggest room for improvement) are `PageWizard`, `ImageCard`, and `AsyncTable`

We could raise the other three category thresholds back to 80%, and bump `branches` up to 73%, with aim to raise it as PageWizard stabilizes/improves. The other currently open PRs shouldn't decrease these coverage numbers.
