### ISSUE TITLE
[TableCard] The Download icon is blue and doesn't match the color of the other icons

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#642]
![image](https://user-images.githubusercontent.com/6663002/67601182-5acb9a00-f739-11e9-89b8-932745328159.png)

Shouldn't be blue

Related PAL issue: https://github.ibm.com/Watson-IoT/pal-tracking/issues/64

**Comment by amymillett** [comment]
Icons should have 16px padding between them and should be the icon-01 color (#161616)

**Comment by amymillett** [comment]
There's also something weird going on with that calendar icon... not sure if it's just the color or if something is off on the sizing.
