### ISSUE TITLE
[Card]: The top action card icons are too small to be tappable and don't align with the table icons

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#643]
<sub>[Internal tracking issue #84](https://github.ibm.com/Watson-IoT/pal-tracking/issues/84)</sub>

See in the screenshot below, the top icons don't align
![image](https://user-images.githubusercontent.com/6663002/67601231-7898ff00-f739-11e9-8486-edb2e191c21c.png)

**Comment by davidicus** [comment]
@amymillett can you take a quick look at the icons here and advise ASAP?

**Comment by amymillett** [comment]
(I also just posted this in a related Monitoring dashboard issue...)

I think what we would like to do is have all the actions icons flattened into one line on the right side of the card. This would eliminate a lot of the extra space and keep all the icons lined up. Icons should have 16px padding between them and should be the icon-01 color (#161616)

<img width="1478" alt="Screen Shot 2019-11-06 at 12 55 58 PM" src="https://user-images.githubusercontent.com/48336859/68607666-c2dae980-0476-11ea-8948-fd18961858be.png">

![Screen Shot 2019-11-11 at 11 28 53 AM](https://user-images.githubusercontent.com/48336859/68607709-e6059900-0476-11ea-98cd-41bf924ea12b.png)

**Comment by tay1orjones** [comment]
The `availableActions` are [currently hardcoded](https://github.com/IBM/carbon-addons-iot-react/blob/526ef4027dd0624e9846e9888945ba44870c52c2/src/components/TableCard/TableCard.jsx#L670). As we consolidate these actions into one spot, we should make this configurable.

**Comment by davidicus** [comment]
closed by this [PR](https://github.com/IBM/carbon-addons-iot-react/pull/821)
