### ISSUE TITLE
[ImageCard] expand/collapse preview doesn't always match shown area

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#648]
### Describe the bug

In certain cases the preview does not match the current area of the image being shown.

### To Reproduce

Expand the image
zoom in on the image
collapse the image
the preview in the left bottom corner doesn't reflect the currently shown area

Visible in both prod and v1 storybook currently.

### Expected behavior

Preview shows the correct area after expand/collapse.

### Environment/versions:

- OS: MacOS
- Browser: chrome and firefox
- `carbon-addons-iot-react` version: `2.10.1` as well as v1.x stream, `1.98.7`

### Additional context

![image](https://user-images.githubusercontent.com/3360588/67597634-45527200-f731-11e9-9eb5-48aa1731202b.png)

**Comment by davidicus** [comment]
closed due to new functionality from this [PR](https://github.com/IBM/carbon-addons-iot-react/pull/812)
