### ISSUE TITLE
Side Nav component: Active tab issue

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#661]
### Describe the bug
In the storybook for side nav component https://carbon-addons-iot-react.com/?path=/story/watson-iot-sidenav--sidenav-component
be default Members tab is dispalyed as active.
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/22093326/67919308-d740fb80-fbc5-11e9-9f6c-a9dd8b93a7e5.png">

When I click on any other item on the side nav bar the default Members tab still shown as active instead showing only the newly selected one as active.
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/22093326/67919529-c2189c80-fbc6-11e9-96c9-283ae6190d8c.png">

**Comment by tay1orjones** [comment]
The `SideNav` story is a single visual state of the component. It does not include a stateful function enabling the change of visual selection state. This would be implemented at the product level. 

Typically, unless a stateful function/wrapper is exported for a component, the stories for that component do not include a stateful example.
