### ISSUE TITLE
Tooltip no icon - on hover

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#662]
### Summary
Hi, I am from TRIRIGA Building Insights development team.
As per our design requirement we need to show tooltip when user mouse hovers on the text. 
The Tooltip no icon(https://carbon-addons-iot-react.com/?path=/story/tooltip--no-icon) works only on-click on the text, is there a way that it can work with on-hover as well?

Design requirement:
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/22093326/67919789-cf825680-fbc7-11e9-9b23-c24603300ffd.png">

We find that TooltipDefinition (https://carbon-addons-iot-react.com/?path=/story/tooltipdefinition--default) works on hover, but implementing it brings an unwanted dotted underline to the text. Hence doesn't fully match our design req.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/22093326/67919858-1a03d300-fbc8-11e9-8f6e-637f865d0d39.png">

### Specific timeline issues / requests

We need the similar component as tooltipdefinition component, which should have styles modified  to get rid of dotted underline so that it matches our design requirements.
This component will be used in multiple place in UI for our current release which is scheduled for Jan 2020.

**Comment by tay1orjones** [comment]
>is there a way that it can work with on-hover as well?

The short answer is no. This was a conscious decision from the Carbon team as there are a11y implications for interactive tooltips to be displayed on focus/click instead of hover. 

[Discussion on the Carbon repo](https://github.com/carbon-design-system/carbon/pull/3633#issuecomment-517703727):

> _"interactive tooltips - because these contain interactive elements and/or rich text, we can't solely rely the `aria-describedby` attribute and we have to treat the tooltip as a `dialog`. Dialogs have different behaviors and we have to be able to focus on the tooltip itself or an interactive element within it. The general practice with this is then to have it show up on click (`focus` + `space/enter`) so that it's clear to users the tooltip is persistent and can be interacted with. "_
>
> (otherwise,) _"...the experience is more confusing and/or frustrating for screen reader users because as they focus on the trigger they are automatically moved to new content without being able to explicitly say 'yes i want to interact with the dialog' This could also throw off the flow of the page for them as they are forced to always be interrupted with content that is related but not necessarily part of the content they are currently navigating through."_

For the specific usage you link above, I would argue a definition tooltip be used. Without the underline, there is no affordance provided to denote the truncated text contains more/expanded information available as a tooltip.

cc @lukefirth
