### ISSUE TITLE
Search component with dynamic category filtering

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#665]
### Summary

Hi Team,

I am from TRIRIGA Building Insights development team, we have requirement for a new search component. More details on the expected functionality and visualization of this component is in the below invision link.

https://ibm.invisionapp.com/share/AWNZD4CM96H#/screens/319294636

**Additional context**
This new component is required for upcoming early Jan 2020 release.

### You will consider this component complete when...

- [ ] It's available as an export of this library
- [ ] Additional criteria you may have [e.g. Fully responsive, Accessible to WCAG 2.0, etc.]

**Comment by tay1orjones** [comment]
Hi @kalyanixraut 👋thanks for surfacing this request.

This would be a welcome contribution from your team if the design is documented and agreed-upon first by the PAL design team. Please work with your designers to propose this in an issue on the [internal `pal-tracking` repository](https://github.ibm.com/Watson-IoT/pal-tracking).

**Comment by daphoenix** [comment]
Navigating the hierarchy using search component from the [PAL - Invision](https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319242460) for Building Insights for [next release](https://ibm.invisionapp.com/share/AWNZD4CM96H#/319286147_3-01_-_Type_Search_Directly)

**Additional context**
Add any other context about the component here [e.g. screenshots, code, InVision prototype, Box notes containing details necessary for implementation]
Screenshot
![Screenshot 2019-11-07 at 04 04 34](https://user-images.githubusercontent.com/5711817/68357026-57121d00-0114-11ea-8c2f-5353dfdc8642.png)

**Comment by davidicus** [comment]
This item is stale. Closing but please feel free to reopen if necessary.
