### ISSUE TITLE
[Table]: Need an onclick handler for the table

### ISSUE THREAD

**Issue by tedlyons** [IBM/carbon-addons-iot-react#67]
## Title line template: [Title]: Brief description
Need an onclick handler for table.  We need to know when a row is clicked on (not just when its mark selected via the checkbox.

## Detailed description
The table should support onclick so that when a user clicks on a specific row we can take the appropriate action.

> What version of the Carbon Design System are you using?
    "carbon-components": "9.66.3",
    "carbon-components-react": "6.83.2",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
This is for the **Maximo Spark** project.

**Comment by scottdickerson** [comment]
whoops, thanks for catching @tedlyons!
