### ISSUE TITLE
[Table] In-line table editing, full table

### ISSUE THREAD

**Issue by KarenGski** [IBM/carbon-addons-iot-react#670]
PENDING - Will fill in details.  Creating as placeholder for now.

- Switching table to edit mode: https://github.ibm.com/Watson-IoT/pal-tracking/issues/20
- Data picker & Numeric spinner in cells: https://github.ibm.com/Watson-IoT/pal-tracking/issues/6
- Validation per cell change with error state indicator: https://github.ibm.com/Watson-IoT/pal-tracking/issues/32
- In Edit mode, show "Notes" button for adding notes to change log: https://github.ibm.com/Watson-IoT/pal-tracking/issues/43

**Comment by davidicus** [comment]
This item has been delivered. Closing.
