### ISSUE TITLE
[Table] Button to invoke "manage columns" dialog from Column config panel

### ISSUE THREAD

**Issue by KarenGski** [IBM/carbon-addons-iot-react#672]
### Summary
To support a top priority APM use case, the user needs the ability to modify the set of available columns in her table.  
To do so, she can click a button "Manage columns," which opens a dialog that allows her to control the available columns.

**Additional context**
See screenshots and link to designs here: https://github.ibm.com/Watson-IoT/pal-tracking/issues/16

This has not yet been incorporated into the PAL, but @lukefirth will be working on it concurrently.

### Specific timeline issues / requests

This is a blocker for a top priority item in the current APM release, due in Feb.

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?
@JordanWSmith15 has indicated that there are some HCL resources available for IoT work.  The AHI team (@zhengy90 as lead) might also have team members who can contribute directly to the IoT repo, but I'm not sure about assignments. 

_Carbon Add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by bryancboyd** [comment]
This enhancement will require development of a `<List>` component #706 for selection

![image](https://user-images.githubusercontent.com/2175647/69068619-b44a8000-09ea-11ea-8ef0-8b9a8b2fc625.png)

![image](https://user-images.githubusercontent.com/2175647/69068588-a98feb00-09ea-11ea-93c0-74368b0ee341.png)

![image](https://user-images.githubusercontent.com/2175647/69068642-bca2bb00-09ea-11ea-8c08-d5008a49d992.png)

**Comment by davidicus** [comment]
The abiliity to add a manage column button has been delivered.
