### ISSUE TITLE
[Table] Need ability to select / deselect available table columns

### ISSUE THREAD

**Issue by KarenGski** [IBM/carbon-addons-iot-react#673]
### Summary

User needs to be able to manage the available set of columns for the data table.  To do this, she can invoke a dialog from the column config panel, see all currently selected items pinned at the top of the list and the total number of selected items.  She can search for and select a new item and when she clears her search, that item will now appear pinned to the top as well.  

**Additional context**
Design proposal is logged here in the PAL tracking repo: https://github.ibm.com/Watson-IoT/pal-tracking/issues/15

The proposal has been reviewed with @lukefirth  and other PAL stakeholders and I believe it is approved but not yet incorporated.  Luke can verify.

This pattern applies whenever a user is managing a list of selected things from a list of available things.  It's used in at least 2 other places in the APM experience: managing simple filter and managing work queues.

Functions needed to support this:
- Search + single column table in dialog
- Hide table column header
- Show total # selected.
- Show currently selected columns pinned to top of list. 
- User can deselect selected item (& total updates)
- User can search for item in list, and list reduces to matching items
- User can select from reduced search list (& total updates)
- User can clear search and see refreshed set of pinned items
- User can Save changes to close the dialog and see updated available columns in open column panel
- All newly-added columns should be added to the end of the table in "show" mode.

### Specific timeline issues / requests

This is blocking a top priority APM story that is part of the current March release plan.

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?
@JordanWSmith15 has indicated that there are some HCL resources available for IoT work.  The AHI team (@zhengy90 as lead) might also have team members who can contribute directly to the IoT repo, but I'm not sure about assignments. 

_Carbon Add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by davidicus** [comment]
Functionality available.
