### ISSUE TITLE
[Table card] Dashboard table header heights issue

### ISSUE THREAD

**Issue by JordanWSmith15** [IBM/carbon-addons-iot-react#680]
### Describe the bug

Table card in Dasboard renders large column headers on Firefox for Mac. 

### To Reproduce

Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-dashboard--basic-dashboard on Firefox for Mac.
Screenshot:
![Screen Shot 2019-11-05 at 1 26 02 PM](https://user-images.githubusercontent.com/21066152/68234780-009bc600-ffd0-11e9-8274-7c1df58b46ac.png)

### Environment/versions:
Mac Firefox  70.0.1

**Comment by davidicus** [comment]
related to PR [#630](https://github.com/IBM/carbon-addons-iot-react/pull/630)

**Comment by enricoberti** [comment]
@davidicus you fixed this already, good to close? works fine on FF 73

![image](https://user-images.githubusercontent.com/751894/74357536-5b5b6f80-4dc0-11ea-8734-87a19e49d162.png)

**Comment by davidicus** [comment]
Closing
