### ISSUE TITLE
[Sidenav] Need Fixed expanded (open) state

### ISSUE THREAD

**Issue by daphoenix** [IBM/carbon-addons-iot-react#684]
### Summary
Building Insights development team needs the component to implement both 2 open states, documented in the [Watson IoT PAL](https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/components/ui-shell-side-nav/usage) -
* Flexible expanded (open) state - implemented in current component 
* Fixed expanded (open) state - still to be implemented.

**Additional context**
Continuing from https://github.com/IBM/carbon-addons-iot-react/issues/661.
* Current behaviour
1. Go to **Storybook link** - [SideNav Component](https://carbon-addons-iot-react.com/?path=/story/watson-iot-sidenav--sidenav-component).
2. Click on top-left hamburger menu.
3. Side menu opens in Flexible expanded (open) state as an overlay over the main content 

* Desired behaviour
4. Click on top-left hamburger menu.
5. Side menu changes to Fixed expanded (open) state and displaces the main content area to the right.

### Specific timeline issues / requests
Do you want this work within a specific time period? Is it related to an
upcoming release?
* Required by the end of November for next product release.

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources
What resources do you have to assist this effort? 
Possibly one member of the development team, depending on timelines.
_Carbon Add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

Same as this one internally in Maximo Asset Monitor:
https://github.ibm.com/wiotp/monitoring-dashboard/issues/785

**Comment by kalyanixraut** [comment]
### Specific timeline issues / requests ###

As we are starting with the implementation from next week, so please note that requested feature is required before 22-Nov-2019.
