### ISSUE TITLE
[Header action buttons with dropdowns] X with blue background when selected

### ISSUE THREAD

**Issue by daphoenix** [IBM/carbon-addons-iot-react#685]
### Summary

Building Insights development team needs the component to implement application switcher selected state, documented in the [Watson IoT PAL](https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/components/ui-shell-header-panel/usage#general-guidance) -
* White X on blue background when selected - still to be implemented.
<img width="209" alt="Screenshot 2019-11-05 at 22 02 55" src="https://user-images.githubusercontent.com/5711817/68245925-23ea6380-0018-11ea-8ce4-37c154234a43.png">

**Additional context**
* Current behaviour
1. Go to **Storybook link** - [Application Switcher Component](https://carbon-addons-iot-react.com/?path=/story/watson-iot-header--header-action-buttons-with-dropdowns).
2. Click on top-right 3x3 menu icon.

* Desired behaviour
3. White X on blue background icon when selected, displaying the header panel content with a white background.

### Specific timeline issues / requests
Do you want this work within a specific time period? Is it related to an
upcoming release?
* Required by the end of November for next product release.

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources
What resources do you have to assist this effort?
_Carbon Add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by davidicus** [comment]
@lukefirth Correct me if I am wrong but the PAL had moved away from the blue background. I can't recall if the x was also changed in favor of conformity to the hamburger icon. Luke, is the spec correct and the component be updated?

**Comment by davidicus** [comment]
Related to [#663](https://github.com/IBM/carbon-addons-iot-react/issues/663) where they are asking the same questions.

**Comment by daphoenix** [comment]
closed as duplicate.
