### ISSUE TITLE
[Table] In table toolbar search icon should be right align and also display table record count (left align) 

### ISSUE THREAD

**Issue by sunilkotiyaibm** [IBM/carbon-addons-iot-react#689]
[Table] In table toolbar search icon should be right align and also display  table record count (left align) (Refer attached design spec)
 
![TableToolbar](https://user-images.githubusercontent.com/56038154/68297832-f0621480-00bd-11ea-8ccd-5fa73e7f37fb.png)

**Comment by creckling** [comment]
pal-tracking issue: https://github.ibm.com/Watson-IoT/pal-tracking/issues/34
