### ISSUE TITLE
[Component Proposal] Navigating the hierarchy using search

### ISSUE THREAD

**Issue by daphoenix** [IBM/carbon-addons-iot-react#695]
### Summary

Describe in detail the component you would like developed.
Include what offering/product you plan to utilize this new component in.

Navigating the hierarchy using search component from the [PAL - Invision](https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319242460) for Building Insights for [next release](https://ibm.invisionapp.com/share/AWNZD4CM96H#/319286147_3-01_-_Type_Search_Directly)

**Additional context**
Add any other context about the component here [e.g. screenshots, code, InVision prototype, Box notes containing details necessary for implementation]
Screenshot
![Screenshot 2019-11-07 at 04 04 34](https://user-images.githubusercontent.com/5711817/68357026-57121d00-0114-11ea-8c2f-5353dfdc8642.png)

### Specific timeline issues / requests
Do you want this work within a specific time period? Is it related to an
upcoming release?
* Required by the end of November for next product release.

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### You will consider this component complete when...
- [ ] It's available as an export of this library
- [ ] Additional criteria you may have [e.g. Fully responsive, Accessible to WCAG 2.0, etc.]

### Available extra resources
What resources do you have to assist this effort?

Possibly one member of the development team, depending on timelines.
_Carbon Add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by tay1orjones** [comment]
This looks like a duplicate of #665

**Comment by daphoenix** [comment]
Yes and closing
