### ISSUE TITLE
CSP error about  'unsafe-eval'

### ISSUE THREAD

**Issue by ilovepumpkin** [IBM/carbon-addons-iot-react#696]
I am trying to use "carbon-addons-iot-react": "1.98.9" in our product (we have to use 1.x because our project is carbon v9 based now ). And our product is enabled with some CSP policies (no 'unsafe-eval'). Now I found the following errors raised by CSP. If I add 'unsafe-eval' in CSP configuration, the following error is gone. 

![image](https://user-images.githubusercontent.com/11310645/68367739-55c30d80-0171-11ea-8fa4-8fa271458f71.png)

I know 1.x is under maintenance mode and your focus is on 2.x. If this issue can not be fixed in 1.x, will it be fixed in 2.x? The reason why I ask this is because next year we will move to carbon 10 and carbon-addons-iot-react 2.x so hope at that time this issue is already fixed.

**Comment by tay1orjones** [comment]
After some digging, I've found this is coming from a dependency `ajv` used to validate the json schema.

See https://github.com/epoberezkin/ajv/issues/406:

> Ajv compiles schemas to code. You can do it at run time, in which case it uses Function constructor - you will need to change your CSP to allow it. Or you can do it at build time converting all your schemas to modules that can be required (it is done this way in "table" package, e.g.). There is no other option.

@scottdickerson @bryancboyd We might consider doing schema validation at build time instead of runtime. Otherwise consumers will have to lax their CSP settings, which may not be possible.

**Comment by scottdickerson** [comment]
@ilovepumpkin we're strongly considering moving AJV out of the repo entirely this should fix the issue.

**Comment by ilovepumpkin** [comment]
@scottdickerson thanks a lot! our release will be out at the end of this December. If this issue could be fixed before that, which will save us a lot of effort to update CSP configurations for all tenants in production environment. Is it possible?
