### ISSUE TITLE
[Table] Filters

### ISSUE THREAD

**Issue by bryancboyd** [IBM/carbon-addons-iot-react#7]
Implement filter enhancement to table component

##### Model

* Filter option and format (i.e. `canFilter`, `filterType = 'enum'`, `filterOptions = ['Connected', 'Disconnected']`) should be associated with `columns` prop in table.
* Active filter(s) should be under `view` prop (example: `view.filter.activeFilters = [{ id: 'deviceId', value: 'A123*' }, { id: 'status', value: 'Connected' }])

##### State: No filters added

* User can apply filters in the table at column level.
* When filter button is clicked, the filter icon turns blue and the filters expand

![image](https://user-images.githubusercontent.com/2175647/51208926-9b59d580-18d4-11e9-9935-a321d703b4fd.png)

##### State: With filters added

* Once a user starts typing in a filter, a cancel button would pop up similar to how the search bar functions
* User can press enter or click off the input to add their filter
* A "clear all filters" button would appear once any filters have been added

![image](https://user-images.githubusercontent.com/2175647/51208949-a57bd400-18d4-11e9-8bff-cd8984e54d0e.png)

**Comment by tay1orjones** [comment]
I believe the only remaining items for this are

- [ ] clear all filters button
- [ ] 'cancel' button on text input filters (ComboBox already has it)
- [ ] minor styling fixes - toolbar toggle icons active state
