### ISSUE TITLE
[Component Proposal] TileGallery

### ISSUE THREAD

**Issue by bryancboyd** [IBM/carbon-addons-iot-react#705]
### Summary

This component (maybe needs a different name than `TileGallery`?) will implement the "Dashboard Landing" pattern:

* collapsible sections
* tiles with: description on hover, click events, thumbnail image, name/icon, overflow menu
* exportable search + list/grid toggle components that can be consumed by a client (typically in `PageTitleBar` extraContent)

**Additional context**
![image](https://user-images.githubusercontent.com/2175647/68604182-88ba1980-046f-11ea-8a9a-d19dd897aae4.png)

https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319120583

### Specific timeline issues / requests

Prototype immediately, finalized in Dec 2019

### You will consider this component complete when...

- [ ] It's available as an export of this library
- [ ] Fully documented, a11y, etc. (the usual)

### Available extra resources

@cgirani and @blechner are working on the prototype.

**Comment by cgirani** [comment]
After some discussion with @blechner we thought:

1. left content just render a node,  where can be used as an icon or another content
2. right content (overflowMenu) also just render a node, which gives us more flexibility
3. Props for width/height, so it can fit for both solutions.

**Comment by bryancboyd** [comment]
@cgirani sound good, although lets avoid `left` and `right` so that it still makes sense in RTL languages/contexts... maybe use before / after?

**Comment by bryancboyd** [comment]
![image](https://user-images.githubusercontent.com/2175647/68616950-b9a84780-048b-11ea-84bc-98f7eabe706b.png)

![image](https://user-images.githubusercontent.com/2175647/68616975-c6c53680-048b-11ea-9b39-f1df0d13c98c.png)

Although, based on these uses I think having named props (that still render nodes) would be fine... `icon` (node), `title` (node), `overflowMenu` (node).  If icon is undefined, the title would be left-aligned on the tile.  If overflowMenu is undefined, nothing would be rendered there

**Comment by davidicus** [comment]
Closed in  PR mentioned above.
