### ISSUE TITLE
[Table]: GVT testing.  

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#71]
Use the table in a GVT environment and make sure that all the user-visible strings are correctly translated/translatable

**Comment by bryancboyd** [comment]
fixed by https://github.com/IBM/carbon-addons-iot-react/pull/112

**Comment by bryancboyd** [comment]
preview: https://deploy-preview-112--carbon-addons-iot-react.netlify.com/?selectedKind=Table&selectedStory=Stateful%20Example%20with%20I18N%20strings&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
