### ISSUE TITLE
SideNav: isActive is not highlighting the menu item when nav bar is in collapse state.

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#717]
### Describe the bug

SideNav component when collapsed does not show the highlight/focus on the menu item which is set isActive. Only when it is expanded the menu item is highlighted.

### To Reproduce
isActive is set true for Explore tab.

When sidenav is collapsed Explore tab is not dispalyed highlighted as in below screen
<img width="437" alt="image" src="https://user-images.githubusercontent.com/22093326/68852373-bcaa6e80-06fd-11ea-82c2-9f226ace2ba3.png">

Whereas when it is expanded Explore tab is highlighted.
<img width="362" alt="image" src="https://user-images.githubusercontent.com/22093326/68852411-d0ee6b80-06fd-11ea-9dff-f15dd7b10221.png">

I have noticed that the behaviour works fine with lower version of carbon-addons-iot-react v2.3.2. Below codesandbox is for reference.
https://codesandbox.io/s/carbon-iot-react-header-n4q3h

Whereas with higher versions 2.8.5 which we are currently using it has the issue mentioned above.

### Specific timeline issues / requests

We need this bug to be fixed for our Nov release.

Relative PAL issue: https://github.ibm.com/Watson-IoT/pal-tracking/issues/72

**Comment by davidicus** [comment]
Adding another issue with subnav items background color to be fixed with this item
