### ISSUE TITLE
Stateful table: Any settings to disable data table toolbar section?

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#729]
### Summary

As I don't have any toolbar items for the stateful table component that I am using, so I don't want the table toolbar section to be shown. Please suggest if there is any porp to be set to get rid of it. Below image has the highlighted section which needs to be removed, and this screen capture is from the storybook. https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--simple-stateful-example

![image](https://user-images.githubusercontent.com/22093326/69117207-fd670680-0ab4-11ea-8334-56e6cab96cfb.png)

**Comment by davidicus** [comment]
Hi @kalyanixraut, our `Table` component currently does not have a prop to achieve this. However, we are exporting the Carbon `DataTable` which will allow you to remove this header area.

**Comment by davidicus** [comment]
@lukefirth I imagine this is something we should support in our `Table` component. Does the PAL spec have any issues wit this?

**Comment by kalyanixraut** [comment]
@davidicus ,  I don’t find carbon’s exported datatable in the storybook nor available here https://github.com/IBM/carbon-addons-iot-react/blob/master/src/index.js
Can you please point it out for me. Thank you!

**Comment by kalyanixraut** [comment]
Any update on this?

**Comment by sstone2423** [comment]
PR is open related to this: https://github.com/IBM/carbon-addons-iot-react/pull/902
