### ISSUE TITLE
[TileCatalog] visual design update for Carbon 10

### ISSUE THREAD

**Issue by bryancboyd** [IBM/carbon-addons-iot-react#731]
### Summary

What changes do we need for this component for Carbon 10?  The screenshot below is from an recent application design using carbon-addons w/ Carbon 10.

**Additional context**

![image](https://user-images.githubusercontent.com/2175647/69184125-d8d15580-0ad9-11ea-8eab-397cf7744697.png)

<sub>[Internal issue #59](https://github.ibm.com/Watson-IoT/pal-tracking/issues/59)</sub>

**Comment by bryancboyd** [comment]
The current component capabilities include search and pagination (optional).

https://carbon-addons-iot-react.com/?path=/story/watson-iot-tilecatalog--with-search

![image](https://user-images.githubusercontent.com/2175647/69184364-57c68e00-0ada-11ea-8212-f84767894655.png)

**Comment by tay1orjones** [comment]
[On hold pending decision/information from internal PAL team](https://github.ibm.com/Watson-IoT/pal-tracking/issues/59)
