### ISSUE TITLE
[StatefullTable] and [TableCard] Pagination component icons mis-aligned.

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#755]
### Describe the bug

I am using [StatefullTable] and [TableCard] components and both has mis-aligned icons in the pagination in Chrome and Safari browsers
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/22093326/69894755-3b341c80-134a-11ea-8299-25ead78cbff4.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/22093326/69894768-64ed4380-134a-11ea-9266-be594baafd34.png">

I am using "carbon-addons-iot-react": "2.17.0"

**Comment by scottdickerson** [comment]
this is no longer a suggested size
