### ISSUE TITLE
[TableCard] size-tall: How to get rid of the time filter and dowload icons?

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#756]
Hi Team,
Have following queries on [TableCard] component:
1) How can I get rid of the Timefilter and Download icon from the header.
2) The Pagination looks little mis-styled in chrome and safari where as it seems ok in Morzilla FF.
3) I want to use [SimplePagination] instead of the default pagination to match our design. So, how can i disable the tablecard pagination?
4)To match the Search as in design (expanded by default), I will have to do style changes.. correct?
Uploading a supporting screen capture for your reference.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/22093326/69894799-d1684280-134a-11ea-948d-59e649cb5450.png">

**Comment by tay1orjones** [comment]
1. We have an open issue https://github.com/IBM/carbon-addons-iot-react/issues/643 to consolidate all icons into one bar. With this work, we could add the ability to customize/remove the action buttons. 
1. I can not reproduce the rendering issue, could you please provide more information on your environment and a reproducible example via codesandbox? https://codesandbox.io/s/codesandbox-yxbkg
1. SimplePagination can not be used within TableCard, as TableCard uses `StatefulTable` to remain consistent across our provided table implementations. We would welcome a PR to add the ability to customize the props passed to the existing pagination.
1. Yes, that design does not follow the unified design direction for search on tables and would need to be an override in your application. I'd consult with your designer - the search bar should likely remain as it is in our library by default.

**Comment by scottdickerson** [comment]
we're replacing the Table card Tall with a ListCard component very soon.
