### ISSUE TITLE
[TableCard] renderDataFunction is not working.

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#766]
Hi Team,

I am using ``` <TableCard> ``` component for implementing a card as shown below in design reference. The cell data needs to be customized so that it behaves like a navigation link. For this I am trying to use renderDataFunction but it is not working and seems to be hardcoded to renderThresholdIcon only.

Design reference : 
<img width="194" alt="image" src="https://user-images.githubusercontent.com/22093326/70149776-d15f9e00-16ce-11ea-9732-b09666b0040e.png">

Storybook reference:
I am using https://carbon-addons-iot-react.com/?path=/story/watson-iot-tablecard--size-tall
carbon-addons-iot-react: v2.17.2

### Specific timeline issues / requests

We need this fix for our Jan 2020 release.

<sub>[Internal tracking issue #131](https://github.ibm.com/Watson-IoT/pal-tracking/issues/131)</sub>

**Comment by davidicus** [comment]
@bryancboyd @scottdickerson Can you speak to this?
