### ISSUE TITLE
[Table] Allow Advanced Query of Table component, need a UX mockup of how that would look, where we would implement

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#78]
The usecase is, what does the Table component look like if it is being Searched with an Advanced Searched query dialog that will fire a query against the server and then prepopulate the table.  Do filters within the Table update, etc.  We need some UX designs here of how the table should act.

@jordanwsmith15 can you work with Karen to help with that?

**Comment by scottdickerson** [comment]
sls@ca.ibm.com

**Comment by scottdickerson** [comment]
@matsgothe @CynthiaZhang

**Comment by scottdickerson** [comment]
don't need this for a while, the Maximo guys don't have it in their early mockups...

**Comment by matsgothe** [comment]
This requirement is related to more advanced filters and saved queries. It is a general need, but not MVP for a first Table component version Lets keep it in backlog.

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.

**Comment by matsgothe** [comment]
This is related to filters, views and advanced queries. It may be tracked in separate issues. @amymillett?
