### ISSUE TITLE
Can 'import ondemand' be supported?

### ISSUE THREAD

**Issue by ilovepumpkin** [IBM/carbon-addons-iot-react#793]
I am using version 1.98.9. I found this package is huge and it does not support import-on-demand. For example, currently I only need to use StatefulTable and now there is only one index.js to import, so the whole package has to be bundled. Is it possible to support import-on-demand ?

**Comment by tay1orjones** [comment]
Hi, are you finding the package isn't working with [tree shaking](https://developer.mozilla.org/en-US/docs/Glossary/Tree_shaking)? That technique is how we intend to meet this use case.

Imports structured as so:
```
import { StatefulTable } from 'carbon-addons-iot-react';
```
import only that named module into the current module.

Other components not imported can then be automatically tree shaken by your module bundler, most commonly [webpack](https://webpack.js.org/guides/tree-shaking/).

**Comment by ilovepumpkin** [comment]
@tay1orjones , yes, I think it is not working, or maybe something wrong with my webpack configuration. 

I am sure I am using 'import { StatefulTable } from 'carbon-addons-iot-react';' in my code and this is only component I am using. As you can see below, 'carbon-addons-iot-react' adds 1.52MB to my bundle. 

![image](https://user-images.githubusercontent.com/11310645/71139204-7a1e0980-2248-11ea-951e-dad3b451c3cb.png)

I am talking about the version 1.98.9. Are you sure 'tree shaking' works in this version?

**Comment by scottdickerson** [comment]
treeshaking will work downstream if you setup your webpack the right way.  Follow the guide above to remove the dead code (use optimization: {usedExports: true} in your webpack and 

```
 "sideEffects": [
    "*.css",
    "*.scss"
  ],
```
in your package json

However @tay1orjones @davidicus  it is weird that we are packaging the whole carbon-icons file in our rollup even though we only use about 10 icons.  The @carbon/icons-react is almost 2 MB of the 3 MB size  According to my research, rollup is support to automatically tree shake those unused icons out!

**Comment by scottdickerson** [comment]
https://github.com/eight04/rollup-plugin-cjs-es . I believe points to our use of CommonJS to breaking the default treeshaking behavior of rollup

**Comment by scottdickerson** [comment]
actually I am incorrect, I checked and the Branch24 is removed from our build correctly using Tree shaking
