### ISSUE TITLE
[classnames] unify import name

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#799]
We're not using a consistent name for usages of the `classnames` package. 

`import cn from 'classnames';`
`import cx from 'classnames';`
`import classnames from 'classnames';`
`import classNames from 'classnames';`

We need to decide on one and refactor all usages to fall in line.

**Comment by sstone2423** [comment]
Looks like `cx` and `classNames` are used by the package's README.

I'd suggest `classNames`, just to keep it obvious.

I can change these imports after the name is decided though

**Comment by tay1orjones** [comment]
There might be an eslint rule we could employ to help drive this consistency. We should do some research. Not a requirement by any means though.
