### ISSUE TITLE
[Table] Grid Layout - When you enable FILTERS, table header component with actions is not resized

### ISSUE THREAD

**Issue by murinha** [IBM/carbon-addons-iot-react#804]
If you have a lot of columns, when you open FILTER option, filtering fields are now displayed under each column header, it expands but the "actions" header is not resized accordingly, as you can see in the screenshot below.

![image](https://user-images.githubusercontent.com/6778220/71679792-34446380-2d67-11ea-8e04-9291b90fc6df.png)

**Comment by tay1orjones** [comment]
I believe this has been fixed through an unrelated PR - please reopen if the issue persists
