### ISSUE TITLE
[Fixed Button Bar] Full-page wizard

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#806]
I'd like to formalize a pattern/component design around a full-page wizard (component name: **PageWizard** ?)

Here are some screenshots from a recent Monitor design that include this component.  Let's take a step back and decide on different permutations of the pattern and ways we can implement a single component to cover all cases of a full-page wizard.

![image](https://media.github.ibm.com/user/699/files/edfa1d80-fa20-11e9-81bc-507c709537b3)

![image](https://media.github.ibm.com/user/699/files/05390b00-fa21-11e9-8ccc-9a7a9ec8fca4)

![image](https://media.github.ibm.com/user/699/files/0ec27300-fa21-11e9-9f2a-1d4fa36bb1d6)

Common elements:

- Progress indicator
- In each step, a title and descriptoin
- in the body of each step, both 1 and 2-column layouts (assuming these would collapse in a responsive way?)
- back/cancel, next/finish buttons beneath step body, left-aligned

See comments in PAL tracking issue [#17](https://github.ibm.com/Watson-IoT/pal-tracking/issues/17)

**Comment by davidicus** [comment]
@bryancboyd any updates on this issue?

**Comment by sstone2423** [comment]
FYI: PageWizard was moved to production in this PR https://github.com/IBM/carbon-addons-iot-react/pull/875

**Comment by sstone2423** [comment]
Was there something else that needed to be added? @bryancboyd @davidicus 

It looks like this can be closed
