### ISSUE TITLE
[Dropdown] Long texts in the option displayed with ellipses, but no tooltip to see the complete text.

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#814]
### Describe the bug

Using the Dropdown component, when there is a long text in the dropdown items the text is displayed with ellipses but there is no way(onHover) to see the complete actual text.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/22093326/72129181-55c2d200-339b-11ea-93fb-a76c9268d4af.png">

### To Reproduce

https://codesandbox.io/s/carbon-addons-iot-react-with-carbon-6-26f6s
Please note the version used in actual implementation is 2.17.7. As I don't have a working codesandbox with this version so used 2.8.5 in the above codesandbox link.

Do you want this work within a specific time period? Is it related to an
upcoming release?
Expected a fix for Jan 2020 release.

**Comment by bjornalm** [comment]
I think that this one was solved in Carbon with commit 62024063d8c298e17eea54e77ec593ee01a2a63f

A title with the item text has been added:
![image](https://user-images.githubusercontent.com/5167091/74563290-bfbb3200-4f6c-11ea-9f17-ffd03d78f102.png)


This was the PR
https://github.com/carbon-design-system/carbon/pull/5102

**Comment by davidicus** [comment]
closing. This issue will be resolved once we have upgraded our Carbon deps to 10.10.0 which will is being tracked [here](https://github.com/IBM/carbon-addons-iot-react/issues/979)
