### ISSUE TITLE
[Stateful Table] Using Sticky header prop in stateful table component brings issue with tooltip when redered as custom cell.

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-addons-iot-react#818]
### Describe the bug

I am having Tooltip as custom render in the Stateful table cell. The table has stickyHeader prop set to true. Tooltip is clicked the tooltip text remains at the same position when table content is scrolled.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/22093326/72258327-c71cb200-3633-11ea-9673-0147a5db7958.png">

Do you want this work within a specific time period? Is it related to an
upcoming release?
Looking for a fix for Jan2020 release.

**Comment by enricoberti** [comment]
@davidicus generally speaking in a non-sticky header table, the tooltip positioning still is related to that position:fixed we have on storybook.

@kalyanixraut for this specific case it's a partly missing functionality in Carbon where the calculation for the offset fails. I created a new story(#905) so you can see it working. Demo [here](https://deploy-preview-905--carbon-addons-iot-react.netlify.com/?path=/story/watson-iot-table--with-sticky-header-and-cell-tooltip-calculation)

The gist of it is to add `style={{ position: 'relative' }}` and  `data-floating-menu-container` to the custom cell renderer container and pass a `menuOffset` function that calculates the tooltip offset based on the cell size and the page scroll itself.

In our case, something like this:
```javascript
const renderDataFunction = ({ value }) => (
    <div style={{ position: 'relative' }} data-floating-menu-container>
        {value}
        <Tooltip
        direction="right"
        tabIndex={0}
        tooltipId="table-tooltip"
        triggerId="table-tooltip-trigger"
        triggerText=""
        menuOffset={menuBody => {
            const container = menuBody.closest('[data-floating-menu-container]');
            return {
            top: -container.getBoundingClientRect().y - window.pageYOffset + 4,
            left: -container.getBoundingClientRect().x - window.pageXOffset + 10,
            };
        }}
        >
        <p>This scroll with the table body</p>
        </Tooltip>
    </div>
);
```

The same but with the prop `menuOffsetFlip` would be required when having a flipped tooltip.
