### ISSUE TITLE
[TableCard] Combine CardHeader with TableHeader

### ISSUE THREAD

**Issue by sstone2423** [IBM/carbon-addons-iot-react#820]
### Summary

When the TableCard is rendered, the CardHeader is rendered with the TableHeader stacked below it. This causes a lot of wasted white space, so it would be more efficient to combine the two.

**Additional context**
Considering these two components were originally designed as two separate components, it will require refactoring both components.

Related internal issue: https://github.ibm.com/wiotp/monitoring-dashboard/issues/517

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

Next release.

### Available extra resources

What resources do you have to assist this effort?

I will fix myself

**Comment by davidicus** [comment]
duplicate of #643
