### ISSUE TITLE
Refactor the TableHead.jsx code for Carbon files 

### ISSUE THREAD

**Issue by sunilkotiyaibm** [IBM/carbon-addons-iot-react#834]
### Summary

Refactor the TableHead.jsx code for Carbon files added (TableHeader.js, state/sorting.js, tools/cells.js, tools/sorting.js), due to Carbon change (ref for <th>) delayed in IOT Table column resize feature 

**Additional context**
Carbon files(TableHeader.js, state/sorting.js, tools/cells.js, tools/sorting.js) need to be removed and related dependcy to modified in TableHead.jsx

### Specific timeline issues / requests

This need to be work when Carbon release (ref/addition ref changes) is merged in IOT. 

### Available extra resources

What resources do you have to assist this effort?

Prabha Shankar will work on this.

**Comment by davidicus** [comment]
issues is stale. closing
