### ISSUE TITLE
  [Cards] Gauge Card for monitor and dashboards

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#849]
**Description**
Gauge Card displays a gauge chart inside a card in the dashboard.
Similar to other chart cards in iot-react: https://carbon-addons-iot-react.com/?path=/story/watson-iot-timeseriescard--medium-single-point-interval-hour

**Name of Pattern or Asset**
Charts: https://www.carbondesignsystem.com/data-visualization/basic-charts

**Additional context**
https://carbon-design-system.github.io/carbon-charts/

PAL repo [issue](https://github.ibm.com/Watson-IoT/pal-tracking/issues/46)

>@cynthiaz Will your team be working on this any time soon?
>We have a couple different donut requirements for APM and I'd like to compare and come up with a standard.
>
>https://ibm.invisionapp.com/d/main#/console/15351459/319304692/preview
![image](https://media.github.ibm.com/user/837/files/f2408700-1d91-11ea-911d-cd017cbcddcd)

**Comment by tay1orjones** [comment]
Missed the auto close on the PR. This is complete 👍
