### ISSUE TITLE
[datepicker] Time range / date-time picking for dashboards

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#854]
Copied from PAL tracking [issue](https://github.ibm.com/Watson-IoT/pal-tracking/issues/26)

**Description**
Time range picker is a common dashboard component requested by many product teams. The component gives user control over the default range, as well as allowing them to filter the data that is being visualized in dashboard by time.

**Name of Pattern or Asset**
_Add the name and a link to the pattern you are referencing in IoT or Carbon_

- Carbon's date range picker: http://react.carbondesignsystem.com/?path=/story/datepicker--range-with-calendar

- Carbon's time picker: http://react.carbondesignsystem.com/?path=/story/timepicker--default

**User outcome**
_Is this related to a user outcome you are working on?_

Users need to be able to change the time window of the data in dashboard. 

**Proposal**
_Do you have a proposed solution? or something you have tried already?_

Proposed design 
![Proposal](https://media.github.ibm.com/user/627/files/1bfa6e00-1070-11ea-95de-c387f11bc0f3)
- the picker provides preset ranges that are relative to Now, this helps user to quickly filter their data
- ability to set a custom relative range 
- ability to set an absolute range 
- ability to inline edit the range that conforms to a specific format
- only commit the change upon clicking "Apply" 

Additional comments from thread:

@cynthiaz
>Here's the latest design exploration 
><img width="1256" alt="image" src="https://media.github.ibm.com/user/627/files/f3c8b780-0b23-11ea-9ffa-eba23bc202b6">

@Laura-Dohle
>@cynthiaz I think that looks awesome! 
Only two comments:
>- I have doubts about is calling it "custom range". When I think about custom range I would expect to add a custom relative range, e.g. last 31 days. I would propose we call it absolute range instead.
>- Instead of using the calendar icon plus dropdown, why don't we use the same visual style carbon is using for their calendar component for aligment:  <img width="261" alt="screenshot 2019-11-20 at 15 03 03" src="https://media.github.ibm.com/user/51161/files/e43e8280-0ba6-11ea-8bc0-31fbb1a284d4">

@cynthiaz
>@Laura-Dohle 
thanks for the feedback!
The reason we didn't use the exact carbon's calendar component is because we wanted to hint user that it's a dropdown with options, rather than suggesting it's only a calendar for picking date.
>
>The default behavior that we expect is to open a dropdown with a list of common relative ranges. Then if the user is not finding anything, they can set an absolute range, which uses the carbon's calendar and behaves exactly the same way as here: http://react.carbondesignsystem.com/?path=/story/datepicker--range-with-calendar
>The only differences are: 
>1. merged two input fields into one; 
>2. added input field to set time
>3. support inline edit with x button to clear the range 

@tay1orjones 
>As this firms up and we begin to look at implementation, it will be important to have a clear path of keyboard navigation through the interactions of this component. There are [a few items open on Carbon for a11y of their DatePicker](https://github.com/carbon-design-system/carbon/issues?q=is%3Aissue+datepicker+label%3A%22type%3A+a11y+%E2%99%BF%22), as well as [the library under the hood, `flatpickr`](https://github.com/flatpickr/flatpickr/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+keyboard).
>
>Some things I'm thinking about:
>- The dropdown tooltip showing absolute range will need to be available on focus in addition to hover.
>- Between the relative/absolute "modes" of the input, it will impact if we can show the tooltip
>  - When a dropdown is focused, it does not open. This works with the tooltip fine. 
>  - Although, when datepicker is focused, it does open. That doesn't work with the tooltip. We'd be opening the calendar as well as showing the tooltip.
>- When editing a range on the calendar, pressing enter applies the selection. This may need to be prevented so the user can select a date, then navigate to the time pickers.

@cynthiaz
>Iteration 3:
><img width="936" alt="image" src="https://media.github.ibm.com/user/627/files/71694900-0fa4-11ea-8dc0-b79bc9ff0612">
>- Default to show any applicable relative ranges (preset)
>- Select "Absolute range" option to open the calendar view
>
>@Laura-Dohle TBI's requirement of being able to choose the reference date instead of Today [Now], maybe a feature that the team can extend based on this pattern. Conceptually, I think once the reference date/time is changed, it becomes an absolute range with a specific Start and End date. The difference is around the experience of setting a custom range. Both options below achieve the same result, but I think what you requested is option 1, which is less burden for user to set the duration.
>1. Last `[ 5 ]` `[hours]` ending at `[Oct 8 15:00] ` 
>2. From `[Oct 8 10:00]` to `[Oct 8 15:00] `

>Saw @Laura-Dohle comment in #39 
>`select an end date and time as either a fixed end time or a relative end time of yesterday, 12AM`
>
>So this requires an option to also change the reference time for a relative range. We could use the custom range option to set a relative or an absolute range: 
><img width="836" alt="image" src="https://media.github.ibm.com/user/627/files/55b38080-1040-11ea-85f0-7a83bb77be9a">
>
>Relative end time could include Today/Yesterday/End of this week... so on

@lukefirth 
>I like this, although my question now is - 'when i'm in custom, how do I get back to regular? 😄 '
>
>Also, are my eyes playing tricks on me, or is the 'custom range' button in the dropdown on the left, a smaller text size than the other options?

@Cynthiaz
>sharp eyes! @lukefirth 😄 
>
>wrt your first question, I thought about it and made a trade off for simplicity.. 
So you are able to click anywhere outside or "Cancel" to close it, and click the dropdown again to get back to the default (2 clicks). We could add a content switcher or a button to get down to just 1 click. 

@lora_dohle
>I like the flow @cynthiaz. Love how we are keeping the dropdown simple while still allowing for full customisability. 
>
>Regarding @lukefirth 's point: How about changing the Cancel button on the custom range modal to a back button? They could still cancel by clicking outside of the modal.

**Comment by davidicus** [comment]
original request for this found #664

**Comment by enricoberti** [comment]
hi everybody! i'm working on this feature - did we reached an agreement on the open points @cynthiaz @lukefirth ? i take the last screenshot as guidelines, correct? thanks!

**Comment by cynthiaz** [comment]
@enricoberti this one has all the specifications:
![image](https://user-images.githubusercontent.com/6788485/75351805-b8522d80-5876-11ea-8a90-9e24c707a119.png)

**Comment by lukefirth** [comment]
Hey folks!

To add to that, @enricoberti I have added a .zip folder to box here: https://ibm.box.com/shared/static/4v2nera5q5p8cr8xvopjc65ihsyg4z2e.zip

that you should be able to access and download. Run the index.html inside and you should get a nice interactive redline for the above that I believe will be helpful.

And of course in general - any questions you may have then @cynthiaz and myself will respond asap 👍

**Comment by enricoberti** [comment]
nice! thank you @cynthiaz for the confirmation and @lukefirth for the Sketch export!
