### ISSUE TITLE
Build exceeding heap size

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#876]
### Describe the bug

We have had to increase our memory heap size considerably. This is way outside the norm for a UI library. We need to investigate sources of memory leak. Initial investigations point to several bugs with React as well as the `react-dnd` package that we use. 

### Additional context

https://github.com/facebook/react/issues/14732
https://github.com/facebook/react/pull/16115
https://github.com/nteract/nteract/issues/4892

**Comment by tay1orjones** [comment]
I dug a bit: React-dnd v7.4.5 had a memory leak react-dnd/react-dnd#1355. v7.5.0 contains the fix.

We're only on 7.0.2 right now. I'm unsure if this also contains the memory leak. Might be worth an exploration to see if just updating this dep helps.
 https://github.com/IBM/carbon-addons-iot-react/blob/c01d357e2f96dd397c92c2cf263d03a3ca12b13d/package.json#L88-L90

**Comment by tay1orjones** [comment]
I'm unable to reproduce the out of memory error.

To test, I removed the heap size flags from the npm scripts and ran profiler debugger on them by adding `NODE_OPTIONS='--inspect'` to the beginning of each relevant script. Heap size isn't even close to max, only like 200mb. 

I have pushed up my changes to a branch, `out-of-memory-repro`. @bryancboyd @scottdickerson @davidicus could you pull down branch `out-of-memory-repro` and test?

I suggest running the following commands to ensure we're all on the same clean slate and config.
1. `killall node`
1. `git pull`
1. `nvm use`
1. `yarn install`
1. `yarn start` - I'm unable to reproduce an out of memory error here
1. cancel server
1. `yarn test:base` - I'm unable to reproduce an out of memory error here
1. If/once finished,
1. `yarn test:watch` - I'm unable to reproduce an out of memory error here
1. If/once finished,
1. `yarn test:update` - I'm unable to reproduce an out of memory error here

If you're able to reproduce, please paste the error here. Stack trace or profiler result could be helpful as well. Flag can be modifed to `--inspect-brk` to automatically breakpoint at line 1 of server startup.

If we're unable to reproduce, we should consider removing the heap flags.
