### ISSUE TITLE
[TitleCatalog] TileCatalog/Marketplace

### ISSUE THREAD

**Issue by jessieyan** [IBM/carbon-addons-iot-react#881]
### Summary

Split into 2 parts work:
1. Simple tile canvas (#967 )
2. Enhanced tile canvas ( includes featured product tile, persistent search, filter)

TileCatalog Marketplace in design https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/components/catalog-marketplace/overview/#featured-product-tile

New TileCatalog component Includes:
Canvas with persistent search, featured tile and filter knobs. User can turn knobs on or off.
Featured product tile
Standard product tile
Icon product tile
Thumbnail product tile
Add examples for device types(simple canvas), function catalog(enhanced canvas)
Deprecate old TileCatalog

**Additional context**
Simple Canvas
![image](https://user-images.githubusercontent.com/24279794/73881763-8b39ce80-4826-11ea-99aa-08dd1b23d47a.png)

Enhanced canvas with persistent search, featured tile and filter
![image](https://user-images.githubusercontent.com/24279794/73881702-6fcec380-4826-11ea-963b-794e1f5a8bac.png)

Featured product tile
![image](https://user-images.githubusercontent.com/24279794/73881671-5e85b700-4826-11ea-8bf2-c3a68c009d77.png)

Standard product tile
![image](https://user-images.githubusercontent.com/24279794/73881796-9a208100-4826-11ea-9831-2bcbb9b36be7.png)

Icon Product Tile
![image](https://user-images.githubusercontent.com/24279794/73881812-a1e02580-4826-11ea-9491-8a5b8f818b19.png)

Thumbnail product tile
![image](https://user-images.githubusercontent.com/24279794/73881846-ae647e00-4826-11ea-8358-72ef7387b782.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### You will consider this component complete when...

- [ ] It's available as an export of this library
- [ ] Additional criteria you may have [e.g. Fully responsive, Accessible to WCAG 2.0, etc.]

### Available extra resources

What resources do you have to assist this effort?

_Carbon Add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by jessieyan** [comment]
Simple tile canvas (#967 ) is finished.

**Comment by davidicus** [comment]
@jessieyan this issue is closed, correct? or do you have more items to complete?

**Comment by davidicus** [comment]
@jessieyan are there other items to complete on this issue?

**Comment by jessieyan** [comment]
@davidicus Hey Dave, we can close it.
