### ISSUE TITLE
[ValueCard] Error & empty state for cards

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#889]
**Is this an extension to an existing component, pattern, or a brand new asset?**

**What is the rationale for this contribution.**
We need a pattern to represent, in a card (or other places), that there is a data collection error state.  In Health, the scheduled data collection task can error for various reasons.  We want an indicator that allows to user to click to see more information about the source of the error.

**Detail the intended behavior**
Need a state that allows the user to see that there was an error in the data.  This is not the same as missing data. 

Not clear what the difference is between Null data and No data, so providing a single "no data" state for now.

**Value card**
- No data state
- Error state

![image](https://media.github.ibm.com/user/837/files/3be6a480-480c-11ea-96f2-e498edfea335)

- Double dash where result would have been.
- No data **icon** is displayed, left-aligned.
- No data **label** is displayed to the right of the icon. It could vary based on the nature of the no data problem. 
- No data **description** is displayed in the card if there's room.  
- Icon, label, and description are provided by app.
- User can click / hover on icon or message to see a tooltip with additional information.  Tooltip contains anything not displayed in the card and any additional content provided by the application. (Question: should it include the icon, label and description regardless of what's show in the card?)
- User can click Learn more to get more information about the problem, if available.

Content adaptations for small cards
- If it's an extra small card (or too small to show the full label), label does not display (or should it just be truncated?)
- If it's an extra small card, the description only appears in the tooltip.

**Table card**
TBD

**Timeline card**
TBD

**Donut card**
TBD

Being worked on in APM https://github.ibm.com/asset-performance/apm-design/issues/438

**Inspiration from other products**
(Optional - remove this is you don't have any)

@KarenGski 
> We did some review with Luke in [asset-performance/apm-design#438](https://github.ibm.com/asset-performance/apm-design/issues/438) and settled on the following design for value cards.
> 
> ![image](https://media.github.ibm.com/user/837/files/d09cd280-480b-11ea-9443-1737b57886eb)
> 
> Open questions:
> 
> * Should the tooltip always contain all information? Or only the things that don't fit in the card?
> * If the label doesn't fit, should it truncate or disappear?
> 
> Charts will just follow Carbon charting standards (I think).
> 
> @lukefirth can you share your thoughts on the open questions and then confirm if good to go?

@lukefirth 
> Open questions:
> 
> **Should the tooltip always contain all information? Or only the things that don't fit in the card?**
> I'd relent to ID on this, but my recommendation would be just the info not shown. (Although I'm easy on this because the tooltip the info when open).
> 
> **If the label doesn't fit, should it truncate or disappear?**
> Labels as in 'No data available' and 'data error' and/or their text below?
> I think @msperli s proposal works with just the icon and the tooltip suffices.
> 
> Good to go from my perspective.

@KarenGski 
> @lukefirth Claudia is working on the content question of what goes in/out of the tooltip. We'll go with whatever the official Content recommendation is.
> Just the icon works for me.
> @msperli We're good to go. You can close the APM issue for this.
> @smithjor FYI
> @rdconner This is approved so I think we can move out of design and into dev backlog.

**Comment by davidicus** [comment]
@lukefirth now that the value card is not setting an xsmall card do we apply the styles of the xsmall based off card size?

**Comment by lukefirth** [comment]
@davidicus great catch!

Internal ref link: https://github.ibm.com/wiotp/monitoring-dashboard/issues/774

In short, recently there has been a small change in card sizes, and more importantly for this I believe - the naming convention of card sizes has been updated and simplified.

In the past we have had (in terms of sizes):

![image](https://user-images.githubusercontent.com/30671949/75354579-cef68580-5872-11ea-916f-47c62cfe4867.png)

1. XSmall
2. XSmall wide
3. Small
4. Medium
5. Wide
6. Large
7. Tall
8. Xlarge


The change in naming convention is to align the sizes of 'small', 'medium' and 'large' to the heights of the cards, and then make the varying width versions modifiers to those sizes resulting in:

![image](https://user-images.githubusercontent.com/30671949/75354561-c43bf080-5872-11ea-98ad-ced2834cf801.png)



1. Small
2. Medium
3. Large

Each with a 'default' a 'wide' and a 'thin variant which will control how many columns it takes up. 


**The upshot:**
In this case, applying a certain style to what was originally named the 'xSmall' size, would now map to the new 'Small' size.

@scottdickerson FYI and to fact check me - we should do a quick check on any other knock-on issues of the recent card size changes like this one.

**Comment by bjornalm** [comment]
> @davidicus great catch!
> 
> Internal ref link: https://github.ibm.com/wiotp/monitoring-dashboard/issues/774
> 
> In short, recently there has been a small change in card sizes, and more importantly for this I believe - the naming convention of card sizes has been updated and simplified.
> 
> In the past we have had (in terms of sizes):
> 
> ![image](https://user-images.githubusercontent.com/30671949/75354579-cef68580-5872-11ea-916f-47c62cfe4867.png)
> 
> 1. XSmall
> 2. XSmall wide
> 3. Small
> 4. Medium
> 5. Wide
> 6. Large
> 7. Tall
> 8. Xlarge
> 
> The change in naming convention is to align the sizes of 'small', 'medium' and 'large' to the heights of the cards, and then make the varying width versions modifiers to those sizes resulting in:
> 
> ![image](https://user-images.githubusercontent.com/30671949/75354561-c43bf080-5872-11ea-98ad-ced2834cf801.png)
> 
> 1. Small, Small wide
> 2. Medium, Medium narrow, Medium wide
> 3. Large, Large narrow, Large wide
> 
> Observe how each base size also have with a 'default' a 'wide' and a 'narrow' sibling.
> 
> **The upshot:**
> In this case, applying a certain style to what was originally named the 'xSmall' size, would now map to the new 'Small' size.
> 
> @scottdickerson FYI and to fact check me - we should do a quick check on any other knock-on issues of the recent card size changes like this one.

Hi @lukefirth 
so in the case of this "Error / Empty state"  issue. I initially implemented the minimalistic view (see image below) for the XSMALL card, but when should it be triggered now? For SMALL cards or for any measured width below a certain value?
![image](https://user-images.githubusercontent.com/5167091/75355983-9923c200-58af-11ea-9cb0-298640525904.png)

**Comment by lukefirth** [comment]
Hey @bjornalm !

I think that works, I'd expect the minimalistic version shown to be applied to the small, and medium narrow card sizes due to both of them having the same size (in respect to width), so that could be framed as under a certain value as a generic rule. 

As long as that value where the switch happens sits between the normal ranges of width between small/medium narrow and the larger ones.

**Comment by bjornalm** [comment]
@lukefirth

Ok, thanks. If small and medium narrow cards are the target for the minimalistic view then using those sizes in the condition would be the easiest solution.
