### ISSUE TITLE
[HierarchyList] If I start the list with a child element selected, the parent is collapsed

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#892]
### Describe the bug

Create the hierarchy list with defaultSelectedId.  The parent is not expanded by default and if the element is offscreen in a scroll pane, it's not visible.  We should probably scroll it into view if it's offscreen (even if it's in it's own pane)

**Comment by sstone2423** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll
