### ISSUE TITLE
IoT Breadcrumb Overflow implementation has issues with Knobs for BreadcrumbItems

### ISSUE THREAD

**Issue by RogerRosado** [IBM/carbon-addons-iot-react#924]
### Describe the bug

Using knobs in graphite storybook for Breadcrumb (specifically for breadcrumb items) will not be updated when the "hasOverFlow" is set. In my IoT development environment, I implemented similar knobs and has the same issues. After a quick troubleshooting in the code, it seems that the overflow items does not get updated with the latest breadcrumb item attribute changes.

### To Reproduce

1. Go to https://pages.github.ibm.com/maximo-app-framework/graphite/react/storybook/?path=/story/components-%E2%98%A2-breadcrumb--breadcrumb
2. Go to knobs
3. modify an value AFTER "Breadcrumb option 1" (the first breadcrumb item is the Only one that can be modified)
4. See that the displayed value does not get updated

### Expected behavior

The display in the story should be updated when knob values are changed.

### Additional context

Make a simple update to your Breadcrumb.story.jsx to add simple text knobs, then try modifying the text knob for Breadcrumb option 2:

```
storiesOf('Watson IoT | Breadcrumb', module)
  .addDecorator(withKnobs)
  .add(
    'default',
    () => {
      return <Breadcrumb {...props()} hasOverflow>
          <BreadcrumbItem href="#">
            {text('Breadcrumb option 1', '1 Homexxxxxxxxxxxxxxxxxxxxxx')}
          </BreadcrumbItem>
          <BreadcrumbItem href="#">
            {text('Breadcrumb option 2', 'breadcrumb 2')}
          </BreadcrumbItem>
          <BreadcrumbItem href="#">Breadcrumb 3</BreadcrumbItem>
        </Breadcrumb>;
    },
    {
      info: {
        text: `
          Breadcrumb enables users to quickly see their location within a path of navigation and move up to a parent level if desired.
        `,
      },
    }
  )
```

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by davidicus** [comment]
Do you have any additional information? what version of storybook, storybook knobs are you using?

**Comment by RogerRosado** [comment]
I used text and boolean knobs, but I believe it would affect all knobs on any "BreadcrumbItem" after the first one is defined. All successions after the first one will ignore all knobs.

(FYI, I also verified the issue in the IoT local environment when I modified the IoT Breadcrumb.story.jsx to include text knobs as described earlier above with the "hasOverflow" attribute)

The storybook version used (in Graphite):
 "@storybook/addon-a11y": "5.1.7",
    "@storybook/addon-actions": "5.1.11",
    "@storybook/addon-console": "1.2.1",
    "@storybook/addon-info": "5.1.11",
    "@storybook/addon-knobs": "5.1.11",
    "@storybook/addon-options": "5.1.11",
    "@storybook/addon-storyshots": "5.1.11",
    "@storybook/addon-storyshots-puppeteer": "5.1.11",
    "@storybook/addons": "5.1.11",
    "@storybook/react": "5.1.11",
