### ISSUE TITLE
[DataTable] header columns auto wrap by default past their text width on render

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#930]
### Describe the bug
The alerts table in our dashboard renders with column headers that are wrapping to multiple lines by default.

![image](https://user-images.githubusercontent.com/6663002/74782332-dad9ba80-5268-11ea-86d7-5f21560465b9.png)

### To Reproduce

1.Because the word-break is set to true (even if a column is not resizable), when tables are being sized to fit within smaller containers, it automatically starts wrapping the columns on first render.
2. We need to either conditionally turn off the word-break wrapping if resize isn't turned on, or we need to auto-size the header column to at least contain the text width by default to stop it from word-break wrapping by default

**Comment by tay1orjones** [comment]
@bjornalm do we need the `word-break: break-all;` for the table column resizing?
It was from the original implementation and was carried through your refactor:
https://github.com/IBM/carbon-addons-iot-react/blob/98f9fb6ea9276525b78adcef2872a749dccd0ac1/src/components/DataTable/_data-table.scss#L34

**Comment by JordanWSmith15** [comment]
Plus 1!  This was inherited in Graphite.

**Comment by bjornalm** [comment]
> @bjornalm do we need the `word-break: break-all;` for the table column resizing?
> It was from the original implementation and was carried through your refactor:
> https://github.com/IBM/carbon-addons-iot-react/blob/98f9fb6ea9276525b78adcef2872a749dccd0ac1/src/components/DataTable/_data-table.scss#L34
> 
> Conditionally turning off that style when resize is turned off sounds like the easiest way to remedy if it's required for the table column resize feature.

I think we need `word-break: break-all;` for resizing, otherwise it will look a bit strange and since the words would be cut (possibly on multiple lines) with no ellipsis. 
![image](https://user-images.githubusercontent.com/5167091/74886870-9d188700-5379-11ea-86b6-429e3428319b.png)

**Comment by bjornalm** [comment]
PR is here https://github.com/IBM/carbon-addons-iot-react/pull/941
