### ISSUE TITLE
[Table] Column Resizing throws an error

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-addons-iot-react#933]
### Describe the bug

Enable hasResize, then resize a column, it dies.

### To Reproduce

Enable hasResize, then resize a column, it dies.

Codesandbox is just showing an error on the button example
> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/codesandbox-yxbkg

### Expected behavior

Should resize the column and not crash

### Additional context

![image](https://user-images.githubusercontent.com/1056553/74835610-b672f200-52eb-11ea-9b1e-3efc5ff0b102.png)

My yarn lock has the following...

![image](https://user-images.githubusercontent.com/1056553/74835645-cab6ef00-52eb-11ea-866f-bcb440ce5799.png)

I'm a little concerned here, since I thought that we were fixing the carbon component versions but, it appears that we will be getting diffrernent version of carbon components for different projects that use iot components at a fixed version.  I have no idea if that is causing this issue or not.

I've also been told that there is this PR in carbon and not sure if it's related to this issue or not.

https://github.com/carbon-design-system/carbon/pull/5084

**Comment by tay1orjones** [comment]
Relevant implementation: https://github.com/IBM/carbon-addons-iot-react/pull/867

**Comment by bjornalm** [comment]
How do I reproduce this? Pulling latest from master with the same carbon library versions as shown above doesn't trigger this error.
