### ISSUE TITLE
[SideNav] isEnabled bit is ignored on each item

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#943]
Our sidenav code supports an isEnabled prop on each link, but it incorrectly sets a disabled classname (which doesn't do anything)

![image](https://user-images.githubusercontent.com/6663002/74952322-c3641400-53c5-11ea-876e-bbbeabd170de.png)

**Comment by davidicus** [comment]
its meant to be able to be styled against. So if you want to gray them out or you want to remove altogether you can do so with a the disabled class. I think the class name should be changed and we should as if disabled though. We were using the isEnabled on monitor when certain features were only supported for certain tenants

**Comment by davidicus** [comment]
I see. the classname is being improperly applied.
