### ISSUE TITLE
Upgrade Carbon deps to v10.10.x

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#979]
There are several fixes needed in this upgrade. This work will have to be done post MAS MVP release. 

<sub>[Internal issue #301](https://github.ibm.com/Watson-IoT/pal-tracking/issues/301)</sub>

Complete when:
- [x] update all carbon deps
- [x] test our stories for defects

**Comment by cgirani** [comment]
MAS team depends on the latest carbon updates, `Notification` component

Carbon:
![image](https://user-images.githubusercontent.com/22034430/77328627-8e681b80-6cfb-11ea-927f-687d78e9595a.png)


Addons:
![image](https://user-images.githubusercontent.com/22034430/77328640-94f69300-6cfb-11ea-8245-e8d047f16845.png)

**Comment by tay1orjones** [comment]
We will need too take this into account: https://github.com/carbon-design-system/carbon/pull/5379

**Comment by davidicus** [comment]
`carbon-components@10.10.3`
>Bug fixes 🐛
fix(tag): define default tag style (#5677) (f8b485066)
fix(button): prevent hover on disabled buttons in g90/g100 theme (#5678) (04ae1e92d)
fix(tile): change expandable tile to button (#5609) (fbab6c0bd)
fix(components): remove @carbon/icons from peerDependencies (#5656) (39e612536)
fix(button): prevent icon and tooltip jumping for tertiary button (#5618) (f32c1a611)
fix(code-snippet): set correct width for feedback container in Safari (#5601) (0917bb27e)
fix(progress-indicator): use circle--filled icon (#5585) (7ae99155c)
fix(tile): add non link styling to clickable tile (#5591) (20517eb72)
fix(SideNav): disregard hover on non-rail SideNav when closed (#5562) (b494e528d)
Bug fixes 🐛
fix(button): prevent text jump in disabled button set (#5556) (38fb161af)
fix(dependencies): update icons dependency in vanilla (#5574) (f793a156a)
fix(toggle): change spacing to match style guide (#5462) (bbe9f0d50)
fix(link): use hover color token for visited links (#5559) (8b03644ec)
fix(tooltip): wrap icon tooltip content (#5544) (dfc695617)
fix(modal): change bottom margin (#5510) (3b7314442)
fix(tabs): update tab styles (#5482) (2c14be25b)
fix(modal): set half width single buttons (#5502) (80903ac57)
fix(Slider): onRelease not always firing (#2695) (#5359) (f5b7d0be9)
fix(overflow-menu): correct hover color (#5513) (40613c234)
New features 🚀
feat(tooltip): add support for hoverable definition tooltip body (#5323) (550bc70d0)
feat(select): add height variations to select (#5311) (6d23a7044)
feat(notification): add info icon to notification (#5203) (189c1c30f)
feat(react): add Grid components (#4894) (354baa82b)
feat(progress-indicator): update to use carbon icons (#5122) (aa33fa0c5)
feat: add Esc key support to dismiss tooltips (#5147) (f03a0a122)
feat(progress-indicator): adds hidden span to announce state of completion (#5125) (99fde8e0d)
feat(progress-indicator): add vertical progress indicator to react (#5146) (1532cf721)
feat(box-shadow): remove deprecated layer, use box-shadow mixin (#5126) (aed0ea253)
feat(text-input): add height variations to text input (#5076) (7011d0bf6)
feat(grid): add zero span columns (#5052) (a0752cd65)
feat(list-box): update selection style (#4753) (9e6335fdf)
Bug fixes 🐛
fix(data-table): correct padding for batch action buttons (#5413) (b3e0b3502)
fix(list-box): reset multiselect selection count position (#5405) (a0bc366d3)
fix(toggle): prevent text from wrapping (#5393) (a84e31c51)
fix(list-box): remove 32px margin right on option (#5400) (382df0407)
fix(number-input): fix positioning when no label is present (#5376) (18f3c8350)
fix(button): reduce ghost button left/right padding (#5334) (5454ef5af)
fix(combobox/text-input): add svg top positioning for IE11 (#5362) (347185b85)
fix(dropdown): ensure inline dropdown has light variant (#5322) (ee3229485)
fix(progressindicator): adjust styles for progress step with optional label position (#5356) (ea14f9874)
fix(button): update icon only ghost button colors (#5313) (8adc849d7)
fix(data-table): fix row sizing with overflow menu (#5292) (0aa38ec76)
fix(_header.scss): fixed head base nav with mobile first approach (#5238) (24429b8d6)
fix(accordion): resolve accordion header z-index issue (#5276) (554c9cee4)
fix(accordion): only target direct child p tags (#5291) (48c9e68b0)
fix(button): use currentColor as icon fill for all states (#5270) (0f9aef286)
fix(notification): inline notification fits parent container (#5268) (004c6143d)
fix(modal): add padding to last child only when scrolling is true (#5267) (a2424745a)
fix(tokens): update color tokens (#5240) (6093c2e45)
fix(code-snippet): use Carbon focus outline and reposition scroll bar (#5233) (ac8bcbd92)
fix(link): remove visited styles by default (#5239) (3c6bff698)
fix(file-uploader): adjusts default button and removes clear file button (#5166) (054b1da43)
fix(ui-shell): remove role='menu' from ui-shell (#5235) (eb9412f9d)
fix(inline-dropdown): vanilla style fixes (#5223) (7059be47e)
fix(search): update search icon to correct token (#5222) (51a3c0a31)
fix(data-table): remove hover styles from thead checkbox (#5209) (7e299c0db)
fix(button): correct sizes for icon-only buttons (#5195) (7e83aa779)
fix(code-snippet): remove focus from snippet container (#5202) (625a98bb7)
fix(button): remove margin added by safari (#5169) (2ce57b31b)
fix(select): change light select hover color token (#5150) (76f800906)
fix(datatable): add padding so search clear button doesn't obstruct text (#5145) (c39173f63)
fix(button): set min-height for field buttons (#5176) (2541e34d6)
fix(inline-loading): update type token (#5172) (6c6341473)
fix(storybook): remove layer import (#5160) (e3b3f0e2e)
fix(text-input): rename sizing props (#5167) (8c577c53c)
fix(tag): add default cursor to non-filter tag (#5140) (0fbfae935)
fix(modal): prevent modal from shifting when scrollbar appears (#5119) (1b3fe3a0f)
fix(date-picker): use correct background for date picker in modal (#5123) (08b6d3cbe)
fix(list): left align numbers (#5100) (d8aa52c8e)
fix(date-picker): adjust style slectors for disabled or prev/next days (#5085) (dc3de3416)
fix: duplicate id data-table in carbon-website (#5080) (baf2e0ae4)
fix(multiselect): fix invalid inline multiselect error icon (#5075) (67adf172d)
fix(accordion): update accordion breakpoints (#5074) (783b7c43b)
fix(data-table-skeleton): remove unnecessary border bottom (#5040) (7af549fcf)
fix(modal): fix modal content padding for regular size (#5046) (62453e7c6)
fix(modal): add transparent outline for high contrast themes (#5037) (e3752093c)
fix(tag): ensure tag keeps pill shape with single character (#5053) (7246188b2)
fix(ui-shell): remove role="menuitem" from header links (63c950e94)
fix(tabs): truncate container tab header text with ellipses (#5035) (532ebc864)
fix(text-area): set wrapper to width:100% to span container (#4995) (30dcf4238)
fix(list): explicitly remove list-style (#5000) (172b32fe3)
fix(list-box): fix dropdown item sizes (#5128) (2975d56db)
fix(dropdown): restore default dropdown height (#5118) (7e91692d8)
fix(listbox): set default title attributes to item text (#5102) (62024063d)
fix(list-box): ensure size variants are in effect (#4928) (0e4d6a82f)
fix(grid): moved vertical spacing to col (#4960) (ed368b1a9)
fix(Tag): ignore click events when disabled (#4792) (3264b8c22)
fix(CodeSnippet): use tooltip styles for feedback and add animation (#4741) (62217bdc0)
fix(uishell): add bgcolor to active links (#4980) (e46d9e4bb)
fix(text-area): change disabled light textarea background colors (#4983) (8f7a077b7)
fix(accordion-skeleton): add margin between icon & text when align=end (#4963) (1ce37896a)
fix(breadcrumb): set visited color to link-01 token (#4976) (ddf3afa42)
fix(checkbox-skeleton): apply skeleton class to checkbox (#4923) (4af62e67f)
fix(tag): adds various fixes for screen reader accessibility; adds AAT (#4863) (00786f81a)
fix(styles): add error handling for rem & em sass functions (#4931) (51558b60a)
fix(styles): update placeholder colors (#4799) (69d495ad4)
fix(code-snippet): maxheight 100% for expanded multi and add padding (#4915) (52145edbe)
fix(inline-notification): add 8px right padding if close button is hidden (#4873) (16f50a617)
fix(styles): replace old spacing vars with new syntax (#4889) (0fa982a91)
fix(button): update focus styles to use box-shadow (#4867) (8495b36f2)
fix(list-box): update chevron position for IE11 (#4898) (bb634cc9a)
fix(multi-select): close button for tags (#4890) (e2fa31ae5)


`@carbon/icons-react@10.9.3`
>Housekeeping 🏠
chore(release): v10.10.3 (109634091)
chore(release): v10.10.3-rc.1 (c78c9480c)
chore(project): sync generated files (af8895e87)
chore(release): v10.10.3-rc.0 (25fa5140a)

`@carbon/icons@10.9.3`
>Bug fixes 🐛
fix(icon): Remove redundant 16px variants (#5563) (ad8af68ce)
Bug fixes 🐛
fix(icons): include build-info.json in files for svelte team (#5536) (5a4587011)
fix(icon): makes up-to-top = back-to-top (#5509) (3e7b3daec)
New features 🚀
feat(icons): add icons from the January and February batch (#5342) (b82f079d5)
feat(icons): add December icon batch (#5015) (66b4833f2)
Bug fixes 🐛
fix(icon): embiggen caret and sort carets icons (#5412) (29f416db3)
fix(icons): update 32/settings--adjust.svg to use new geometry (#5361) (7e7bfeb40)
fix(icons): update switcher 32 geometry and overflow menus (#5314) (b49d5871e)
fix(ui-shell): fix onclick menu bugs (#5274) (616b18259)

`carbon-components-react@7.10.3`
>Bug fixes 🐛
fix(data-table): require additional props in certain situations (#5682) (c095b57d8)
fix(combo-box): add title attribute to input field (#5621) (854c1b21f)
fix(tag): define default tag style (#5677) (f8b485066)
fix(Tooltip): use valid prop name for tabIndex (#5679) (ffd588f1d)
fix(tile): change expandable tile to button (#5609) (fbab6c0bd)
fix(TableToolbarSearch): set focus on expanded search bar (#5637) (d6916b531)
fix(DropdownSkeleton): remove div role (#5619) (cc93f33ac)
fix(text-input): use placeholder text as title attribute (#5622) (b0494ea08)
fix(structured-list): remove unused prop (#5592) (6bc7f8b7a)
fix(icon-build-helpers): disable svgo plugins that cause rendering issues (#5603) (c0ae87bbc)
fix(progress-indicator): use circle--filled icon (#5585) (7ae99155c)
fix(tile): add non link styling to clickable tile (#5591) (20517eb72)
fix(InlineNotification): make statusIconDescription optional (#5528) (952c780cb)
fix(SideNav): disregard hover on non-rail SideNav when closed (#5562) (b494e528d)
Bug fixes 🐛
fix(button): remove role="button" from button styled anchors (#5522) (76e97f7c8)
fix(ui-shell): remove role="menuitem" from Switcher li's (#5525) (80d767b95)
fix(FileUploader): respect multiple prop in default file uploader (#5492) (f12617178)
fix(Slider): onRelease not always firing (#2695) (#5359) (f5b7d0be9)
New features 🚀
feat(tooltip): add support for hoverable definition tooltip body (#5323) (550bc70d0)
feat(select): add height variations to select (#5311) (6d23a7044)
feat(components): support automatic focus sentinel (#5260) (0e9c6d525)
feat(Tooltip): add several ARIA attributes (#5282) (45acec0b9)
feat(SideNavMenu): collapse submenu on esc keydown (#5198) (0853d381a)
feat(notification): add info icon to notification (#5203) (189c1c30f)
feat(react): add Grid components (#4894) (354baa82b)
feat(react): add support for rollup in bundles (#5185) (540889922)
feat(progress-indicator): update to use carbon icons (#5122) (aa33fa0c5)
feat: add Esc key support to dismiss tooltips (#5147) (f03a0a122)
feat(DataTable): allow additional contents to expand cells (#5060) (f3422c438)
feat(progress-indicator): adds hidden span to announce state of completion (#5125) (99fde8e0d)
feat(progress-indicator): add vertical progress indicator to react (#5146) (1532cf721)
feat(text-input): add height variations to text input (#5076) (7011d0bf6)
feat(data-table): add colSpan prop for TableHeader (#5088) (c061bccca)
feat(list-box): update selection style (#4753) (9e6335fdf)
feat(ListBox): fix labels of trigger buttons (#4820) (f87a204f6)
feat(file-uploader): add support for onChange (#4906) (66abfcf77)
Bug fixes 🐛
fix(Copy): add aria-live to announce text updates (#5386) (75acb174e)
fix: Prevent Tooltip setState call if not open (#5363) (aa276b2f0)
fix(number-input): remove default value for label (#5347) (acb94588f)
fix(ui-shell): add check for if href exists when handling onBlur (#5352) (50b14ff8c)
fix(button): update icon only ghost button colors (#5313) (8adc849d7)
fix(OverflowMenu): call closeMenu method only when menu is open (#5336) (61d137373)
fix(search): switch search role from datatable to search, add labeledby (#5330) (7e4c0e5b1)
fix(DatePicker): ensure down arrow opens calendar dropdown (#5326) (57914e5fa)
fix(HeaderMenu): re-enabled links in submenu (#5296) (55f44c9cc)
fix(ui-shell): fix onclick menu bugs (#5274) (616b18259)
fix(notification): update status icon description prop (#5266) (3e77d6d07)
fix(tooltip): ensure tooltip is not hidden in storybook (#5304) (b8c1e1c57)
fix(ui-shell): update SideNavLink proptype (#5256) (5822571de)
fix(ui-shell): allow custom classes on HeaderSideNavItems (#5275) (4b9cc7c2e)
fix(slider): change prop to stepMultiplier and deprecate stepMuliplier (#5251) (dbce79476)
fix(number-input): adjust invalid logic and add proptype check for value (#5217) (115de18a2)
fix(link): remove visited styles by default (#5239) (3c6bff698)
fix(file-uploader): adjusts default button and removes clear file button (#5166) (054b1da43)
fix(ui-shell): remove role='menu' from ui-shell (#5235) (eb9412f9d)
fix(Tab): hoist tab role to upper element (#5173) (d6a36a9d9)
fix(data-table): also add ref to non-sortable branch in TableHeader (#5204) (132dbfb46)
fix(code-snippet): remove focus from snippet container (#5202) (625a98bb7)
fix(FilterableMultiSelect): open item list when searching (#5192) (8faf1f7b1)
fix(tile): adds onChange call to handlers in selectable tile (#5156) (1ebf04a16)
fix(TableToolbarSearch): allow default values to be set (#5089) (e97a7ed9b)
fix(multiselect): replace checkbox with visually identical element (#5039) (88fd0afbe)
fix(storybook): remove layer import (#5160) (e3b3f0e2e)
fix(text-input): rename sizing props (#5167) (8c577c53c)
fix(tag): add default cursor to non-filter tag (#5140) (0fbfae935)
fix(Tabs): allow keyboard event defaults (#5124) (cd62e62a4)
fix(tabs): un-comment hidden prop to be add to root elem (#5120) (b30d5f688)
fix(time-picker): update icon to chevrondown16 (#5115) (fd67b897e)
fix(TableBatchActions): ensure hidden action bar un-focusable (#5081) (b994c9af8)
fix(breadcrumbs): add spread attribute to root node (#5108) (cb2a1ecbd)
fix(pagination): use descriptive id for right hand select (#5109) (f04f03b88)
fix(TooltipIcon): add new direction prop types (#5051) (b5b4cb54b)
fix(ui-shell): remove role banner from header ui-shell (#5077) (766929991)
fix(Tabs): add ARIA attributes (#4970) (0add8cc8a)
fix(structured-list): fix DAP errors (#5066) (0f1f2876f)
fix(ui-shell): remove role="menuitem" from header links (63c950e94)
fix(code-snippet): update export pattern to include missing export (de233aad2)
fix(tabs): truncate container tab header text with ellipses (#5035) (532ebc864)
fix(InlineLoading): change error icon to filled (#5018) (2f9ffa67e)
fix(FileUploaderDropContainer): fix NPE selecting file (#4936) (f4cb71c98)
fix(uishell): close HeaderMenu on blur (#5003) (79fc14b2e)
fix(listbox): set default title attributes to item text (#5102) (62024063d)
fix(Tag): ignore click events when disabled (#4792) (3264b8c22)
fix(DatePicker): fix programmatic set of date in range mode (#4814) (ba9616498)
fix(DatePicker): fix calendar dropdown position (#4846) (4a7f458a3)
fix(CodeSnippet): use tooltip styles for feedback and add animation (#4741) (62217bdc0)
fix(Tabs): ignore disabled tabs on keyboard navigation (#4784) (f430a1446)
fix(radio-tile, selectable-tile): deprecate iconDescription and add handleOnChange function (#4966) (6a70073ea)
fix(ComboBox): bring IME support back (#4952) (f788410fa)
fix(checkbox-skeleton): apply skeleton class to checkbox (#4923) (4af62e67f)
fix(DatePicker): explicitly update minDate and maxDate (#4912) (731583027)
fix(date-picker): support changing date format (#4856) (2ca548e62)
fix(ComboBox): ensure unique keys (#4999) (b92e2407b)
fix(multi-select): fix DAP violations (#4991) (8a20d0e5e)
fix(dropdown): use itemToElement for selected label if not null (#4977) (057e35cfc)
fix(tag): adds various fixes for screen reader accessibility; adds AAT (#4863) (00786f81a)
fix(dropdown): revert id change to have stable identifier (#4935) (a506f76ae)
fix(search): adjust icon and hover styles on Close16 button for Chrome's new autofill color (#4891) (62dee03b5)
fix(button): add elementType to 'as' property type check (#4893) (#4895) (0144dfeea)
fix(devenv): use content margin style for expanded side nav (#4886) (4bd977619)
fix(inline-notification): add 8px right padding if close button is hidden (#4873) (16f50a617)
fix(table-header): forward ref for (#4877) (f65f115dc)
fix(UIshell): adds story for SkipToContent and removes the tabIndex prop requirement (#4875) (04ed48019)
fix(data-table): update menu to match visible and accessible labels (#4862) (7663fe682)

`@carbon/themes@10.10.3`

`@carbon/colors@10.8.0`
>Bug fixes 🐛
fix(colors): update rgb hex colors clr (#5139) (1a7203300)

**Comment by davidicus** [comment]
- delete layer global mixin
- copy old formItem story since Carbon deleted theirs. This lets people be aware of it from storybook. 
- SideNav has some css changes needed for menu sub items
-

**Comment by cgirani** [comment]
MAS team depends on some fixes done in FileUploaderContainer 

https://github.com/carbon-design-system/carbon/pull/4936

**Comment by davidicus** [comment]
Carbon removed `handleTabAnchorFocus` in https://github.com/carbon-design-system/carbon/commit/83ddb6a722cd5b5de9e947feafffccb1173de048#diff-fc9dc2c53f4ac6f9a14e2ff6741c85af. Good catch Taylor
