### ISSUE TITLE
[List] Embedded row action buttons renders unnecessary scrollbars

### ISSUE THREAD

**Issue by tomklapiscak** [IBM/carbon-addons-iot-react#988]
### Describe the bug

![image](https://user-images.githubusercontent.com/7372253/76103817-40001080-5fca-11ea-9d80-37a26502afbf.png)

### To Reproduce

See https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-list--with-row-actions-single

### Expected behavior
scrollbars should be suppressed (`overflow: hidden`?)

### Environment/versions:

- OS: Fedora
- Browser: Chrome
- `carbon-addons-iot-react` version: `v2.54.1`

**Comment by jessieyan** [comment]
For some reason, I don't see the scroll bar in my browser.
